infra-geo-ouverte/igo2-lib

src/demo-app/app/app.component.html
src/lib/map/map-browser/index.ts
src/lib/map/map-browser/map-browser-binding.directive.ts
src/lib/map/map-browser/map-browser-binding.spec.ts
src/lib/map/map-browser/map-browser.component.spec.ts
src/lib/map/map-browser/map-browser.component.ts
src/lib/map/module.ts

- Directive to allow binding a map browser to the map service. This allows for multiple map browser but only one can be binded to the map service at once.

feat(map): map browser binding directive

---

src/demo-app/app/app.component.html
src/demo-app/app/app.component.styl
src/demo-app/app/app.component.ts
src/demo-app/assets/locale/en.json
src/demo-app/assets/locale/fr.json
src/lib/form/fields/index.ts
src/lib/form/fields/map-field/index.ts
src/lib/form/fields/map-field/map-field.component.html
src/lib/form/fields/map-field/map-field.component.spec.ts
src/lib/form/fields/map-field/map-field.component.styl
src/lib/form/fields/map-field/map-field.component.ts
src/lib/form/index.ts
src/lib/form/module.ts
src/lib/map/map-browser/map-browser.component.ts
src/lib/map/shared/map.ts
src/lib/module.ts
src/lib/query/shared/query.directive.ts

- Reactive form custom field to select a location on a map

feat(form): map field

---

src/demo-app/app/app.component.html
src/demo-app/app/app.component.ts
src/demo-app/app/module.ts
src/lib/feature/shared/feature.enum.ts
src/lib/feature/shared/feature.interface.ts
src/lib/map/shared/map.ts
src/lib/search/search-sources/datasource-search-source.ts
src/lib/search/search-sources/index.ts
src/lib/search/search-sources/nominatim-search-source.ts
src/lib/shared/clone/clone.pipe.spec.ts
src/lib/shared/clone/clone.pipe.ts
src/lib/shared/clone/index.ts
src/lib/shared/module.ts
src/lib/tool/module.ts
src/lib/tool/tools/search-results-tool/search-results-tool.component.spec.ts
src/lib/tool/tools/search-results-tool/search-results-tool.component.ts

- Data source search souce that allows searching for a datasource
- For now, the service searchs into an MSP service
- Update search results tool to make it add the selected datasource result

feat(search): datasource search source

---

src/demo-app/app/app.component.ts
src/demo-app/app/module.ts
src/lib/context/shared/context.service.ts
src/lib/context/shared/layer-context.directive.ts
src/lib/core/index.ts
src/lib/core/route/index.ts
src/lib/core/route/route.interface.ts
src/lib/core/route/route.service.spec.ts
src/lib/core/route/route.service.ts
src/lib/search/search-bar/search-url-param.directive.ts

These params are added: 
context=contextName
center=-73.5,-46.8  (lon, lat)
projection=EPSG:4326
zoom=5

feat(urlParams): add url params to define map view and context

---

src/lib/core/route/route.interface.ts
src/lib/core/route/route.service.ts
src/lib/datasource/shared/datasources/feature-datasource.ts
src/lib/layer/layer-item/layer-item.component.html
src/lib/layer/layer-item/layer-item.component.ts

If a param named "id" is specified into the context.json user can refer to this value into the url to toggle visibility over pre-defined values into the context. If there is no id defined into the context.json, user can use a pre-generated key (Md5.hashStr(..)).  User can refer to the layer's tooltip to grab the id's value. No "cut and paste" behavior at this time on the tool-tip.
Allowed values are
-  =* (star) for everything         
- comma-separated list : ex =id1,id2
Note that * values are interpreted before named id controls. 
ex: 
http://url/igo2/?context=mtq&invisiblelayers=*&visiblelayers=id1,id2
http://url/igo2/?context=mtq&invisiblelayers=id1,id2&visiblelayers=*
http://url/igo2/?context=mtq&invisiblelayers=id1&visiblelayers=id2

Adding route param invisiblelayers and visiblelayers

---

src/lib/feature/feature-details/feature-details.component.html
src/lib/feature/feature-details/feature-details.component.ts
src/lib/query/shared/query.service.ts

According to issue #109 , innerhtml param (as defined into the context.json) was "destroying" style and script from html response for each feature. 
Before: slicing html response from < body> to < /body>
and putting it into the template. 
Now: Checking if <body></body> is not empty and then, putting into the template inside an iframe.

Issue #109 Innerhtml wms getfeatureinfo response : entire content instead of only body 

---

src/lib/catalog/catalog-layers-list/catalog-layers-list-binding.directive.ts
src/lib/catalog/shared/catalog.interface.ts

Dig multiples levels in getCapabilities service
Add regex filter on layer's name when added by getCapabilities

Dig multiples levels in getCapabilities service

---

src/demo-app/app/app.component.html
src/demo-app/contexts/_default.json
src/demo-app/contexts/embacle.json
src/demo-app/contexts/wfs_test.json
src/demo-app/contexts/wms_filter.json
src/lib/filter/ogc-filter-form/ogc-filter-form.component.html
src/lib/filter/ogc-filter-form/ogc-filter-form.component.styl
src/lib/filter/ogc-filterable-item/ogc-filterable-item.component.html
src/lib/filter/ogc-filterable-item/ogc-filterable-item.component.ts
src/lib/filter/ogc-filterable-list/ogc-filterable-list.component.html
src/lib/layer/layer-item/layer-item.component.html
src/lib/layer/layer-item/layer-item.component.ts
src/lib/layer/layer-list/layer-list.component.html
src/lib/layer/layer-list/layer-list.component.ts
src/lib/layer/module.ts
src/lib/tool/module.ts
src/lib/tool/tools/index.ts
src/lib/tool/tools/map-details-tool/map-details-tool.component.html
src/lib/tool/tools/map-details-tool/map-details-tool.component.ts
src/lib/tool/tools/map-details-tool/map-details-tool.interface.ts
src/lib/tool/tools/ogc-filter-tool/index.ts
src/lib/tool/tools/ogc-filter-tool/ogc-filter-tool.component.html
src/lib/tool/tools/ogc-filter-tool/ogc-filter-tool.component.spec.ts
src/lib/tool/tools/ogc-filter-tool/ogc-filter-tool.component.ts
src/locale/en.json
src/locale/fr.json

Adding an ogcFilter-tool in the toolbar.
IF the context.json contain a  
`"toolbar": ["ogcFilter"],`
and  `  "tools": [{"name": "ogcFilter"}]`
User will be able to edit filters. 
Into the mapDetails options, you can control IF the filter will be shown into the layer-list-item section or not.
`{
"name": "mapDetails",
"options": {"ogcFiltersInLayers": true }
},`
See picture bellow.
ON CLICK GIVE

Ogc filter toolbar

---

package-lock.json
package.json
src/lib/feature/feature-details/feature-details.component.html
src/lib/feature/shared/feature.interface.ts

Define FeatureGeometry type to the correct list of geometry type (exclude Circle for a GeoJSON)
Fix feature.properties to be not required for real

Fix FeatureGeometry type and feature.properties not required

---

src/lib/datasource/shared/datasources/wfs-datasource.ts
src/lib/datasource/shared/datasources/wms-datasource.ts
src/lib/download/shared/download.service.ts
src/lib/feature/shared/feature.service.ts
src/lib/filter/ogc-filter-form/ogc-filter-form.component.html
src/lib/filter/ogc-filterable-item/ogc-filterable-item.component.ts
src/lib/layer/layer-item/layer-item.component.html
src/lib/query/shared/query.directive.ts
src/locale/en.json
src/locale/fr.json

Adjustements in igo-lib to fit with the structure of igo-api. See https://github.com/infra-geo-ouverte/igo2-api/pull/5 
Modyfied features to fit with igo-api:
- OgcFilter
- SourceFields
- WMS Layer has wfs capabilities IF a wfsSource is set. Adding ability to download data & populate menu (fields and values)
- Download wfs data
Adding a new feature:
- Features are now clickable on the map.

Ajustements for igo-api & Make features clickable

---

src/lib/search/search-bar/search-bar.component.ts
src/lib/search/search-sources/datasource-search-source.ts
src/lib/search/search-sources/icherche-search-source.ts
src/lib/search/search-sources/nominatim-search-source.ts
src/lib/search/search-sources/search-source.interface.ts
src/lib/search/search-sources/search-source.ts
src/lib/search/shared/search.service.ts

Indenpendent FeatureService and Search Service. Was mandatory to exploit searchResults without populating Feature service. 
Adding locate by coordinates for nominatim & icherche sources.

Independent search service&reverse geocode

---

src/lib/download/shared/download.service.ts

This value was undefined if IGO2 is not used with the IGO-API.

Fix for undefined value

---

src/lib/datasource/shared/datasources/datasource.interface.ts
src/lib/query/shared/query.directive.ts

Adding dragbox selection
Adding displayField logic for clicked Features.  => you must set a "displayField": "fieldName", in your context.

Manage drag box on feature select

---

demo/src/app/geo/layer/layer.component.ts
projects/geo/src/lib/datasource/shared/datasources/datasource.interface.ts
projects/geo/src/lib/datasource/shared/datasources/wms-datasource.interface.ts
projects/geo/src/lib/datasource/shared/datasources/wms-datasource.ts

Refresh WMS layer based on a parameter. #165 
An enhancement would be to refresh WFS & Feature Datasources. 
```
[ ] Yes
[X] No
```

Refresh interval on WMS

---

demo/src/app/geo/search/search.module.ts
demo/src/environments/environment.prod.ts
demo/src/environments/environment.ts
projects/core/src/lib/request/logging.interceptor.ts
projects/geo/src/lib/search/search-bar/search-bar.component.ts
projects/geo/src/lib/search/search-sources/datasource-search-source.ts
projects/geo/src/lib/search/search-sources/icherche-search-source.ts
projects/geo/src/lib/search/search-sources/index.ts
projects/geo/src/lib/search/search-sources/nominatim-search-source.ts
projects/geo/src/lib/search/search-sources/reseau-transport-quebec-search-source.ts
projects/geo/src/lib/search/search-sources/search-source.interface.ts
projects/geo/src/lib/search/search-sources/search-source.provider.ts
proxy.conf.json

Adding new search sources for the Quebec Provincial road network (municipal network excluded).
- a-5 will return the complete linestring for highway # 5
- 20  will return the complete linestring for highway # 20
- 138+700 will return a point on road 138, a the specific KM (km 700) This is note interpolation, the position represent physical signs on the road.
- -71.292469,46.748107 will propose you some roads around this coordinate.
For expert user:
- 2006 or 0002006 will return the complete linestring for highway # 20, segment 06
- 2006051 or 0002006051 will return the complete linestring for highway # 20, segment 06, section # …

Reseau transport quebec

---

projects/geo/src/lib/layer/layer-list/layer-list.component.html

When layers's list length is under 5, the is an empty space above the list. 
Fix issue #187 
The is an empty space above the list is removed.
```
[ ] Yes
[X] No
```

fix(layer-list) Fix issue # 187

---

demo/src/app/geo/feature/feature.component.ts
demo/src/app/geo/search/search.component.ts
demo/src/environments/environment.ts
projects/geo/src/lib/overlay/shared/index.ts
projects/geo/src/lib/overlay/shared/overlay.directive.ts
projects/geo/src/lib/overlay/shared/overlay.enum.ts
projects/geo/src/lib/overlay/shared/overlay.interface.ts
projects/geo/src/lib/overlay/shared/overlay.service.ts
projects/tools/src/lib/search-results-tool/search-results-tool.component.ts

On click on results, the current behavior is to zoom to the feature, despite if the feature is already contained in map extent...
Prevent zoom on if feature extent is in map. 
```
[ ] Yes
[ ] No
```

feat(*) Prevent zooming on result if already contained in map extent

---

demo/src/app/geo/search/search.module.ts
demo/src/environments/environment.prod.ts
demo/src/environments/environment.ts
projects/context/src/lib/sidenav/sidenav.component.html
projects/context/src/lib/sidenav/sidenav.component.ts
projects/geo/src/lib/feature/shared/feature.interface.ts
projects/geo/src/lib/overlay/shared/overlay.directive.ts
projects/geo/src/lib/search/search-sources/icherche-search-source.ts
projects/geo/src/lib/search/search-sources/nominatim-search-source.ts
projects/geo/src/lib/search/search-sources/reseau-transport-quebec-search-source.ts
projects/geo/src/lib/search/search-sources/search-source.interface.ts

- [ X] The commit message follows our guidelines:https://github.com/infra-geo-ouverte/igo2/blob/master/.github/CONTRIBUTING.md#git-commit-guidelines
Cleaner zoom behavior on search or query
Previously (pr #193), the zoom behavior was based on feature extent. This way to check intersection was incorrect. In the case a small map extent was covered by a large feature (large extent), extents were intersecting but not the geometry. This PR fix it. 
**Now** 
if the geometry do not overlap map extent = Zoom
if the number of vertice intersecting the geometry / Total vertices  is under or equal to 5%, = zoom out.
e.g. 5 vertices are …

Feature zoom if not in extent based on feature geometry. 

---

projects/context/src/lib/tool/toolbar-item/toolbar-item.component.html
projects/context/src/lib/tool/toolbar-item/toolbar-item.component.ts
projects/context/src/lib/tool/toolbar/toolbar.component.html
projects/context/src/lib/tool/toolbar/toolbar.component.ts

The toolbar doesn't emit a click event. It only emit a select event. The select event is not appropriate
for all use cases because it's only emited if the selected item changes.
The toolbar emits a click event everytime an item is clicked, even if it's the currently selected item.
```
[ ] Yes
[x] No
```

toolbar emit a click event as well as the usual select event

---

projects/geo/src/lib/datasource/shared/datasources/datasource.interface.ts
projects/geo/src/lib/query/shared/query.directive.ts
projects/geo/src/lib/search/search-sources/reseau-transport-quebec-search-source.ts

Deprecated empty observable in reseau-transports-quebec search sources.
displayField for vector feature (file and service) were not usable
Remplacement of empty() for of([])
Redirection from displayField to queryTitle (sourceOptions)
```
[ ] Yes
[X] No
```

Enable display field

---

projects/geo/src/lib/datasource/shared/datasources/wms-datasource.ts
projects/geo/src/lib/query/shared/query.service.ts

if queryFormat format is set (` "queryFormat": "html"` ) there is no way to change the info_format used into the url for GetfeatureInfo (wms sources)
for wms-datasources, into the params section, if a info format is provided, this format will be used to query the service. 
This new way do not remplace the way to parse the returned format, only the way to call the service. If you want to parse a new format, you must make a PR.... 
This PR is done to provide a way to call a service into a html format, but with a non-standard name.
Ex: Called Format = html, Called Format Name = text/html2.
Same thing probably applyable for gml2 with …

feat(wms-datasources) a way to bypass info_format given for getinfo

---

projects/context/src/lib/tool/shared/tool.service.ts
projects/core/src/lib/route/route.interface.ts
projects/core/src/lib/route/route.service.ts

Adding a way to control which tool is open on page initialization. Creating keys and an array of allowed tool names.
Linked with PR infra-geo-ouverte/igo2#236
```
[ ] Yes
[X] No
```

Control tool at opening

---

projects/geo/src/lib/query/shared/query.directive.ts
projects/geo/src/lib/query/shared/query.service.ts
projects/geo/src/lib/routing/routing-form/routing-form.component.ts

When the direction component is activated, when the user fire a click, the query directive is called and focus on results. 
Moving the queryLayers to service allow another component to control the active queryLayers. In this case, in the routing (direction) component, the query on layers is not activated. When the user leave the component, the layers become queryable again
```
[ ] Yes
[x] No
```

Query layers and directions

---

projects/geo/src/lib/query/shared/query.directive.ts
projects/geo/src/lib/query/shared/query.service.ts
projects/geo/src/lib/routing/routing-form/routing-form.component.ts

The way to control query was to remove layer from the queryLayers array.
The side effect was that the wms layers where not queryable, but the vector sources (files or service based i.e. wfs) where still queryable. 
The main effect was on start/stop digitizing (by click on map) in the routing component, the querydirective was fired on vector sources.
On opening the routing component, the query service will store a param blocking the querydirective to be executed. Non destroy, the layers become now queryable.
```
[ ] Yes
[x] No
```
If this PR contains a breaking …

Proper way to control queries from another component

---

projects/geo/src/lib/query/shared/query.service.ts

Vector source without activated (or available) wms layer cannot be queryed.
The vector source are now queryable.
```
[ ] Yes
[X] No
```

Fix query with undefined url

---

projects/geo/src/lib/catalog/catalog-layers-list/catalog-layers-list-binding.directive.ts
projects/geo/src/lib/datasource/shared/capabilities.service.ts
projects/geo/src/lib/metadata/shared/metadata.interface.ts

1- Layers added from catalog didn't have timefilterable enabled if the layer has these capabilities.  
2- Layers added from catalog didn't have metadata enabled if the layer has these capabilities.  
Fix the previous behavior by providing these options from catalog OR from context's layer defined  with "optionsFromCapabilities": true 
```
[ ] Yes
[X] No
```

Fix WMS capabilities

---

projects/common/src/lib/panel/panel.component.html
projects/common/src/lib/panel/panel.component.scss
projects/common/src/lib/panel/panel.component.ts
projects/common/src/lib/panel/panel.module.ts

There is no way to create a panel withtout a header
With the input "withHeader" set to false, the panel will have no header.
```
[ ] Yes
[x] No
```

feat(panel): make it possible to create a igo-panel without a header

---

package.json
projects/geo/src/lib/print/print-form/print-form.component.html
projects/geo/src/lib/print/print-form/print-form.component.scss
projects/geo/src/lib/print/print.module.ts
projects/geo/src/lib/print/shared/print.service.ts
projects/geo/src/locale/en.geo.json
projects/geo/src/locale/fr.geo.json

Issue #189 
Toggle options
Selectbox for orientation
Margins correction
```
[ ] Yes
[ x ] No
```

Issue #189 Print options fix

---

projects/context/src/lib/share-map/share-map/share-map-binding.directive.ts
projects/context/src/lib/share-map/share-map/share-map.component.ts
projects/context/src/lib/share-map/shared/share-map.service.ts
projects/core/src/lib/route/route.interface.ts
projects/core/src/lib/route/route.service.ts
projects/geo/src/lib/layer/layer-list/index.ts
projects/geo/src/lib/layer/layer-list/layer-list-binding.directive.ts
projects/geo/src/lib/layer/layer-list/layer-list.component.html
projects/geo/src/lib/layer/layer-list/layer-list.component.ts
projects/geo/src/lib/layer/layer-list/layer-list.enum.ts
projects/geo/src/lib/layer/layer-list/layer-list.service.spec.ts
projects/geo/src/lib/layer/layer-list/layer-list.service.ts
projects/geo/src/lib/layer/layer.module.ts
projects/tools/src/lib/map-details-tool/map-details-tool.component.html
projects/tools/src/lib/map-details-tool/map-details-tool.component.ts
projects/tools/src/lib/map-details-tool/map-details-tool.interface.ts

Layer list toolbar only have a behavior:
- default = shown if there is more than 5 layers
1. Introducing other behavior to layer list toolbar 
- always
- never
- default
These behavior can be controlled by new options in yourcontext.json:
`{ "name": "mapDetails",`
`      "options": {`
`        "layerListControls": {`
`          "showToolbar": 'default',        'never' or 'always, if no value provided, default is used.`
`          "toolbarThreshold": 15, if no value provided, 5 by default,  option not used for always or never values)` 
` }}}`
For the default behavior, you can control the threshold (number of layers) at which the …

Layer list toolbar

---

projects/geo/src/lib/feature/feature-details/feature-details.component.html
projects/geo/src/lib/feature/feature-details/feature-details.component.ts
projects/geo/src/lib/feature/shared/feature.interface.ts
projects/geo/src/lib/query/shared/query.directive.ts
projects/geo/src/lib/query/shared/query.service.ts

There is no way to provide alias to datasources.
1.  By using the sourceFields param (also used for ogc-filter) , you can provide an alias to a field
`"sourceFields": [`
`          {"name": "fieldname", "alias": "fieldAlias"},`
`          ....`
`          ...`
`        ]}`
2. When you click on map to query the vector source, the result is now grouped with the layer title instead of a generic group name named  "Clicked feature". e.g.
Before:
After:
```
[ ] Yes
[x] No
```
If this PR contains a breaking change, please describe the impact and migration path for …

Provide ALIAS to wms getfeatureinfo(gml), wfs and vector datasources

---

projects/geo/src/lib/layer/layer-list/layer-list.component.ts

Into the mapDetails tool, layer list could be controled/subsetted by
-  layer title
-  type
- visiblity  (visible or in scale range)
Adding a way to control/subset  by keyword.
The keyword could be provided by 2 ways:
1. "optionsFromCapabilities": true,   ==> wms layer's keywords
2.  "metadata": {
"keywordList": ["your","own","keyword", "list"]
}
```
[ ] Yes
[x] No
```

feat(layer-list)Allow search with layer keyword (capabilitie or context)

---

projects/geo/src/lib/datasource/shared/datasources/wms-datasource.ts
projects/geo/src/lib/filter/ogc-filterable-item/ogc-filterable-item.component.html
projects/geo/src/lib/filter/ogc-filterable-item/ogc-filterable-item.component.ts
projects/geo/src/lib/filter/shared/ogc-filter.ts

Ogc filters defined in a context were note interpreted on wms layer creation. The layer was filtered only when the ogcfilter tool was called.
1- Layer is now filtered on layer creation.
2- Ogcfilter sent are now case sensitive.
See https://github.com/mapserver/mapserver/pull/5512.
```
[ ] Yes
[x] No
```

OGC Filters

---

demo/src/environments/environment.ts
projects/geo/src/lib/search/search-sources/reseau-transport-quebec-search-source.ts
projects/geo/src/lib/search/search-sources/search-source.interface.ts

When using the search bar, the search source was trying to detect which service (wfs) to call. 
Sometime, the wrong service was called and no features were returned.
For each search into the searchbar, every service from this search source are called. 
* Adding a way to find roads exits (number of the exit, not by road).
* Providing alias for search sources  (config.json)
* Providing a way to control search distance into config.json (distance in km).
```
[ ] Yes
[x] No
```
If this PR contains a breaking change, please describe the impact and migration path for …

refactor reseau-transport-quebec search sources

---

demo/src/app/context/context/context.component.html
demo/src/app/geo/directions/directions.component.html
demo/src/app/geo/print/print.component.html
demo/src/app/geo/simple-map/simple-map.component.html
demo/src/app/geo/simple-map/simple-map.component.ts
projects/geo/src/lib/map/index.ts
projects/geo/src/lib/map/map-browser/map-browser.component.scss
projects/geo/src/lib/map/map.module.ts
projects/geo/src/lib/map/rotation-button/index.ts
projects/geo/src/lib/map/rotation-button/rotation-button.component.html
projects/geo/src/lib/map/rotation-button/rotation-button.component.scss
projects/geo/src/lib/map/rotation-button/rotation-button.component.ts
projects/geo/src/lib/map/shared/map.ts
projects/geo/src/locale/en.geo.json
projects/geo/src/locale/fr.geo.json

Allow to reset view rotation
```
[ ] Yes
[x] No
```

Reset rotation to map view

---

projects/common/src/lib/custom-html/custom-html.component.html
projects/common/src/lib/custom-html/custom-html.module.ts
projects/common/src/lib/custom-html/custom-html.pipe.ts
projects/common/src/lib/custom-html/index.ts

Some content (string) passed to the custom html component are sanitized and then, unusable. 
Ex: `<h1 style="color:blue;margin-left:30px;">This is a heading</h1>"`
The style was not used. 
The declared html is not sanitize anymore.  
```
[ ] Yes
[x] No
```

fix(custom-html) ByPassTrustHtml for string declared as html

---

projects/geo/src/lib/datasource/shared/datasources/wms-datasource.ts
projects/geo/src/lib/query/shared/query.service.ts
projects/geo/src/lib/search/search-sources/reseau-transport-quebec-search-source.ts
projects/geo/src/lib/search/search-sources/search-source.interface.ts

1- Service only in WMS 1.1.1 were not usable until srs param was set into the layer's param. 
2- Some getfeatureinfo results were not usable due to geometry field name that was not removed from properties 
1- Throw an error if SRS not filled.
2- removing extra geometry name field. 
3- Refactor properties
```
[ ] Yes
[x ] No
```

Various fix

---

projects/geo/src/lib/catalog/catalog-layers-list/catalog-layers-list-binding.directive.ts
projects/geo/src/lib/catalog/shared/catalog.interface.ts
projects/geo/src/lib/catalog/shared/catalog.service.ts

Allow to configure catalog to control which:
-  info_format 
-  html destination (_blank or innerhtml)
-  feature_count 
should be used for getfeatureinfo queries.
```
{
"title": "MTQ Québec",
"url": "https://ws.mapserver.transports.gouv.qc.ca/swtq",
"queryFormat": {
"html": "*",
"json": "stations_meteoroutieres"
},
"queryHtmlTarget": "innerhtml",
"count": 365
}
```
In this case, every layer called by getfeatureinfo will be in text/html. Except for stations_meteoroutieres which be …

Catalog enhancement (info_format, count)

---

packages/geo/src/lib/feature/shared/feature.interfaces.ts
packages/geo/src/lib/feature/shared/feature.utils.ts
packages/geo/src/lib/feature/shared/strategies/loading.ts
packages/geo/src/lib/measure/measurer/measurer.component.ts

There's no functions to initialize a FeatureStore and there's no possibility to control the motion on a FeatureStore load.
Utility functions have been added to initialize a FeatureStore and "motion" has been added to the load strategy of the FeatureStore. Measurer has been adapted to use the new functions.
```
[ ] Yes
[x ] No
```

Init store

---

demo/src/app/geo/ogc-filter/ogc-filter.component.ts
packages/geo/src/lib/datasource/shared/datasources/wms-datasource.ts
packages/geo/src/lib/filter/shared/ogc-filter.service.ts

When you filter a wms layer built from 2 layers
, filter do not work because you try to apply a single filter on 2 layers...
Repeating the filter into the url for every filter.
Ex:
```
"params": {
"layers": "layerA,layerB"
},
```
will build a url like : ...&filter=(...filterforlayerA...)(...filterforlayerB...)
Your layers MUST share the same fields. You can control the fields by this property
```
"sourceFields": [
{"alias":"Alias1","name": "name1", "values": ["value1","value2","value3"]},
{"alias":"Alias2","name": "name2", "values": [1,2,3,4,5,6,7,8]},
]
```
```
[ …
```

Apply same filter on WMS layer with grouped layers (comma separated) 

---

packages/geo/src/lib/datasource/shared/datasources/datasource.ts
packages/geo/src/lib/datasource/shared/datasources/wms-datasource.ts
packages/geo/src/lib/layer/layer-item/layer-item.component.html
packages/geo/src/lib/layer/layer-legend/layer-legend.component.html
packages/geo/src/lib/layer/layer-legend/layer-legend.component.scss
packages/geo/src/lib/layer/layer-legend/layer-legend.component.ts
packages/geo/src/lib/map/shared/map.utils.ts
packages/geo/src/lib/print/print/print.component.ts
packages/geo/src/lib/print/shared/print.service.ts

Layer legend is zoom level agnostic
**What is the new behavior?*
WMS layer legend follows the map's zoom level
```
[ ] Yes
[x] No
```

feat(legend): make the legend adapt with the zoom level

---

demo/src/app/geo/layer/layer.component.html
packages/geo/src/lib/layer/layer-item/layer-item.component.ts
packages/geo/src/lib/layer/layer-list/layer-list.component.html
packages/geo/src/lib/layer/layer-list/layer-list.component.ts
packages/integration/src/lib/map/map-details-tool/map-details-tool.component.html
packages/integration/src/lib/map/map-details-tool/map-details-tool.component.ts
packages/integration/src/lib/map/map-tool/map-tool.component.html
packages/integration/src/lib/map/map-tool/map-tool.component.ts

Visible layers with toggleLegendOnVisibilityChange= true do not show the legend onInit (legend is collapsed).
Now If the layer is visible & expandLegendVisibleLayers= true, legend is now shown on init.
Adding a new property to mapDetails's options : expandLegendVisibleLayers
```
[ ] Yes
[x] No
```

feat(layer) Visible layers show legend onInit

---

packages/geo/src/lib/datasource/shared/datasources/wms-datasource.interface.ts
packages/geo/src/lib/layer/layer-legend/layer-legend.component.html
packages/geo/src/lib/layer/layer-legend/layer-legend.component.ts

The title of grouped wms layers are the name of the layer.
For WMS grouped layers, with "optionsFromCapabilities" set true, the app will try to catch the title from the wms getcapabilities and provide it as the title.
```
[ ] Yes
[x] No
```

feat(wms) Provide title to grouped layers (comma)

---

demo/src/environments/environment.prod.ts
demo/src/environments/environment.ts
packages/geo/src/lib/catalog/shared/catalog.interface.ts
packages/geo/src/lib/catalog/shared/catalog.service.ts
packages/geo/src/lib/layer/layer-item/layer-item.component.html
packages/geo/src/lib/layer/layer-item/layer-item.component.ts
packages/geo/src/lib/layer/layer-list/layer-list.component.ts
packages/geo/src/lib/layer/shared/layers/layer.interface.ts

The tool tip only repeat the layer title
At the layer level, the tooltip could be configured by 3 way
```
"tooltip": {
"type":"title" // layer title, by GetCapabilities or title property in layer config.
},
or
"tooltip": {
"type":"abstract"  // by GetCapabilities Or metadata.abstract property
},
or
"tooltip": {
"type":"custom",
"text": "you custom tooltip"
}
```
At the catalog level, you can configure the tooltip type into config.json
```
{
id: 'catalogwithtooltipcontrol',
title: 'Controling tooltip type',
url: 'https://geoegl.msp.gouv.qc.ca/apis/ws/igo_gouvouvert.fcgi',
tooltipType: 'abstract' // or title
}
```
If you set …

Abstract as tooltip 1.0.0-alpha.1

---

demo/src/app/geo/layer/layer.component.html
packages/integration/src/lib/map/map-details-tool/map-details-tool.component.html
packages/integration/src/lib/map/map-details-tool/map-details-tool.component.ts
packages/integration/src/lib/map/map-tool/map-tool.component.html
packages/integration/src/lib/map/map-tool/map-tool.component.ts

QueryBadge could only be controled by code modification.
QueryBadge can now be set into a the context.json into the (mapDetails or map) properties:
```
{
"name": "map", // or mapDetails
"options": {
"queryBadge": true,
}
},
```
```
[ ] Yes
[x] No
```

feat(layer-list) provide input to show/hide queryBadge on layers

---

demo/src/app/geo/search/search.component.ts
demo/src/environments/environment.prod.ts
demo/src/environments/environment.ts
packages/geo/src/lib/map/shared/map.utils.ts
packages/geo/src/lib/search/shared/search.service.ts

Fix #288 (Reverse coordinate search)
Add a rainbow of possibilities for searching coordinate (multiple formats supported)
Add support for EPSG:32198
- [X ] The commit message follows our guidelines:https://github.com/infra-geo-ouverte/igo2/blob/master/.github/CONTRIBUTING.md#git-commit-guidelines
With LonLat, now accepting UTM, MTM, DD, DMD, DMS, BELL and MM coordinates
Coordinates will be switch for North America if send LatLon
```
[ ] Yes
[X ] No
``` …

rainbow of possibilities for searching coordinate

---

packages/context/src/lib/share-map/shared/share-map.service.ts
packages/geo/src/lib/datasource/shared/datasource.service.ts
packages/geo/src/lib/datasource/shared/datasources/any-datasource.interface.ts
packages/geo/src/lib/datasource/shared/datasources/any-datasource.ts
packages/geo/src/lib/datasource/shared/datasources/cluster-datasource.interface.ts
packages/geo/src/lib/datasource/shared/datasources/cluster-datasource.ts
packages/geo/src/lib/datasource/shared/datasources/datasource.interface.ts
packages/geo/src/lib/datasource/shared/datasources/index.ts
packages/geo/src/lib/layer/shared/clusterParam.ts
packages/geo/src/lib/layer/shared/layer.service.ts
packages/geo/src/lib/layer/shared/layers/vector-layer.interface.ts
packages/geo/src/lib/layer/shared/layers/vector-layer.ts
packages/geo/src/lib/layer/shared/layers/vectortile-layer.ts
packages/geo/src/lib/layer/shared/style.service.ts

Drekss alpha cluster

---

demo/src/app/geo/geometry/geometry.component.ts
packages/geo/src/lib/geometry/geometry-form-field/geometry-form-field-input.component.ts
packages/geo/src/lib/geometry/geometry-form-field/geometry-form-field.component.html
packages/geo/src/lib/geometry/geometry-form-field/geometry-form-field.component.ts
packages/geo/src/lib/geometry/shared/geometry.utils.ts

- [ x ] The commit message follows our guidelines:https://github.com/infra-geo-ouverte/igo2/blob/master/.github/CONTRIBUTING.md#git-commit-guidelines
It's not possible to define custom symbol for geometry input draw tool.
Draw tool cannot be deactivated.
When draw guide is undefined, radius is 0 and no point appears when drawing / also point added to map is too small to be noticeable.
geometry-form-field and geometry-form-field-input now allows to:
- Set color of symbol
- Set icon as point symbol
- Deactivate draw tool by setting null geometry type
- Apply default circle radius of 8 when no draw guide is defined
**Does this PR …

feat{geometry-form-field}: allow to set symbol

---

packages/common/src/lib/entity/entity-table/entity-table.component.html
packages/common/src/lib/entity/shared/entity.interfaces.ts

- [ x  ] The commit message follows our guidelines:https://github.com/infra-geo-ouverte/igo2/blob/master/.github/CONTRIBUTING.md#git-commit-guidelines
Material buttons in Entity Table are of type mat-mini-fab
Can now choose between mat-mini-fab and mat-icon-button style (mat-mini-fab stays default)
```
[ ] Yes
[ x ] No
```

feat(entity-table): add option to choose button style

---

package.json
packages/common/src/lib/list/list.component.spec.ts
packages/context/src/lib/context-manager/context-edit/context-edit.component.ts
packages/context/src/lib/context-manager/context-form/context-form.component.scss
packages/context/src/lib/context-manager/shared/context.service.ts
packages/geo/src/lib/search/search-selector/search-selector.component.ts
packages/geo/src/lib/search/search-settings/search-settings.component.html
packages/geo/src/lib/search/search-settings/search-settings.component.scss
packages/geo/src/lib/search/search-settings/search-settings.component.spec.ts
packages/geo/src/lib/search/search-settings/search-settings.component.ts
packages/geo/src/lib/search/search-settings/search-settings.module.ts
packages/geo/src/lib/search/shared/sources/ilayer.ts
packages/integration/src/lib/context/context-editor-tool/context-editor-tool.component.ts
packages/integration/src/lib/context/context-manager-tool/context-manager-tool.component.ts
packages/integration/src/lib/context/context-permission-manager-tool/context-permission-manager-tool.component.ts

enable / disable a service source with checkbox in settings.
~add hashtag's synonym~
```
[ ] Yes
[x] No
```

Search setting upgrade

---

packages/geo/src/lib/filter/ogc-filter-toggle-button/ogc-filter-toggle-button.component.html
packages/geo/src/lib/filter/ogc-filter-toggle-button/ogc-filter-toggle-button.component.scss
packages/geo/src/lib/filter/ogc-filter-toggle-button/ogc-filter-toggle-button.component.ts
packages/integration/src/lib/about/about-tool/about-tool.component.ts

- the return of line is not managed on the tooltip of ogc filter toggle for the display.
- the multilines is not managed on the about tool and the tooltip of ogc filter toggle in JSON configuration.
On about-tool component
- add the possibility to use a string array in the JSON configuration for the html.
```
{
"name": "about",
"options": {
"html": [
"This is a",
"IGO"]
}
}
```
On ogc-filter-toggle-button componet
- add the management of the return of line on the tooltip;
```
"tooltip": "Barrière,\nCaméras,\nCinémomètre"
```
- add the possibility to use a string array in the JSON configuration for the tooltip. 
Note: The return of …

feat(about-tool, ogc-filter-toggle-button): management of multi-lines

---

packages/geo/src/lib/datasource/shared/datasources/carto-datasource.ts
packages/geo/src/lib/datasource/shared/datasources/tilearcgisrest-datasource.ts
packages/geo/src/lib/datasource/shared/datasources/wms-datasource.ts
packages/geo/src/lib/query/shared/query.interfaces.ts
packages/geo/src/lib/query/shared/query.service.ts

Refer to #306 
Adding a property to show/control if a label is shown on queried result. 
if the property is not set (undefined), no label will be shown.
the property is named mapLabel
```
[ ] Yes
[x] No
```

Add property to show an attribute on map (label)

---

packages/geo/src/lib/layer/shared/layers/vector-layer.ts

- animation appear when layer is not visible  
- label is duplicate when animation is on
no animation when layer is not visible and erase label from cloned style
```
[ ] Yes
[x] No
```

fix(geo.vector-layer.animation) styleVector don't need label.

---

packages/geo/src/lib/feature/feature-details/feature-details.component.ts

…lias's order instead of properties's order
The feature details render the properties based on the feature properties order.
t
```
[ ] Yes
[x] No
```

Order the properties based on allowedFieldsAndAlias instead of feature's properties order.

---

packages/geo/src/lib/filter/ogc-filter-toggle-button/ogc-filter-toggle-button.component.scss

The toggle button sometimes turns to the right and not to the center when navigating the filter option. Sometimes you have to double click on the toggle button to activate or deactivate it.
The toggle button remains centered on the navigation of the filter option. And navigation has become stable again.
```
[ ] Yes
[x] No
```

fix: set text center on toggle button

---

packages/geo/src/lib/query/shared/query-search-source.ts
packages/geo/src/lib/routing/routing-form/routing-form.component.ts
packages/geo/src/lib/search/shared/search.service.ts
packages/geo/src/lib/search/shared/sources/coordinates.ts
packages/geo/src/lib/search/shared/sources/icherche.ts
packages/geo/src/lib/search/shared/sources/ilayer.ts
packages/geo/src/lib/search/shared/sources/nominatim.ts
packages/geo/src/lib/search/shared/sources/source.interfaces.ts
packages/geo/src/lib/search/shared/sources/source.ts
packages/geo/src/lib/search/shared/sources/storedqueries.ts

When a search is triggered programmatically, there is no way to control which source is used. 
The hashtag has been tested but not interesting because hashtag is linked to search result.
adding an option property the filter the sources BEFORE the call. 
2 properties added to TextSearchOptions interface
```
searchType?: 'Feature' | 'Layer'; // refer to search.enum.ts SEARCH_TYPES = [FEATURE, LAYER];
getEnabledOnly?: boolean;
```
searchType refer the the search source type
getEnabledOnly is to bypass or not the user's defined enabled sources. 
Use https://github.com/infra-geo-ouverte/igo2-lib/pull/418/commits/fce7278844a4bd532801570c …

Apply restrictions programatically to search sources

---

packages/geo/src/lib/search/shared/search.utils.ts

Query results could have marker icon (not in IGO because of the way query results are displayed)
- They don't have a marker icon  anymore
```
[ ] Yes
[x] No
```

ui(query): query results don't have a marker icon anymore

---

packages/geo/src/lib/filter/ogc-filter-toggle-button/ogc-filter-toggle-button.component.scss
packages/geo/src/lib/filter/ogc-filterable-item/ogc-filterable-item.component.scss
packages/geo/src/lib/layer/layer-item/layer-item.component.scss

The toggle button not displaying correctly in ie11.  The style flex option is not applied. (link with pullRequest https://github.com/infra-geo-ouverte/igo2-lib/pull/414)
- The toggle button now displaying correctly in ie11.
- Space saving to around the pushButton
```
- fix ie11:
.mat-button-toggle { display: inline-flex; }
.igo-layer-button-group { max-width: 100%; }
- ajust style (space saving): .mat-list-item { height: auto; }
- ajust style (space saving): .igo-layer-button-group { contents; } /* Note: ie11 equivalent: display: ruby-base; ... no polyfills found */
```
**Does this PR introduce a breaking change?** (check one with …

fix: display ogc-filter-button:

---

packages/geo/src/lib/filter/ogc-filter-button/ogc-filter-button.component.ts

the collapse is not available on the push button when the layer is not inResolutionRange
to remove the deactivation of the collapse on the push button when the layer is not inResolutionRange
```
[ ] Yes
[x] No
```

fix: collapse push button when the layer is not inResolutionRange

---

demo/src/app/geo/layer/layer.component.html
packages/integration/src/lib/map/map-details-tool/map-details-tool.component.html
packages/integration/src/lib/map/map-tool/map-tool.component.html

When tracking a feature with #422 the button to stop tracking is not in the layer's option
the button is there
```
[ ] Yes
[x] No
```

fix(integration.map.tool) add button when track a feature

---

packages/geo/src/lib/routing/routing-form/routing-form-binding.directive.ts
packages/geo/src/lib/routing/routing-form/routing-form.component.ts
packages/geo/src/lib/routing/routing-form/routing-form.service.ts
packages/geo/src/lib/routing/shared/routing.interface.ts
packages/geo/src/locale/en.geo.json

The direction tool was not handling multi geometries
Term subscription issue.
The route was not shown when leaving/opening the component again.
```
[ ] Yes
[x] No
```

Directions

---

packages/geo/src/lib/catalog/catalog-browser/catalog-browser.component.ts
packages/geo/src/lib/search/shared/sources/icherche.interfaces.ts

Depending the catalog sort, the added layers were not added respecting this order...
```
[ ] Yes
[x] No
```

fix(catalog)Keep catalog's sort for added layers

---

packages/geo/src/lib/datasource/shared/datasources/wms-datasource.ts

Url containing ? inside their url cause getlegendgraphics recomposition to fail by putting 2 ? into the composed url. 
exemple for mapserver
http://mydomain/cgi-bin/mapserv?map=/home/www/mapserverstuff/mymapfile.map
If the defined url contain a ?, the url/param separator is now a & instead of a ?
```
[ ] Yes
[x] No
```

WMS datasource url containing ? crash getlegendgraphic recomposition

---

packages/geo/src/lib/datasource/shared/datasources/wms-datasource.ts
packages/geo/src/lib/datasource/utils/esri-style-generator.ts
packages/geo/src/lib/layer/shared/layers/layer.ts
packages/geo/src/lib/map/shared/controllers/view.ts
packages/geo/src/lib/map/shared/map.utils.ts

The dpi of the layers depends on the data source:
- WMS 1.3 standard specifies the pixel width : 0.28 mm. That value gives a resolution of 25.4/0.28 = 90.71 dpi approximately. 
- Only GeoServer respect this standard
- MapServer by default has a dpi of 72 but can be modified in the mapfiles
- ArcGIS Server / Qgis Server by default has a dpi of 96
Some visibility issues are present due to poor resolution.
Popular WMS servers extend WMS service with dpi parameters:
- MapServer with MAP_RESOLUTION=value
- GeoServer with FORMAT_OPTIONS=dpi:value
- ArcGIS Server / QGIS Server with DPI=value
Common GIS softwares works with a resolution of 96 dpi. For example, QGIS adds all those parameters …

feat(map): normalize the dpi to 96

---

packages/geo/src/lib/geometry/geometry-form-field/geometry-form-field-input.component.ts

When this component is destroyed, there is still a reference to it somewhere in the angular forms core. Reusing the same form control after that yields to the value being set twice. This is not a common use case.
On destroy, set ready to false to avoid any side-effect.
```
[ ] Yes
[x] No
```

fix(geometry): properly destroy geometry input

---

packages/geo/src/lib/routing/routing-form/routing-form.component.ts

Return multipolygons zoom somewhere of of the earth... unable to zoom back on earth.
Take the firs coordinate of the interior point of polygons.
```
[ ] Yes
[x] No
```

fix(direction) Reverse search proposal for multipolygon

---

demo/src/app/geo/query/query.component.ts
packages/geo/src/lib/feature/shared/feature.interfaces.ts
packages/geo/src/lib/feature/shared/feature.utils.ts
packages/geo/src/lib/query/shared/query.directive.ts
packages/geo/src/lib/query/shared/query.service.ts

sourceFields is not considered with vector layer
can use sourceFields with vector layer
```
[ ] Yes
[ ] No
[x] Maybe
```
More tests have to be done if there is a breaking change

feat(geo.layer.vector) use sourcefield's alias on query

---

packages/geo/src/lib/map/shared/map.utils.ts
packages/geo/src/lib/search/shared/sources/coordinates.ts

Refer to https://github.com/infra-geo-ouverte/igo2-lib/issues/475
Fix.
```
[ ] Yes
[x] No
```

Fix search for coord with reprojection

---

packages/geo/src/lib/catalog/shared/catalog.service.ts

```
[ ] Yes
[x] No
```
The value of `layerList.Name` is `undefined` when `groupItem` is created with a layergroup with multiple levels (exemple geomet). `groupItem.id` always has a value of `catalog.group.undefined`
When many `groupItem` are added, they have all this same `id` so, only the last added will be display.
In this case, we use `group.Name` instead.

Fix layerList.Name is undefined

---

demo/src/app/geo/layer/layer.component.html
packages/geo/src/lib/filter/filter.module.ts
packages/geo/src/lib/filter/index.ts
packages/geo/src/lib/filter/ogc-filter-button/ogc-filter-button.component.html
packages/geo/src/lib/filter/ogc-filter-button/ogc-filter-button.component.ts
packages/geo/src/lib/filter/ogc-filterable-item/ogc-filterable-item.component.html
packages/geo/src/lib/filter/ogc-filterable-item/ogc-filterable-item.component.scss
packages/geo/src/lib/filter/ogc-filterable-item/ogc-filterable-item.component.ts
packages/geo/src/lib/filter/ogc-filterable-list/ogc-filterable-list.component.html
packages/geo/src/lib/filter/time-filter-button/index.ts
packages/geo/src/lib/filter/time-filter-button/time-filter-button.component.html
packages/geo/src/lib/filter/time-filter-button/time-filter-button.component.ts
packages/geo/src/lib/filter/time-filter-form/time-filter-form.component.html
packages/geo/src/lib/filter/time-filter-form/time-filter-form.component.ts
packages/geo/src/lib/filter/time-filter-item/time-filter-item.component.html
packages/geo/src/lib/filter/time-filter-item/time-filter-item.component.scss
packages/geo/src/lib/filter/time-filter-item/time-filter-item.component.ts
packages/geo/src/lib/filter/time-filter-list/time-filter-list.component.html
packages/integration/src/lib/map/map-details-tool/map-details-tool.component.html
packages/integration/src/lib/map/map-details-tool/map-details-tool.component.ts
packages/integration/src/lib/map/map-tool/map-tool.component.html
packages/integration/src/lib/map/map-tool/map-tool.component.ts

OGC filters are accessed from ogcFilter tool and from the layer list as a layer option.
Time filters are accessed from timeFilter tool only.
From the ogcFilter tool and  timeFilter tool, if the user want to see the legend, he have to navigate to map/mapDetails tool.
1- Provide time filter button in layer list for time enabled layer.
3- Add a legend ogcFilter tool and  timeFilter tool by clicking on the layer title. 
```
[x] Yes
[ ] No
```
**MINOR BREAKING CHANGE** 
The integration tool options for mapDetails / map is now renamed from 
ogcFiltersInLayers to …

Unify filter access

---

demo/src/app/geo/layer/layer.component.ts
demo/src/app/geo/ogc-filter/ogc-filter.component.ts
demo/src/app/geo/print/print.component.ts
demo/src/app/geo/time-filter/time-filter.component.ts
demo/src/app/geo/workspace/workspace.component.ts
packages/context/src/lib/share-map/shared/share-map.service.ts
packages/geo/src/lib/catalog/shared/catalog.service.ts
packages/geo/src/lib/datasource/shared/capabilities.service.ts
packages/geo/src/lib/datasource/shared/datasource.service.ts
packages/geo/src/lib/datasource/shared/datasources/wms-datasource.interface.ts
packages/geo/src/lib/datasource/shared/datasources/wms-datasource.ts
packages/geo/src/lib/datasource/utils/id-generator.ts
packages/geo/src/lib/filter/shared/ogc-filter.service.ts
packages/geo/src/lib/filter/shared/ogc-filter.ts
packages/geo/src/lib/filter/shared/time-filter.service.ts
packages/geo/src/lib/filter/time-filter-item/time-filter-item.component.html
packages/geo/src/lib/layer/layer-legend/layer-legend.component.ts
packages/geo/src/lib/query/shared/query.service.ts
packages/geo/src/lib/search/shared/sources/ilayer.ts
packages/utils/src/lib/object-utils.ts

Some wms params were duplicated.
**What is the new behavior?
Openlayers strictly interpreting wms params in uppercase. We now redirect all wms params to uppercase.
In case of lowercase user defined wms params, all users wms params will be kept. But every params will be converted into uppercase. 
In case of duplicated param (uppercase & lowercase), the priority remain to the lowercase property (or the property containning less upercase letters). In the next example, the priority to this user defined property is accorded to  `layers`
ex:
``` 
"params": {
"LAYERS": "telephone_urg",
"lAYERS": "telephone_urg",
"laYERS": "telephone_urg",
"layERS": "telephone_urg", …
```

Duplicated WMS params lowercase vs uppercase

---

packages/context/src/lib/context-manager/shared/context.service.ts
packages/context/src/locale/en.context.json
packages/context/src/locale/fr.context.json

Add a significant error message for adding the same permission on context

fix(contexts): add permission error message change

---

demo/src/app/geo/search/search.module.ts
packages/geo/src/lib/search/shared/sources/cadastre.providers.ts
packages/geo/src/lib/search/shared/sources/cadastre.ts
packages/geo/src/lib/search/shared/sources/index.ts

New search source. 
The service allow to search for many specific number. At this moment, when separating numbers by comma, IGO2 'detect' the term as coordinates. Then IGO2 do not trigger the search by term.
10000,100000000 trigger nothing.
The search source only allow to search for 1 cadastre number at each time. 
10000 work properly.
```
[ ] Yes
[x] No
```

feat(search-source)New search by 'cadastre' number

---

packages/context/src/lib/share-map/share-map/share-map.component.html
packages/geo/src/lib/download/shared/download.service.ts
packages/geo/src/lib/filter/ogc-filter-button/ogc-filter-button.component.html
packages/geo/src/lib/filter/shared/ogc-filter.ts

1-Share map notice was not properly aligned
2- Download data from Pushbuttons (ogc-filters) was not equal to the map data. The applied filter for download data was the initial filter (on layer initialisation).
3- For a filterable layer with pushbuttons, if the ogcfilter was not editable, all the filters section was not available in the ui.
Fix
```
[ ] Yes
[x] No
```

Fix ogcFilters Push buttons

---

demo/src/app/geo/search/search.component.html
demo/src/app/geo/search/search.component.ts
packages/geo/src/lib/filter/shared/ogc-filter.ts
packages/geo/src/lib/search/search-bar/search-bar.component.html
packages/geo/src/lib/search/search-bar/search-bar.component.ts
packages/geo/src/lib/search/search-results/search-results.component.ts
packages/geo/src/lib/search/search-settings/search-settings.component.html
packages/geo/src/lib/search/search-settings/search-settings.component.ts
packages/geo/src/lib/search/shared/sources/cadastre.ts

1- Cadastre crash when the search term contains letters. 
2- The pointer summary status was not propagated to the search-settings
```
[ ] Yes
[x] No
```

Fix cadastre and pointer summary setting

---

packages/integration/src/lib/search/search-results-tool/search-results-tool.component.ts

- When a search-result is selected with his top panel (feature-details) and the search tool is deactivate, the panel is still there (collapsed) when we reactivate the search tool

fix(search-results): features-details stays with tool deactivation

---

packages/geo/src/lib/map/shared/controllers/view.ts
packages/geo/src/lib/overlay/shared/overlay.utils.ts

1- Beyond zoom level 17, when selecting a feature, the zoomto action was zooming out to the feature
2- Vertical offset between the pin and the real position.
1- Non prevent to zoom out and set the custom zoom level a level 19.
2- Reducing the offset.
```
[ ] Yes
[x] No
```

Zoom to behavior on feature select/zoomto

---

README.md
packages/geo/src/lib/catalog/catalog-browser/catalog-browser-group.component.html
packages/geo/src/lib/catalog/catalog-browser/catalog-browser-group.component.ts
packages/geo/src/lib/catalog/catalog-browser/catalog-browser-layer.component.html
packages/geo/src/lib/catalog/catalog-browser/catalog-browser-layer.component.scss
packages/geo/src/lib/catalog/catalog-browser/catalog-browser-layer.component.ts
packages/geo/src/lib/catalog/catalog-browser/catalog-browser.component.html
packages/geo/src/lib/catalog/catalog-browser/catalog-browser.component.ts
packages/geo/src/lib/catalog/catalog-browser/catalog-browser.module.ts
packages/geo/src/lib/catalog/shared/catalog.interface.ts
packages/geo/src/lib/filter/shared/spatial-filter.service.ts

Add the possibility to visualize legend from the catalog browser.
By defaut, legend will not be available into the catalog browser.
At the catalog definition level (config.json or environnement./.ts) you must define if the catalog allow or not to show legend.
```
{
id: 'glace',
title: 'Carte de glace',
url: '/apis/ws/radarsat.fcgi',
showLegend: true
},
```
```
[ ] Yes
[x] No
```

Catalog legend

---

packages/geo/src/lib/datasource/shared/capabilities.service.ts
packages/geo/src/lib/datasource/shared/datasources/wms-datasource.ts
packages/geo/src/lib/datasource/shared/datasources/wms-wfs.utils.ts
packages/geo/src/lib/feature/feature-details/feature-details.component.ts
packages/geo/src/lib/search/shared/sources/storedqueries.ts

1- QGis server do not allow lowercase wms or wfs service.
2- For layer with fields aliases, if the field was empty, the field was not shown in the results. 
1- set uppercase
2- keep all the fields
```
[ ] Yes
[x] No
```

Various fixes

---

packages/auth/src/lib/shared/auth.interceptor.ts

In IE11, the hostname of the current element wasn't correctly set. Cause the authentification interceptor to fail.
With resetting the href attribute, the hostname is now correctly set

fix(auth): Fix IE11 authentification interceptor bug

---

packages/context/src/lib/share-map/shared/share-map.service.ts
packages/geo/src/lib/filter/shared/ogc-filter.ts
packages/geo/src/lib/layer/layer-legend/layer-legend.component.ts

With some grouped layers having common styles and/or filters, causing igo to crash on layer call.
```
LAYERS: "layer1,layer2"
```
Prevent empty filters params AND duplicate (or + depending the number of layers in the grouped layer) the style param for grouped layers.
```
[ ] Yes
[x] No
```

better handling grouped layers

---

packages/geo/src/lib/datasource/shared/capabilities.service.ts
packages/geo/src/lib/query/shared/query.enums.ts
packages/geo/src/lib/query/shared/query.service.ts

The format of the query must be defined in the context or the GML2 format is used without checking whether the service provides this format.
The getCapabilities is used to find the supported formats. The priority of formats is:
GeoJSON: application/geojson or geojson
GML3: application/vnd.ogc.gml/3.1.1
GML2: application/vnd.ogc.gml
JSON: application/json
HTML: text/html
The geojson format is prioritized in getCapabilities instead of GML2
**Other …

feat(datasource): retrieve query format from capabilities

---

packages/context/src/lib/context-manager/context-list/context-list.component.html
packages/context/src/lib/context-manager/context-list/context-list.component.scss
packages/context/src/lib/context-manager/context-list/context-list.component.ts
packages/context/src/lib/context-manager/context-list/context-list.enum.ts
packages/context/src/lib/context.module.ts
packages/context/src/locale/en.context.json
packages/context/src/locale/fr.context.json
packages/integration/src/lib/search/search-results-tool/search-results-tool.component.ts

- Allow the user to filter the contexts list similarly to the layer list of the map-details-tool

Context filter

---

packages/geo/src/lib/catalog/shared/catalog.service.ts

The regular expression is not applied to layers without group of wms catalog for the first level of the catalog.
Apply regular expression on layers of first level of catalog.
```
[ ] Yes
[x] No
```
refer to issues #598

fix(catalog): apply regex layers of the first level

---

packages/common/src/lib/list/list.component.scss
packages/geo/src/lib/catalog/catalog-browser/catalog-browser-group.component.scss

Low emphasis due to opacity.
Related to https://github.com/infra-geo-ouverte/igo2-lib/pull/542
Better emphasis
```
[ ] Yes
[x] No
```

Group title emphasis opacity from 0.8 to 0.9

---

packages/geo/src/lib/datasource/shared/datasources/datasource.interface.ts
packages/geo/src/lib/filter/ogc-filter-form/ogc-filter-form.component.html
packages/geo/src/lib/filter/ogc-filter-form/ogc-filter-form.component.ts
packages/geo/src/lib/filter/ogc-filterable-item/ogc-filterable-item.component.ts
packages/geo/src/lib/filter/shared/ogc-filter.enum.ts
packages/geo/src/lib/filter/shared/ogc-filter.ts
packages/geo/src/locale/en.geo.json
packages/geo/src/locale/fr.geo.json

Allowed operator were defined for all the fields
Allowed types are  : 
- 'all' = PropertyIsEqualTo, PropertyIsNotEqualTo, PropertyIsLike, PropertyIsGreaterThan, PropertyIsGreaterThanOrEqualTo, PropertyIsLessThan, PropertyIsLessThanOrEqualTo, PropertyIsBetween, During, PropertyIsNull, Intersects, Within, Contains
- 'spatial' = Intersects and Within
- 'basicandspatial' = PropertyIsEqualTo,PropertyIsNotEqualTo,Intersects and Within 
**(Default value if none provided)**
- 'basic' = PropertyIsEqualTo,PropertyIsNotEqualTo
- 'time' = During
- 'basicnumeric' = PropertyIsEqualTo, PropertyIsNotEqualTo, PropertyIsGreaterThan, - …

Provide operator at the field scale

---

demo/src/app/geo/query/query.component.ts
packages/geo/src/lib/query/shared/query.service.ts

#617 
When the geom is null, create a new geom from urlClick, a square polgone around click, and put it in geometry of features.
```
[ ] Yes
[ ] No
```

feat(QueryService): Add create geom for mapTag when geom is null on extractData #617

---

packages/geo/src/lib/filter/time-filter-form/time-filter-form.component.ts

The years range show in ui reset when the user close the filter detail
https://github.com/infra-geo-ouverte/igo2/issues/359
The years doesn't reset when the user close filter detail
```
[ ] Yes
[x ] No
```

fix(TimeFilter): calendar year range, don't reset year range in UI (igo2 #359)

---

packages/geo/src/lib/layer/layer-item/layer-item.component.ts
packages/geo/src/lib/layer/layer-list/layer-list.component.html
packages/geo/src/lib/layer/layer-list/layer-list.component.ts
packages/geo/src/lib/map/shared/map.ts

- Fix baselayer bug with select all checked
- Fix opacity slider with selection mode

fix(layer-list): fix baselayer with select all and opacity CSS

---

packages/geo/src/lib/layer/layer-item/layer-item.component.ts
packages/geo/src/lib/layer/layer-list/layer-list.component.html
packages/geo/src/lib/layer/layer-list/layer-list.component.ts
packages/geo/src/lib/layer/shared/layers/layer.interface.ts

- Fix select all condition when check manually
- Save check attribute when filters are applied

fix(layer-list): fix selection mode

---

packages/integration/src/lib/map/map-details-tool/map-details-tool.component.ts
packages/integration/src/lib/map/map-legend/map-legend-tool.component.ts
packages/integration/src/lib/map/map-tools/map-tools.component.ts

1-Fix layers subscrition is now based on both resolution change AND layers change
2-Increase the delay before showing the emptyLayers message 
```
[ ] Yes
[x] No
```

Integration fix

---

packages/integration/src/lib/map/map-legend/map-legend-tool.component.ts
packages/integration/src/lib/map/map-tools/map-tools.component.ts

On context change, the configurated value for allowShowAllLegends was not kept. Then on context change, the previous context values were use. Resulting for large contexte to call ALL the legends despite of the configurated value.... 
Fix previous. 
```
[ ] Yes
[x] No
```

Hide all non active legend when allowShowAllLegends is false (on context change)

---

packages/geo/src/lib/catalog/catalog-browser/catalog-browser.component.ts
packages/geo/src/locale/fr.geo.json

[The demo](https://infra-geo-ouverte.github.io/igo2-lib/#/catalog) crash on an empty property
1- translation in french are modified
2- Trap the undefined catalog in the catalog-browser-component

Legend tool translations and catalog empty property.

---

packages/integration/src/lib/filter/spatial-filter-tool/spatial-filter-tool.component.ts

Fix polygon/line layer display. Wasn't entering the if condition when there was only one feature, so the layer was never added to the map.

fix(spatial-filter): fix polygon/line layer display

---

packages/geo/src/lib/import-export/import-export/import-export.component.ts

When exportOptions is undefined , cause export tool to crash.
Skip until exportOptions until the value is not undefined.

fix(importExport)Skip while exportOptions undefined

---

packages/geo/src/lib/import-export/export-button/export-button.component.html
packages/geo/src/lib/import-export/export-button/export-button.component.ts
packages/geo/src/lib/import-export/export-button/index.ts
packages/geo/src/lib/import-export/import-export.module.ts
packages/geo/src/lib/import-export/import-export/import-export.component.html
packages/geo/src/lib/import-export/import-export/import-export.component.ts
packages/geo/src/lib/import-export/shared/export.type.ts
packages/geo/src/locale/en.geo.json
packages/geo/src/locale/fr.geo.json
packages/integration/src/lib/map/map-details-tool/map-details-tool.component.html
packages/integration/src/lib/map/map-details-tool/map-details-tool.component.ts
packages/integration/src/lib/map/map-tool/map-tool.component.html
packages/integration/src/lib/map/map-tool/map-tool.component.ts
packages/integration/src/lib/map/map-tools/map-tools.component.html
packages/integration/src/lib/map/map-tools/map-tools.component.ts
packages/integration/src/lib/map/map.module.ts

1- Non vector layers with download (url) property contained in sourceOptions are not exportable by the import/Export tool. 
2- Vector layer that were not initialized (visibility set to false in config) were not exportable. This cause an error :
1- These layers are now listed exportable. The associated export format is an URL and the form submit open the link. 
2- On layer selection, if the vector contain no feature, the layer visibility is set to true, the opacity = 0 and queryable = false. Then OpenLayers download the features. On the next layer selection (or on tool leave) the previous layer original visibility, opacity and …

Export by url

---

demo/src/app/geo/search/search.component.ts
package-lock.json
package.json
packages/geo/ng-package.json
packages/geo/ng-package.prod.json
packages/geo/package.json
packages/geo/src/lib/feature/feature-details/feature-details.component.html
packages/geo/src/lib/feature/feature-details/feature-details.component.ts
packages/geo/src/lib/search/shared/sources/coordinates.ts
packages/geo/src/lib/search/shared/sources/icherche.ts
packages/geo/src/lib/utils/googleLinks.ts
packages/geo/src/locale/en.geo.json
packages/geo/src/locale/fr.geo.json

- Before : Point, Line and Polygon were all treated the same. Coordinates (lon/lat) were used to open google maps link and cause problems with long geometry.
- Now : If search-result is a Point, use the coordinates and if not, use the name or the title of the result.

fix(GoogleMapsLink): fix line and polygon google maps link

---

packages/geo/src/lib/layer/layer-list-tool/layer-list-tool.component.html

The icon doesn't appear and the tooltip was invert for alpha sort 
I change the icon name 'sort-alphabetical' -> for -> 'sort-alphabetical-variant'
I invert the tooltip whe alpha sort is active or not (IGO2 issus 461)
https://github.com/infra-geo-ouverte/igo2/issues/461
- [x ] No

fix(layer-list-tool) alphaSort icon name+ tooltip

---

demo/src/app/common/entity-table/entity-table.component.html
demo/src/app/common/entity-table/entity-table.component.ts
demo/src/app/common/entity-table/entity-table.module.ts
demo/src/app/geo/legend/legend.component.ts
demo/src/app/geo/workspace/workspace.component.html
demo/src/app/geo/workspace/workspace.component.ts
packages/common/ng-package.json
packages/common/ng-package.prod.json
packages/common/src/lib/entity/entity-table-paginator/entity-table-paginator.component.html
packages/common/src/lib/entity/entity-table-paginator/entity-table-paginator.component.ts
packages/common/src/lib/entity/entity-table-paginator/entity-table-paginator.interface.ts
packages/common/src/lib/entity/entity-table-paginator/entity-table-paginator.module.ts
packages/common/src/lib/entity/entity-table-paginator/index.ts
packages/common/src/lib/entity/entity-table/entity-table.component.html
packages/common/src/lib/entity/entity-table/entity-table.component.ts
packages/common/src/lib/entity/entity-table/entity-table.module.ts
packages/common/src/lib/entity/entity.module.ts
packages/common/src/lib/entity/index.ts
packages/common/src/locale/en.common.json
packages/common/src/locale/fr.common.json
packages/common/src/public_api.ts
packages/context/src/lib/context-manager/shared/context.service.ts

Entity table do not handle pagination
Entity table now handle pagination in a distinct component.
The paginator component is separated from the entity-table to allow various position of the paginator through the application (i.e. : in the header of the workspace component)

entity-table pagination

---

packages/geo/src/lib/catalog/shared/catalog.service.ts
packages/geo/src/lib/directions/directions-form/directions-form.component.html
packages/geo/src/lib/directions/directions-form/directions-form.component.ts
packages/geo/src/lib/feature/feature-details/feature-details.component.html
packages/geo/src/lib/feature/feature-details/feature-details.component.scss
packages/geo/src/lib/feature/feature-details/feature-details.component.ts
packages/geo/src/lib/feature/feature-details/feature-details.directive.ts
packages/geo/src/lib/feature/feature-details/feature-details.module.ts
packages/geo/src/lib/search/shared/sources/icherche.ts
packages/geo/src/locale/en.geo.json
packages/geo/src/locale/fr.geo.json
packages/geo/src/public_api.ts
packages/integration/src/lib/directions/directions-tool/directions-tool.component.html
packages/integration/src/lib/directions/directions-tool/directions-tool.component.ts
packages/integration/src/lib/directions/directions.state.ts
packages/integration/src/lib/search/search-results-tool/search-results-tool.component.html
packages/integration/src/lib/search/search-results-tool/search-results-tool.component.ts

- Add a routing attribute on feature-details directive
-  Allow the user to draw the route between his position (starting point) and the selected feature (ending point)
- If the user has not allow the geolocate function, only the ending point is added to the directions tool

Feature details routing

---

packages/geo/src/lib/catalog/shared/catalog.service.ts
packages/geo/src/lib/datasource/shared/capabilities.service.ts
packages/geo/src/lib/layer/shared/layers/vector-layer.ts
packages/geo/src/locale/en.geo.json
packages/geo/src/locale/fr.geo.json

What is the current behavior? (You can also link to an open issue here)
In catalog when service getCapabilities return Acces Denied, the app throw an error: cannot read property 'layer' of undefined
What is the new behavior?
In that case, the app trow now a Error with message:
Service error getCapabilities: Access is denied
No message to user only in console
- [x ] No

Fix(capabilities.service): Access denied err handling

---

packages/context/src/lib/share-map/shared/share-map.service.ts

[710](https://github.com/infra-geo-ouverte/igo2-lib/issues/710)
problem with shareMap when a layer have badName in context
check if contextLayer id is undefined, don't push it
-  [x] No

Fix(share-map.service) shareMap problem with bad layer name (#710)

---

packages/geo/src/lib/catalog/catalog-browser/catalog-browser-layer.component.html
packages/geo/src/lib/catalog/catalog-browser/catalog-browser-layer.component.ts
packages/geo/src/lib/catalog/shared/catalog.service.ts
packages/geo/src/lib/layer/layer-legend/layer-legend.component.ts

The tooltip on layer is only the title
Allow to show the abstract as tooltip for layers in catalog.
Config :
With this config, also the layer will show the abstract on tooltip (into the layer list)

Abstract on layer in catalog

---

packages/geo/src/lib/datasource/shared/datasource.service.ts
packages/geo/src/lib/datasource/shared/datasources/wfs-datasource.ts
packages/geo/src/lib/datasource/shared/datasources/wfs.service.ts
packages/geo/src/lib/datasource/shared/datasources/wms-wfs.utils.ts

1-When retrieving values from fields, sometime, the call take very long time to get the results...
2- Openlayers always call only once the service to retrieve the data.
1- try to make a gml call without the geometry to accelerate the retrieval of the values from a field.
2- Dice the wfs getfeature call for wfs 2.0.0 & outputformat different from gml, where the count is superior to defaultMaxFeatures (5000). Then call the service by 1000 chunks. 
@mbarbeau 
https://github.com/infra-geo-ouverte/igo2-lib/commit/03a257f73f2e9048615083bd8553acdfda65f423
and 
https://github.com/infra-geo-ouverte/igo2-lib/pull/732/commits/2c18db81569f6ec7 …

WFS call optimization

---

packages/integration/src/lib/map/map-details-tool/map-details-tool.component.html
packages/integration/src/lib/map/map-tool/map-tool.component.html
packages/integration/src/lib/map/map-tools/map-tools.component.html

The metadata button is placed between less frequent button (ogcfilter and timefilter)
Position the metadata button to the nearest position of the common button (opacity, move up and down, eye...)

Button integration

---

demo/src/environments/environment.ts
packages/common/src/lib/interactive-tour/interactive-tour.loader.ts
packages/common/src/lib/interactive-tour/interactive-tour.service.ts

add new config  : 
"activateInteractiveTour": true
- no error went is false and  no interactiveTour config file 
- Better handling error went param is true and no interactiveTour config file are detect

feat(interactive-tour)add config + handling error no configtourFile

---

packages/integration/ng-package.json
packages/integration/ng-package.prod.json
packages/integration/src/lib/search/search-results-tool/search-results-tool.component.ts

For search results -- Small line or polygon visible at a small scale were pratically invisible despite the highlight style
Adding a pin point, based on the ratio feature extent/ view extent for line and poly. 
When zooming in
, if the previous ratio become under a threshold, the pin is removed.
It is possible the configurate the status of this feature. To disable the feature, under the app config.json, you can turn of this feature this way: 
```
"hasFeatureEmphasisOnSelection": false,
```
```
[ ] Yes
[x] No
```
If this PR contains a breaking change, please describe …

Search-result --  add a emphasis feature for line and poly too deep in view

---

packages/geo/src/lib/datasource/shared/datasources/wfs-datasource.ts
packages/geo/src/lib/layer/shared/layers/vector-layer.ts
packages/geo/src/lib/layer/shared/layers/vectortile-layer.ts
packages/geo/src/lib/layer/utils/vector-watcher.ts

…elated to the spinner (activity-service)
url based vector sources do not trigger the activity service.
Monitor the load/end of url based vector sources. Now trigger the loading spinner
@drekss - Reviewer or comment after the merge...

Monitor the load/end of url based vector sources. Related to the spinner

---

demo/src/app/common/entity-table/entity-table.component.ts
packages/common/src/lib/entity/entity-table/entity-table.component.html
packages/common/src/lib/entity/entity-table/entity-table.component.ts
packages/common/src/lib/entity/entity-table/entity-table.module.ts
packages/common/src/locale/en.common.json
packages/common/src/locale/fr.common.json
packages/geo/src/lib/import-export/import-export/import-export.component.ts

URL were rendered as plain text.
1- Allow to format an url like string (begin with http:// or https://)  
2- If it is an url and containt .png .jpg or .gif, then the image is shown, height set to 50, click on the image open the link.

Entity table renderer for url and image

---

packages/context/src/lib/context-manager/shared/layer-context.directive.ts
packages/geo/src/lib/datasource/shared/datasource.service.ts
packages/geo/src/lib/datasource/shared/options/options-api.interface.ts
packages/geo/src/lib/datasource/shared/options/options-api.service.ts
packages/geo/src/lib/datasource/shared/options/options.service.ts
packages/geo/src/lib/layer/shared/layer.service.ts

Provide the context uri from where the layer is added. Allow the optionsApi to retrieve the correct layerOptions depending of the context. 
Controlled by a config: 
```
provideContextUri?: boolean;
```

feat(options-api) provide a context name for layer options retrieval

---

packages/geo/src/lib/catalog/shared/catalog.abstract.ts
packages/geo/src/lib/catalog/shared/catalog.service.ts

- Allow to add alias to WMS, WMTS or ArcGIS REST catalog's layer (for composite catalog for example)
- regFilters must be used to match the indexes. 
For example, if catalog's config is : 
{
"id": "2",
"url": "https://geoappext.nrcan.gc.ca/arcgis/services/GSCA/basin_f/MapServer/WMSServer?",
"groupImpose": {"id": "geo", "title": "Géologie"},
"regFilters": ["^3$", "^6$"],
"alias": ["Analyse - 1", "Analyse - 2"]
}
Then it would mean that the layer whose name is 3 going to be rename as "Analyse - 1" and the layer whose name is 6 is going to be rename as "Analyse - 2".
Note that if alias is not mandatory, if none are provided, the service's title is going to be used (like it was before).
Issue https://github.com/infra-geo-ouverte/igo2/issues/515 in igo2 (assemblage)
JIRA : …

Catalog force name

---

packages/context/src/lib/context-manager/shared/layer-context.directive.ts

Share link problem with a layer id numeric set in context
ShareLink is ok 

Fix(layerContextDirective.computeLayerVisibilityFromUrl) share link bug with layer id numeric

---

packages/geo/src/lib/datasource/shared/capabilities.service.ts
packages/geo/src/lib/datasource/shared/datasource.service.ts
packages/geo/src/lib/datasource/shared/options/options-api.service.ts
packages/geo/src/lib/datasource/shared/options/options.service.ts
packages/geo/src/lib/search/shared/sources/ilayer.ts

Only wms layer can retrieve the options from the options api
Provide to the arcgis datasource, a method to retrieve their options from options api.

feat(options-api) extend the capacities to arcgis services

---

packages/geo/src/lib/download/shared/download.interface.ts
packages/geo/src/lib/download/shared/download.service.ts
packages/geo/src/lib/import-export/import-export/import-export.component.ts
packages/geo/src/locale/en.geo.json
packages/geo/src/locale/fr.geo.json

The only way to control the export formats is at the app level.
Control the export formats at the layer leve. 

Export formats

---

packages/geo/src/lib/datasource/shared/datasources/wfs-datasource.ts
packages/geo/src/lib/datasource/shared/datasources/wms-datasource.ts
packages/geo/src/lib/filter/ogc-filter-selection/ogc-filter-selection.component.html
packages/geo/src/lib/filter/ogc-filter-selection/ogc-filter-selection.component.ts
packages/geo/src/lib/filter/shared/ogc-filter.ts

- Auto detection of selector type (@pelord )
- Fix apply filters at map initialization when selector is enabled
- Fix checkbox enabled condition :
- There was a problem with checkbox enabled condition because they were all linked to the same formControl
It'll be needed to discuss what to do with radioButtons enabled initial attribute. There can only be one radio buttons selected at the same time, so it can cause problem when multiple buttons are set to true.

fix(ogcFilters): various fix for release 1.7

---

packages/geo/src/lib/datasource/shared/datasources/imagearcgisrest-datasource.ts
packages/geo/src/lib/layer/layer-legend/layer-legend.component.ts

- Fix imagearcgisrest datasource params options if layer is not defined
- GetLegendGraphic catchError only if error is error type (browser console error could appeared if not)

fix(imagearcgisrest/layer-legend): release 1.7 various fix

---

demo/src/app/geo/search/search.module.ts
demo/src/environments/environment.ts
packages/geo/src/lib/search/shared/sources/storedqueries.ts

- fix bug [852](https://github.com/infra-geo-ouverte/igo2-lib/issues/852)
- param limit is now functional with a storedQuery search
Exemple of config is working now :
"storedqueries": {
"available": true,
"title": "Feuillets SNRC",
"searchUrl": "/ws/mffpecofor.fcgi",
"storedquery_id": "sq250et20kFeuillet",
"fields": [
{"name": "no_feuillet","defaultValue": "0"}
],
"resultTitle": "feuillet",
"params": {
"limit": 10
}
}
},
- [x ] No

feat-fix(StoredQueriesSearchSource) fix excep when no title. Param limit is now functional

---

packages/geo/src/lib/map/shared/map.utils.ts

When 2 numeric terms are search and these are not coordinates, the app detect a coordinate type. The app convert the provided coords into longitude/latitude coords.  The app crash
https://infra-geo-ouverte.github.io/igo2/?search=000012392110001%200001320192110001
If the longitude latitude coords are out of bounds, (180 to -180 and -90 to 90), the reversesearch is not triggered.

fix(map utils): conversion to latitude longitude out of bounds

---

packages/geo/src/lib/query/shared/query.service.ts

wms query in geojson format do not use source fields as alias
wms query in geojson format now use source fields as alias

fix(query): wms query in geojson format now use source fields as alias

---

demo/src/app/geo/layer/layer.component.ts
packages/geo/src/lib/datasource/shared/capabilities.service.ts
packages/geo/src/lib/layer/layer-list/layer-list.component.html
packages/geo/src/lib/layer/layer-list/layer-list.component.ts
packages/geo/src/lib/layer/shared/layers/layer.interface.ts
packages/geo/src/lib/map/shared/controllers/view.ts
packages/geo/src/lib/map/shared/map.interface.ts
packages/geo/src/lib/map/shared/map.ts
packages/geo/src/locale/en.geo.json
packages/geo/src/locale/fr.geo.json

N/A (https://github.com/infra-geo-ouverte/igo2/issues/518)
Un bouton dans les options de couche(s) permet de cadrer la vue sur la/les couches sélectionnées.

feat (layer-list): ajout d'un bouton permettant de cadrer sur une ou plusieurs couches contenues dans la carte

---

packages/geo/src/lib/datasource/shared/capabilities.service.ts
packages/integration/src/lib/about/about-tool/about-tool.component.html
packages/integration/src/lib/about/about-tool/about-tool.component.ts

- Disabled guide download button when call is not finished and window not opened yet
- To avoid multiple clicking from user

fix(about-tool): disabled guide button when downloading

---

packages/geo/src/lib/datasource/shared/capabilities.service.ts
packages/geo/src/lib/layer/shared/layer.service.ts
packages/geo/src/lib/layer/shared/layers/image-layer.ts

Allow IGO to catch mapserver service exception report (error) that has a status code 200.
Mapserver error on getMap calls returns status code 200 very often. It makes impossible for IGO to catch those errors. 
Solution here is to convert the arrayBuffer response to text and verify if it contains ServiceExceptionReport tag.

Mapserver errors

---

packages/context/src/lib/context-manager/shared/context.service.ts
packages/core/src/lib/message/shared/message.interface.ts
packages/core/src/lib/message/shared/message.service.ts

**What is the current behavior?** 
[demande 507](https://github.com/infra-geo-ouverte/igo2/issues/507)
messages is remove when context change.
* error message is keep
no
Branche create from branche messageHandling

feat(context-service)on context change remove mesage from other context

---

packages/geo/src/lib/datasource/shared/datasources/wfs-datasource.ts
packages/geo/src/lib/datasource/shared/datasources/wms-datasource.ts
packages/geo/src/lib/filter/ogc-filter-button/ogc-filter-button.component.html
packages/geo/src/lib/filter/ogc-filter-button/ogc-filter-button.component.ts
packages/geo/src/lib/filter/ogc-filter-selection/ogc-filter-selection.component.html
packages/geo/src/lib/filter/ogc-filter-selection/ogc-filter-selection.component.scss
packages/geo/src/lib/filter/ogc-filter-selection/ogc-filter-selection.component.ts
packages/geo/src/lib/filter/ogc-filterable-item/ogc-filterable-item.component.ts
packages/geo/src/lib/filter/shared/filterable-datasource.pipe.ts
packages/geo/src/lib/filter/shared/ogc-filter.interface.ts
packages/geo/src/lib/filter/shared/ogc-filter.ts
packages/geo/src/lib/query/shared/query.service.ts
packages/geo/src/locale/en.geo.json
packages/geo/src/locale/fr.geo.json
packages/integration/src/lib/map/map-tools/map-tools.component.ts

User could use checkboxes, push buttons and radio buttons for OGC filters. There were multiple bugs with the radio buttons.
User can now also use a dropdown list (MatSelect) to filter data. It is possible to select one or many options in the list by using the "multiple" keyword in the config. Various bugs with the radio buttons were also fixed.
This branch was merged with branch wmsLayerSync.

feat(ogcFilter): add MatSelect to selectors for OGC filters and bug fixes

---

packages/geo/src/lib/import-export/shared/import.service.ts
packages/geo/src/lib/layer/layer-list/layer-list.component.html
packages/geo/src/lib/layer/layer-list/layer-list.component.scss
packages/integration/src/lib/map/map-details-tool/map-details-tool.component.html
packages/integration/src/lib/map/map-details-tool/map-details-tool.component.scss
packages/integration/src/lib/map/map-tool/map-tool.component.scss
packages/integration/src/lib/map/map-tools/map-tools.component.scss

[509](https://github.com/infra-geo-ouverte/igo2/issues/509)
-----------------------
* fix error handling with OGRE import
The layer list filter is fix on top of the list
- [x ] No

Feat(layer-list): Fix layer filter on top of list

---

packages/geo/src/lib/datasource/shared/capabilities.service.ts

- Fix non geographical wms layer extent
- It was causing the extent to be out of bounds for 3857 (results in NaN), so the layer would not be displayed.

fix(capabilities): fix bad geographical extent

---

packages/geo/src/lib/layer/layer-list/layer-list.component.html
packages/geo/src/lib/layer/layer-list/layer-list.component.scss

When there are many layers in the list, the scrollable zone is not the right size when tools are not shown.
The scrollable zone is now the right size.

fix(layer-list): scrollable zone bug fix

---

packages/common/src/lib/context-menu/context-menu.directive.ts

fix https://github.com/infra-geo-ouverte/igo2/issues/645 
Fix it. 
- [x ] No

fix(context-menu): ios context menu was not available.

---

demo/src/app/geo/hover/hover.component.ts
packages/context/src/lib/context-manager/shared/context.service.ts
packages/geo/src/lib/layer/shared/layers/vector-layer.ts
packages/geo/src/lib/map/shared/map.ts
packages/geo/src/lib/measure/measurer/measurer.component.ts

WFS layers are saved in context. It causes problems when opening a context that contains wfs layers.
WFS layers are not saved anymore. 

fix(context/vector): fix wfs layer in context / vector layer source

---

packages/geo/src/lib/search/shared/sources/storedqueries.ts

Due to the migration to eslint, an error was inserted, then the params property was not initilized properly.
Fix it. 

fix(storedQueries): params property was not initilized properly

---

packages/common/src/lib/context-menu/context-menu.directive.ts

Reverts infra-geo-ouverte/igo2-lib#899
Fix map's button not clickable but contextMenu is not available on iOS. 
Related to https://github.com/infra-geo-ouverte/igo2/issues/686

Revert "fix(context-menu): ios context menu was not available."

---

packages/geo/src/lib/layer/layer-legend/layer-legend.component.html
packages/geo/src/lib/layer/layer-legend/layer-legend.component.ts

**What is the current behavior?** 
[685](https://github.com/infra-geo-ouverte/igo2/issues/685)
with many layer, many legend is show. 
Same as 1.8 version
- [x ] No

Fix (layer-legend-component) problem with layer contain manyLayer

---

demo/src/app/geo/query/query.component.ts
packages/geo/src/lib/query/shared/query.directive.ts
packages/geo/src/lib/query/shared/query.interfaces.ts
packages/geo/src/lib/query/shared/query.service.ts
packages/geo/src/lib/query/shared/query.utils.ts

the absence of the new behavior
the new queryable layer's param allow a custom getFeatureInfo's url.  
find and replace in the url:  
{x} : coordinate X of the click
{y} : coordinate Y of the click
{xmin} : extent of the map on click
{ymin} : extent of the map on click
{xmax} : extent of the map on click
{ymax} : extent of the map on click
{srid}: srid of the map and extent, x and y
{resolution} : resolution fo the map on click

Custom url get info

---

packages/geo/src/lib/search/shared/search-pointer-summary.directive.ts
packages/geo/src/lib/search/shared/search.interfaces.ts
packages/geo/src/lib/search/shared/sources/icherche.ts

1-Pointer summary do no respect the planned order (into the search results). Then, the summary order is always based on response time.
2- Pointer summary do not show the type of the result...
vs 
Respect order
Present type.

Pointer enhancement

---

packages/core/src/lib/message/shared/message.interface.ts
packages/geo/src/lib/layer/shared/layers/layer.ts

feat(messages): message at the layer level, config to allow the message to be shown each time the layer is set to be visible.

---

packages/geo/src/lib/query/shared/query.utils.ts

When queryLayerFeatures is "false", return true. 
#947 was bad. fixed non-existent queryLayerFeatures but was wrong when queryLayerFeatures was "false"
return false when false ! 

fix (query.utils) fix when queryLayersFeatures is false

---

packages/core/src/lib/message/message.module.ts
packages/geo/src/lib/search/shared/sources/storedqueries.ts
packages/geo/src/locale/en.geo.json

message duplicate [x] [710](https://github.com/infra-geo-ouverte/igo2/issues/710)
storedQuery feuilletSNRC not working fine
no show count message duplicate 
storedQuery feuillet ok
- [x ] No
config to check storedQuery feuillet:
"storedqueries": {
"available": true,
"title": "Feuillets SNRC",
"searchUrl": "/ws/mffpecofor.fcgi",
"storedquery_id": "sq250et20kFeuillet",
"fields": 
{"name": "no_feuillet","defaultValue": "0"}
,
"resultTitle": "feuillet",
"params": {
"limit": 10
}
}

fix(messageModule-storedQuery.ts)- fix duplicate mesage and storedQuery

---

packages/geo/src/lib/query/shared/query.service.ts

no query title for htmlgml2 formats
query title for htmlgml2 formats

feat(query): provide a way to show the querytitle in htmlgml2 queryformat

---

packages/geo/src/lib/geometry/shared/controls/draw.ts
packages/geo/src/lib/measure/measurer/measurer.component.ts

Pressing escape to abort the measure case label (measure) to stay on map. 
Remove label on abort drawing.

Measure fix

---

packages/auth/src/lib/auth-form/auth-intern.component.html

…n to fix Angular issue 30616
When a user uses autofill in Chromium browser to login, the login form does not detect the content of the fields and proceed as they were empty. By security design, it requires an action in the form by the user to allow the autofill detection (Angular issue 30616). Therefore, the validation of the form does not allow the submit button to validate. Additionnaly, users get confused when they see the submit button grayed out and think they are not allowed to login. 
The validation of the form is disabled for the submit button. If the user leaves an empty field or wrong login informations, an error …

Fix(auth-form): Fixed disabled login submit when using autofill in Chromium browsers

---

packages/geo/src/lib/datasource/shared/datasources/wms-datasource.ts
packages/geo/src/lib/filter/ogc-filter-button/ogc-filter-button.component.ts
packages/geo/src/lib/filter/ogc-filter-selection/ogc-filter-selection.component.scss
packages/geo/src/lib/filter/ogc-filter-selection/ogc-filter-selection.component.ts
packages/geo/src/lib/filter/ogc-filter-time/ogc-filter-time.component.html
packages/geo/src/lib/filter/ogc-filter-time/ogc-filter-time.component.scss
packages/geo/src/lib/filter/ogc-filter-time/ogc-filter-time.component.ts
packages/geo/src/lib/filter/shared/ogc-filter.ts
packages/geo/src/locale/en.geo.json
packages/geo/src/locale/fr.geo.json

[694] (https://github.com/infra-geo-ouverte/igo2/issues/694) (Done only for OGC-filter)
[695](https://github.com/infra-geo-ouverte/igo2/issues/695)
[467](https://github.com/infra-geo-ouverte/igo2/issues/467)
[328](https://github.com/infra-geo-ouverte/igo2/issues/328)
Only for OGCFilterTime
- add reset and disabled button
- fix badge in layer option when ogcTime is actif
- fix problem in calendarYearMode when no time is give in date creation
- fix value 'today' trow angular warning Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. 
- [x ] No
@matrottier maybe you …

feat-fix(ogc-filter-time*)- add reset and disabled button- fix calendarYear date problem

---

packages/core/src/lib/network/network.service.ts
packages/geo/src/lib/map/shared/mapOffline.directive.ts

Multiple message (toast) are show on network changes,
Prevent it. Only keep the current network state in toast. 

feat(network): prevent showing 2 different network state simultaneously

---

packages/geo/src/lib/datasource/shared/datasources/wfs-datasource.ts
packages/geo/src/lib/layer/shared/layers/vector-layer.ts

The entities displayed in the table do not match the filter. A previous query is used instead of the last query in the table view. 
This results from a return from an observable having taken longer to process and which returns after the last call.
Ex: a 2016 value is entered manually. 20 is already in place and the user successively enters the numbers 1 and 6. 201 and launched as a filter then is followed 2016. 2016 is processed faster than 201. 201 is applied to the tabular view.
Behaviour: The entities displayed in the table correspond to the last filter requested.
In the code: Avoids retrieving an older call that took longer to …

(fix): bad result filter in table view #986

---

packages/geo/src/lib/search/search-results/search-results-add-button.component.html

Feature details popup show also on search-add-button click. It causes recurrent overflow and display problems.
Feature details popup doesn't show on search-add-button click, only on the search-results selection.

refactor(search-results): stop propagation from search-add-button

---

packages/geo/src/lib/datasource/shared/datasources/wms-datasource.ts

When ogcFilters.filters is not defined, but sourceFields is (regular advanced ogcFilters), datasource does not load
When ogcFilters.filters is not defined, but sourceFields is (regular advanced ogcFilters), datasource does load with specified advanced filters

fix(ogcFilters): fix advancedOgcFilters when filters not defined

---

packages/geo/src/lib/layer/shared/layers/vector-layer.ts

Poor handling of latecomers to and call state. 
The last call calls a success with the wanted entities. The late call is directed to an empty success to be released.

fix(featureloader) bad manage success

---

packages/geo/src/lib/layer/utils/layerSync-watcher.ts

…r are the same
Linked wfs layer were refreshed despite the provided ogcfilters were identical to the previous. 
Prevent refresh for the same ogcfilters.

feat(layerSync): prevent refresh of linked layer if applied OGC filters are the same

---

packages/context/src/lib/context-manager/context-list/context-list.component.scss
packages/geo/src/lib/layer/layer-list/layer-list.component.scss

overflow display problem with layer-list-tool and igo-context-button with Google Chrome 100
overflow display correctly

fix(context/layer-list-tool): fix CSS overflow with Chrome 100

---

packages/common/src/lib/entity/entity-table/entity-table.component.ts

When an entity has no properties, error was raised at the formControl instanciation for edition mode
When an entity has no properties, the formControl is created with the entity directly

fix(entity-table): fix formControl (edition) with no properties entity

---

packages/geo/src/lib/workspace/shared/wms-workspace.service.ts

WMS layers with wfs params attached, but with workspace.enabled = false, layer was queried twice, on the wms getfeatureinfo and on the vector query.
Prevent query wfs features on these conditions.

fix(wms-workspace): duplicated query on non exposed workspace

---

packages/common/src/lib/entity/entity-table/entity-table.component.html

Entity-table buttons doesn't display when editMode is not defined
Entity-table buttons works when editMode is undefined

fix(entity-table): fix entity-table buttons

---

packages/geo/src/lib/workspace/shared/feature-workspace.service.ts
packages/geo/src/lib/workspace/shared/wfs-workspace.service.ts
packages/geo/src/lib/workspace/shared/wms-workspace.service.ts

https://github.com/infra-geo-ouverte/igo2/issues/765
The color selection is now the same as config queryOverlayStyle.selection
"fillColor" 
"fillOpacity"
"strokeColor"
"strokeWidth"      
- [x ] No
config to test:
```
"queryOverlayStyle": {
"selection": {
"markerColor": [0,137,123], 
"markerOpacity": 1.0, 
"markerOutlineColor": [255,255,255],        
"fillColor": "#c9f2d0", 
"fillOpacity": 0.0,     
"strokeColor": "#2effff",       
"strokeWidth": 3                
},
```
layerContext to test:
{     
"title": "WMS-WFS avec table attribut sans query",
"visible": true,
"id": 1,
"workspace": { …

feat(workspace*) Wks color selection is now the same as queryOverlayStyle.selection config

---

packages/geo/src/lib/filter/shared/ogc-filter.ts

propertyislike operator crash with undefined values
fix

fix(ogcfilter): propertyislike operator crash with undefined values

---

packages/geo/src/lib/filter/shared/ogc-filter.ts

…r and upper boundary
between operator crash with undefined values
fix it.  Used default bound from 1e40 *-1 to 1e40. 

fix(ogcfilter): between operator crash with undefined values for lower and upper boundary

---

packages/common/src/lib/entity/entity-table/entity-table.component.ts
packages/common/src/lib/entity/shared/entity.interfaces.ts
packages/geo/src/lib/datasource/shared/datasources/datasource.interface.ts
packages/geo/src/lib/workspace/shared/edition-workspace.service.ts
packages/geo/src/lib/workspace/shared/edition-workspace.ts

Nothing discriminate which source field you really want to send on add/modify action
Predefined url are not considered for relation http call
add, remove and modify buttons are always available
Edit mode shows all other features (in edit mode or not) and causes some problems with multiple domain value
"send" config allow to send or not send sourceFields on add/modify action
"url" can now be part of relation options config
add, remove and modify buttons can now be set to disabled directly by layer edition options
Edit mode only shows the feature in edit mode

feat(edition): allow send config option / url call for dom / add, modify, delete disabled button config

---

packages/geo/src/lib/feature/feature-details/feature-details.component.ts

Page not loading on iphone IOS due to incompatibility with lookbehind expression
https://caniuse.com/js-regexp-lookbehind 
lookbehind isn't use anymore

fix(regex): fix iphone regex (lookbehind expression)

---

packages/geo/src/lib/feature/feature-details/feature-details.component.html
packages/geo/src/lib/feature/feature-details/feature-details.component.scss
packages/geo/src/lib/feature/feature-details/feature-details.component.ts
packages/geo/src/locale/en.geo.json
packages/geo/src/locale/fr.geo.json

On map query, when content is url, only a link is available to open the link
Add a button to copy the link

feat(feature-details): copy content button alongside the url

---

packages/geo/src/lib/layer/layer-list/layer-list.component.html
packages/geo/src/lib/layer/layer-list/layer-list.component.ts

Layer lis was not scrolling during layer(s) displacement.
If you raise layer(s), the list will scroll to follow the first item.
If you lower layer(s), the list will scroll to follow the last item. 

fix(layer-list): follow checked or focused layer on layer displacement

---

packages/auth/src/lib/shared/auth.interceptor.ts

withCredentials & token  were in conflicts. If you were authenticated by credentials (kerberos), the token was also provided and was deleting the credential value ....
Return request to ve authenticated by kerberos. 

fix(auth Interceptor): withCredentials & token conflict

---

packages/geo/src/lib/workspace/shared/edition-workspace.service.ts
packages/geo/src/lib/workspace/shared/edition-workspace.ts

Edition url is only defined by config
You can now define url absolute path in the layer edition options

feat(edition): allow absolute url if config is not defined

---

packages/context/src/lib/context-manager/context-list/context-list.component.ts

While ours is empty, contexts$ is never re assigned, results in empty contexts in the app
Fix

fix(contexts): fix empty context list when ours is empty

---

packages/geo/src/lib/query/shared/query.service.ts

When layer feature count is set to 1, message always show
When feature count is less than 1, never show the message

fix(query): don't show message when feature count is 1 or less

---

packages/geo/src/lib/import-export/shared/import.interface.ts
packages/geo/src/lib/import-export/shared/import.service.ts

There is no method to control allowed formats during imports.
Reuse an existing interface (export config--> formats) to control allowed formats. 
https://github.com/infra-geo-ouverte/igo2-lib/blob/master/packages/geo/src/lib/import-export/shared/import.interface.ts#L5

feat(import): controls for import formats

---

packages/context/src/lib/context-manager/shared/map-context.directive.ts
packages/geo/src/lib/map/shared/hover-feature.directive.ts

If a view projection is define, (not the default one), the igoHoverDirective cause app to crash....
On context change, the view was not reloaded if the projection was different.
Provide proj to vectortile source in hover directive to fix it. 
On context change, change the view depite the keepcurrentview property. 

Hover projection

---

angular.json
packages/geo/src/lib/print/shared/geopdf.ts
packages/geo/src/lib/print/shared/index.ts
packages/geo/src/lib/print/shared/print.interface.ts
packages/geo/src/lib/print/shared/print.service.ts

**What is the current behavior?** 
https://github.com/infra-geo-ouverte/igo2/issues/747
when you print a pdf is now georeference so you can put it in SIG or app like Avenza
you can find information like bbox, bound, date pdf Create and producer IGO2 on open pdf doc with blocNote.
- [x ] No

feat(print.service) print make Pdf georeferenced

---

packages/geo/src/lib/search/search-results/search-results.component.ts

Search - Remove the number of results #829

---

packages/geo/src/lib/search/search-bar/search-bar.component.html
packages/geo/src/lib/search/search-bar/search-bar.component.ts

To add a search button to the search bar, the user must add an input to the component.
The user must add a config to the config file
See https://github.com/infra-geo-ouverte/igo2/pull/898

refactor(search-bar): switched from input to config for search button

---

packages/geo/src/lib/datasource/shared/datasources/datasource.interface.ts
packages/geo/src/lib/datasource/shared/datasources/feature-datasource.interface.ts
packages/geo/src/lib/workspace/shared/edition-workspace.service.ts

Use lat/lon to save geometry (Point only) in edition
Use wkt to save geometry in edition
- [] No
Remove the trigger on database table (the one who convert lat/lon in geometry). Add the geometry database projection "geomDatabaseProj" parameter in layer definition at sourceOptions->edition

Change lat/lon to wkt for edition

---

demo/src/environments/environment.ts
packages/context/src/lib/context-manager/shared/layer-context.directive.ts
packages/geo/src/lib/import-export/import-export/import-export.component.ts
packages/geo/src/lib/import-export/shared/drop-geo-file.directive.ts
packages/geo/src/lib/import-export/shared/import.interface.ts

…ort config
importWithStyle  is a standalone config. 
Move it into importExport configs.
Move it into importExport configs.
A warning is shown in the console.

BREAKING CHANGE(import): importWithStyle config move inside importExport config

---

packages/geo/src/lib/feature/shared/strategies/search.ts
packages/geo/src/lib/search/search-results/save-feature-dialog.component.html
packages/geo/src/lib/search/search-results/save-feature-dialog.component.ts
packages/geo/src/lib/search/search-results/search-results-add-button.component.ts
packages/integration/src/lib/search/search-results-tool/search-results-tool.component.html
packages/integration/src/lib/search/search-results-tool/search-results-tool.component.ts

This update relate to the issue [915](https://github.com/infra-geo-ouverte/igo2/issues/915) in igo2.
Make the option save a search result in layer configurable

feat(integration): Make the save search result option configurable

---

packages/geo/src/lib/feature/feature-details/feature-details.component.ts
packages/geo/src/lib/layer/shared/layers/layer.ts
packages/geo/src/lib/map/offline-button/offline-button.component.html
packages/geo/src/lib/map/offline-button/offline-button.component.scss
packages/geo/src/lib/map/offline-button/offline-button.component.ts
packages/geo/src/lib/map/shared/map.ts
packages/geo/src/lib/map/shared/mapOffline.directive.ts

setting layer max resolution to 0 was impossible. Infinity was set instead.
Fix it + major refactor.
igo-offline-button is not controled anymore by a config. 
When using igo-offline-button, use a *ngIf clause instead based on offlineButton config OR showOfflineButton from portal.component.ts (within igo2 project)

BREAKING CHANGE(OFFLINE): major refactor and some properties moved

---

packages/integration/src/lib/map/map-proximity-tool/map-proximity-tool.component.html
packages/integration/src/lib/map/map-proximity-tool/map-proximity-tool.component.scss
packages/integration/src/lib/map/map-proximity.state.ts

Map proximity radius was not kept into storage. Then, after reloading app, the user's radius is not applied anymore.
Keep the user's radius for further usage.

feat(map-proximity): keep radius distance into storage

---

packages/geo/src/lib/print/print/print.component.ts
packages/geo/src/lib/print/shared/print.service.ts

This update relate to the issue [913](https://github.com/infra-geo-ouverte/igo2/issues/913) in igo2.
fix the bug export map and legend  in the same zip file and code improvement

fix(geo): export map and legend in the same file zip

---

packages/geo/src/lib/search/search-results/search-results-add-button.component.html
packages/geo/src/lib/search/search-results/search-results-add-button.component.ts
packages/integration/src/lib/search/search-results-tool/search-results-tool.component.html

this issue related to save search result in layer [915](https://github.com/infra-geo-ouverte/igo2/issues/915)
This issue relates to disabling the Add Layer button if we disable save Search Result In Layer

fix(geo, integration): solve config bug save search result in layer

---

packages/geo/src/lib/datasource/shared/datasource.service.ts

On offline app, if a service based layer is created, the app raise an error on getcapabilities or on option service. 
Prevent calling service when offline. 

fix(datasource): prevent service request when offline

---

packages/geo/src/lib/search/search-results/search-results-add-button.component.ts

This update relate to the [#925](https://github.com/infra-geo-ouverte/igo2/issues/925)
Change the default color for  symbology of features added on the map

feat(geo): add style and change color in feature store

---

packages/geo/src/lib/search/search-results/search-results-add-button.component.html
packages/geo/src/lib/search/search-results/search-results-add-button.component.scss
packages/geo/src/lib/search/search-results/search-results-add-button.component.ts
packages/geo/src/lib/search/search-results/search-results-item.component.html
packages/geo/src/lib/search/search-results/search-results-item.component.ts

This update relate to [#924](https://github.com/infra-geo-ouverte/igo2/issues/924)
Show add results icon only when hovering over the result

feat(geo): Show add results icon only when hovering over the result

---

packages/geo/src/lib/datasource/shared/datasources/feature-datasource.interface.ts
packages/geo/src/lib/layer/shared/layers/vector-layer.ts

Non visible layers or layers out off resolution range are not loaded until the layer become visible or in the resolution range. 
Add a bypass to load vector data before the visibility OR the range state change.
This allow to enable search on non visible layers. 

feat(feature-datasource): add a preload options on vector source

---

packages/geo/src/lib/draw/draw/draw.component.ts

Drawing circle cause crash
Fix it.

fix(draw): drawing circle crash whole drawing component.

---

packages/common/src/lib/entity/entity-table/entity-table.component.ts

Problème avec les string contenant des numériques et débutant avec un "0"
Retrait de la conversion numérique du string débutant avec un zéro

Corriger le parseInt qui ajuste normalement les attributs en integer

---

packages/context/src/lib/context-manager/shared/context.service.ts
packages/geo/src/lib/import-export/shared/export.service.ts
packages/geo/src/lib/layer/shared/layers/vectortile-layer.interface.ts
packages/geo/src/lib/style/style-service/draw-style.service.ts
packages/geo/src/lib/style/style-service/style.service.ts

this behavior related to https://github.com/infra-geo-ouverte/igo2-lib/issues/1337
1- Store the feature style as an igoStyleObject within _style property. 
2- Store the label inside the _mapTitle property.
Overall, this PR propose to use existing mecanism to handle styles during import (context or data). This is a "temporary" fix. I think we need to create a new layer type or extend the vector type, to handle internal layer types (draw, directions, measures) to be handled easily, on export/import. 
Furthermore, the style handling will be changed shortly by using the geostyler library. 
**Does this PR introduce a breaking change?** …

Fix import context with style (drawing layer)

---

packages/context/src/lib/context-import-export/shared/context-import.utils.ts
packages/context/src/lib/context-manager/shared/context.interface.ts
packages/context/src/lib/context-manager/shared/context.service.ts
packages/context/src/lib/context-manager/shared/layer-context.directive.ts

this behavior related to [#979](https://github.com/infra-geo-ouverte/igo2/issues/979) in igo2
Save layer opacity if export contexts
Solve some logical bugs for import and export contexts

feat(context): save layer opacity if export context

---

packages/geo/src/lib/utils/googleLinks.ts
packages/geo/src/lib/utils/osmLinks.ts

Current google map link were not interpreted on mobile. Google maps was opening but with no query 
Fix around the new method from google map to open their apps. 
https://developers.google.com/maps/documentation/urls/get-started?hl=fr

fix(geo): google map links were not interpreted on mobile

---

.eslintrc.json
packages/context/src/lib/context-import-export/context-import-export/context-import-export.component.ts
packages/context/src/lib/context-manager/shared/context.service.ts
packages/geo/src/lib/map/shared/map.ts

this behavior related to [#981](https://github.com/infra-geo-ouverte/igo2/issues/981) in igo2
Set map zoom level after importing context

feat(context): set map zoom level after importing context

---

packages/geo/src/lib/directions/directions.component.html
packages/geo/src/lib/directions/directions.component.scss
packages/geo/src/lib/directions/directions.component.ts
packages/geo/src/lib/directions/directions.module.ts
packages/geo/src/locale/en.geo.json
packages/geo/src/locale/fr.geo.json

There is no method to disable map's interaction from the user.
Add a toogle to allow the user to enable/disable the map interaction.
This is useful if the user wants to query the map, not add a intermediate point.

feat(direction): add a toogle to control user interaction with map

---

packages/core/src/theming/prebuilt-themes/qcca/components/_index.scss
packages/core/src/theming/prebuilt-themes/qcca/components/scrollbar.scss

The scrollbar has a personnalized color and is thinner.

feat(qcca-theme): ajout de style pour la barre de défilement qc-ca

---

packages/core/src/lib/config/config-deprecated.ts
packages/core/src/lib/config/config.interface.ts
packages/core/src/lib/config/config.service.ts
packages/geo/src/lib/map/menu-button/menu-button.component.ts

The is no method to warn user ou super user of deprecated configs.
Add a way to infor user, inside the console, as a warn or an error, based on a deprecation date.
If there is an alternate key, the key will be suggested. 

feat(core): add a new method to handle deprecated configs

---

packages/core/src/lib/message/shared/index.ts
packages/core/src/lib/message/shared/message.service.ts
packages/core/src/lib/request/error.interceptor.ts
packages/geo/src/lib/query/shared/query.service.spec.ts

I tried many solutions but none worked. So I end up with this workaround, we remove the progress bar for all error messages https://github.com/infra-geo-ouverte/igo2/issues/1026

fix(Core): resolve infinite loop between MessageService and the ErrorInterceptor

---

packages/geo/src/lib/datasource/shared/datasources/wfs-datasource.ts
packages/geo/src/lib/layer/shared/layers/vector-layer.ts
packages/geo/src/lib/offline/shared/geo-network.service.ts
packages/geo/src/lib/workspace/shared/edition-workspace.service.ts

Previous wfs call are not cancelled on pan/zoom, and still, they are not loaded into the source.
cancel outgoing wfs xhr on pan/zoom

perf(wfs): cancel outgoing wfs xhr on pan/zoom

---

packages/geo/src/lib/map/home-extent-button/home-extent-button.component.ts

this behavior related to #1391 
fix  bug if homeExtentButton config is empty

fix(geo): fix home Extent Button Options

---

packages/context/src/lib/context-manager/shared/context.service.ts

this behavior related to [#979](https://github.com/infra-geo-ouverte/igo2/issues/979) in igo 2
save layer opacity in db

feat(context): save layer opacity in db

---

demo/src/config/interactiveTour.json
packages/common/src/lib/interactive-tour/interactive-tour.interface.ts
packages/common/src/lib/interactive-tour/interactive-tour.service.ts

https://github.com/infra-geo-ouverte/igo2/issues/1054

fix(common): interactive-tour add the auto placement

---

packages/context/src/lib/context-manager/shared/context.service.ts

save layer opacity in data base

fix(context): save layer opacity in db

---

packages/geo/src/lib/offline/geoDB/configFileToGeoDB.service.ts
packages/geo/src/locale/en.geo.json
packages/geo/src/locale/fr.geo.json

Wrong url or path simply raise a console.log message OR throw an error.
+ 
On error, the "data download"  message stay indefinetly. 
Raise message error + delete the Download start message.

feat(geo): add a error message on fail during data download

---

packages/geo/src/lib/search/search-settings/search-settings.component.html
packages/geo/src/lib/search/search-settings/search-settings.component.scss

style(geo): fix search setting list style regression

---

packages/geo/src/lib/draw/draw/draw.component.html
packages/geo/src/lib/draw/draw/draw.component.scss
packages/geo/src/lib/filter/spatial-filter/spatial-filter-item/spatial-filter-item.component.html
packages/geo/src/lib/filter/spatial-filter/spatial-filter-item/spatial-filter-item.component.scss
packages/geo/src/lib/filter/spatial-filter/spatial-filter-list/spatial-filter-list.component.scss
packages/geo/src/lib/measure/measurer/measurer-item.component.scss

this behavior related to [#1084](https://github.com/infra-geo-ouverte/igo2/issues/1084)

style(geo): solve mobile issue with measure unit

---

packages/geo/src/lib/print/print-form/print-form.component.html
packages/geo/src/lib/print/print-form/print-form.component.ts
packages/geo/src/lib/print/shared/print.type.ts

this behavior related to [#1085](https://github.com/infra-geo-ouverte/igo2/issues/1085) on igo2
with mobile devices max print resolution 150 ppp.
with Pc devices max print resolution 300 ppp.

fix(geo): eliminate 300 ppp resolution from mobile devices

---

packages/common/src/lib/color-picker-form-field/color-picker-form-field.component.ts
packages/geo/src/lib/style/style-modal/layer/style-modal-layer.component.html

related to issue #1508 
Fix it?

fix(geo): Layer color picker do not change the fill/stroke color

---

packages/core/src/theming/prebuilt-themes/blue-theme.scss
packages/core/src/theming/prebuilt-themes/bluedark-theme.scss
packages/core/src/theming/prebuilt-themes/bluedq-theme.scss
packages/core/src/theming/prebuilt-themes/qcca-theme.scss

fix(core): delete foreground from blue theme

---

packages/geo/src/lib/measure/measurer/measurer.component.html
packages/geo/src/lib/measure/measurer/measurer.component.scss
packages/geo/src/lib/measure/measurer/measurer.component.ts

this behavior related to #1499 and [#1096](https://github.com/infra-geo-ouverte/igo2/issues/1096)
- adapt numbers with unit changes.
- solve show hide ligne ditanse and area surface.
- keep Length and area units after navigating to another tool.

fix(geo): adapt numbers with unit and solve show hide ditanse and area 

---

angular.json
package-lock.json
package.json
packages/auth/package.json
packages/auth/src/lib/shared/admin.guard.ts
packages/auth/src/lib/shared/auth.interceptor.ts
packages/auth/src/lib/shared/auth.interface.ts
packages/auth/src/lib/shared/auth.service.ts
packages/auth/src/lib/shared/index.ts
packages/auth/src/lib/shared/token.interface.ts
packages/auth/src/lib/shared/token.service.ts
packages/auth/src/public_api.ts
packages/context/src/lib/context-map-button/user-button/user-dialog.component.ts
packages/context/src/lib/share-map/share-map/share-map-api.component.ts
packages/core/src/lib/analytics/shared/analytics.interface.ts
packages/core/src/lib/analytics/shared/analytics.service.ts
packages/integration/src/lib/analytics/analytics-listener.service.ts

Old deps for jwt-decode
Update it  + add an interface for the decoded jwt

chore(auth): jwt-decode from v2 to v4

---

packages/geo/src/lib/search/shared/sources/icherche.ts
packages/geo/src/locale/en.geo.json
packages/geo/src/locale/fr.geo.json

N/A
Insert research into icherche for layer unites
N/A

feat_icherche(unites) insert research into icherche

---

packages/common/src/lib/form/form-field/form-field-text.component.html
packages/common/src/lib/form/form-field/form-field-text.component.ts

When clicking on password type form field, the form was submitted. 
Prevent it. 
+
Autohide password based on a 10sec timeout.

fix(common): prevent form submit on password hide/show and auto hide password after 10sec of inactivity

---

projects/demo/src/app/geo/layer/layer.component.ts
projects/demo/src/app/geo/ogc-filter/ogc-filter.component.ts
projects/demo/src/app/geo/print/print.component.ts

this behavior related to #1555 

fix(demo): update layers option in print and ogc filter

---

packages/geo/src/lib/layer/shared/layers/layer.interface.ts
packages/geo/src/lib/map/baselayers-switcher/mini-basemap.component.ts

When a base layer shown in the mini-basemap/preview has linked layers, the linked layers are always shown/visible in the preview. This can lead to performance issues.
The new config, showInMiniBaseMap, allows the user to decide if a linked layer should be visible in the preview of a base layer or not.

feat(linked-layers): Added new config for visibility in Base Layer Switcher

---

packages/geo/src/lib/map/shared/controllers/view.ts

The rotation button is disabled despite the effective rotation. 
Set the rotation on view definition.

fix(geo): initial rotation is not supplied to viewcontroller

---

packages/integration/src/lib/catalog/catalog-browser-tool/catalog-browser-tool.component.ts

this behavior related ti #1573 

fix(geo): check catalog not undefined before loading items

---

packages/common/package.json
packages/context/package.json
packages/core/ng-package.json
packages/core/ng-package.prod.json
packages/core/package.json
packages/core/src/packages-prod.import.scss
packages/geo/package.json
scripts/src/core/postbuild-core.ts

Ajustement de path pour respecter la règle que tous les SASS devrait se retrouver dans le dossier `src` en mode distribution. Ce qui nous permet de rouler en local (symlink) comme en prod (distribution).
Breaking changes pour la nomenclature de l'export `theming` qui devient `theme`. Pour éviter les collisions lors de la résolutions de paths. Je passe le BREAKING CHANGES incognito vu qu'on doit être les seuls a utiliser les thèmes via les fichiers SASS.

fix: sass exports for themes and utils

---

packages/geo/src/lib/catalog/shared/catalog.service.ts
packages/geo/src/lib/datasource/shared/capabilities.interface.ts

Arcgisrest catalog are a simple list of layers.
Add a group layer logic to show groups and nested layers within.
- [x ] No

feat(geo): add a sub level to arcgisrest  catalogs

---

packages/geo/src/lib/search/shared/sources/cadastre.ts

this behavior related to #1597 

fix(geo): garantine no comma in the beginning and end of search term

---

packages/auth/ng-package.json
packages/auth/ng-package.prod.json
packages/auth/src/auth.theme.scss
packages/auth/src/lib/auth-form/auth-intern.component.html
packages/auth/src/lib/auth-form/auth-intern.component.scss
packages/auth/src/lib/auth-form/auth-intern.theme.scss
packages/auth/src/lib/auth.module.ts
packages/auth/src/locale/fr.auth.json
packages/core/src/packages.import.scss
packages/core/src/theming/all-theme.scss

Fix #1632 
Go to the issue to see more details and example of the new design proposition

1632 la modale dauthentification le bouton se connecter et rester anonyme

---

packages/geo/src/lib/filter/ogc-filter-time/ogc-filter-time.component.ts
packages/geo/src/lib/filter/shared/ogc-filter.ts

this bug related to [#987](https://github.com/infra-geo-ouverte/igo2/issues/987)

fix(geo): ensure ogc filter accept today and now

---

packages/common/src/lib/tool/shared/toolbox.ts
packages/geo/src/lib/catalog/catalog-library/catalog-library.component.ts
packages/integration/src/lib/catalog/catalog-library-tool/catalog-library-tool.component.ts

this behavior related to [#1007](https://github.com/infra-geo-ouverte/igo2/issues/1007) in igo2

feat(integration, common, geo): keep selected catalog when changing tools

---

packages/integration/src/lib/map/advanced-map-tool/advanced-coordinates/advanced-coordinates.component.ts

this behavior related to [#1149](https://github.com/infra-geo-ouverte/igo2/issues/1149) in igo2

fix(integration): update latitude and longitude if coords system change

---

packages/integration/src/lib/map/map-proximity-tool/map-proximity-tool.component.ts

refactor(integration): change icon for proximity tool

---

packages/geo/src/lib/filter/ogc-filter-form/ogc-filter-form.component.ts

The application cannot process filter with the special character '*'
It sends the following error message:
It can now filter with special character '*' as intended.

Fix Advanced filter 'As' 

---

package-lock.json
packages/core/monitoring/src/sentry/sentry.interface.ts
packages/core/monitoring/src/sentry/sentry.provider.spec.ts
packages/core/monitoring/src/sentry/sentry.provider.ts
packages/core/monitoring/src/sentry/sentry.spec.ts
packages/core/monitoring/src/sentry/sentry.ts
packages/core/monitoring/src/sentry/sentry.utils.spec.ts
packages/core/monitoring/src/sentry/sentry.utils.ts
packages/core/package.json

- BREAKING CHANGE: Sentry enableReplay options is removed in favor of replaysSessionSampleRate. Samething for enableTracing replaced by tracesSampleRate. See the Sentry doc for more details

refactor(core): sentry monitoring update to v8

---

package-lock.json
packages/context/src/lib/context-manager/shared/layer-context.directive.ts
packages/core/package.json
packages/core/src/lib/core.module.ts
packages/geo/src/lib/datasource/shared/capabilities.service.ts
packages/geo/src/lib/layer/shared/layer.service.ts
packages/geo/src/lib/layer/shared/layers/layer.ts
packages/geo/src/lib/layer/shared/layers/vector-layer.ts
packages/geo/src/lib/offline/geoDB/configFileToGeoDB.service.ts
packages/geo/src/lib/offline/geoDB/geoDB.service.ts
packages/geo/src/lib/offline/index.ts
packages/geo/src/lib/offline/layerDB/layerDB.service.ts
packages/geo/src/lib/offline/offline.interface.ts
packages/geo/src/lib/offline/offline.provider.ts
packages/geo/src/lib/offline/shared/geo-network.service.ts
packages/integration/src/lib/environment/environment.interface.ts

Certaine application n'utilise pas les capacités de offline et on a aucun moyen de désactiver l'instanciation de la base de donnée IndexedDB. Cela nous causait des erreurs dans nos applications alors on propose une manière de désactiver via les fichiers d'environnement applicative (environment.ts).
En lien avec:
https://github.com/infra-geo-ouverte/igo2/pull/1167

Add the possibility to configure the offline capabilities

---

packages/core/analytics/src/analytics.service.ts

Current cookies defined by Matomo are unsecure by default.
Ensure to have secured cookies on https

feat(core): Allow to use secure cookies on https instances

---

packages/core/language/src/shared/language.interface.ts
packages/core/language/src/shared/language.loader.ts
packages/core/language/src/shared/language.provider.ts
packages/core/src/lib/core.module.ts
projects/demo/src/main.ts

L'objectif est de permettre l'utilisation du module Language sans avoir besoin du module de Config. Aussi dans certain cas on veut l'utiliser sans nécessairement télécharger les fichiers de translation de la lib par exemple pour SDG, lorsqu'on utiliser les composantes de bases.
Cette PR est basé sur la branche fix/language, il y a aussi une branche correspondante pour l'assemblage
https://github.com/infra-geo-ouverte/igo2/pull/1169

fix(core): language add static loader and options to ignores libs locale

---

packages/context/src/lib/context-manager/shared/context.interface.ts
packages/context/src/lib/context-manager/shared/context.service.ts
packages/geo/src/lib/datasource/shared/datasources/arcgisrest-datasource.ts
packages/geo/src/lib/datasource/shared/datasources/carto-datasource.interface.ts
packages/geo/src/lib/datasource/shared/datasources/carto-datasource.ts
packages/geo/src/lib/datasource/shared/datasources/cluster-datasource.interface.ts
packages/geo/src/lib/datasource/shared/datasources/cluster-datasource.ts
packages/geo/src/lib/datasource/shared/datasources/datasource.interface.ts
packages/geo/src/lib/datasource/shared/datasources/datasource.ts
packages/geo/src/lib/datasource/shared/datasources/feature-datasource.interface.ts
packages/geo/src/lib/datasource/shared/datasources/feature-datasource.ts
packages/geo/src/lib/datasource/shared/datasources/imagearcgisrest-datasource.interface.ts
packages/geo/src/lib/datasource/shared/datasources/imagearcgisrest-datasource.ts
packages/geo/src/lib/datasource/shared/datasources/mvt-datasource.interface.ts
packages/geo/src/lib/datasource/shared/datasources/mvt-datasource.ts
packages/geo/src/lib/datasource/shared/datasources/osm-datasource.interface.ts
packages/geo/src/lib/datasource/shared/datasources/tilearcgisrest-datasource.interface.ts
packages/geo/src/lib/datasource/shared/datasources/tilearcgisrest-datasource.ts
packages/geo/src/lib/datasource/shared/datasources/tiledebug-datasource.interface.ts
packages/geo/src/lib/datasource/shared/datasources/wfs-datasource.interface.ts
packages/geo/src/lib/datasource/shared/datasources/wfs-datasource.ts
packages/geo/src/lib/datasource/shared/datasources/wms-datasource.interface.ts
packages/geo/src/lib/datasource/shared/datasources/wms-datasource.ts
packages/geo/src/lib/datasource/shared/datasources/wmts-datasource.interface.ts
packages/geo/src/lib/datasource/shared/datasources/xyz-datasource.interface.ts
packages/geo/src/lib/layer/shared/layers/layer.ts
packages/geo/src/lib/search/shared/sources/ilayer.interfaces.ts
projects/demo/src/app/geo/ogc-filter/ogc-filter.component.ts

Permettre une meilleure distinctions des éléments sauvegardable selon les besoins de chaque layer/datasource. Nous allons avoir d'autres modiciation dans la branche sur la gestions des LayerGroup mais ces changements sont nécessaires pour la prochaine feature.
(cherry picked from commit f87c3ed1e137480748c3e862dfe2272554cfb768)

fix(geo): add saveable options for layers and datasources

---

packages/geo/src/lib/catalog/catalog-library/add-catalog-dialog.component.html
packages/geo/src/lib/catalog/catalog-library/add-catalog-dialog.component.scss
packages/geo/src/lib/catalog/catalog-library/add-catalog-dialog.component.ts
packages/geo/src/lib/catalog/catalog-library/catalog-library.component.ts
packages/geo/src/locale/en.geo.json
packages/geo/src/locale/fr.geo.json
projects/demo/src/app/geo/catalog/catalog.component.html

If we configure composite catalogs to be added to the predefined list, the catalogs is not added to the catalog store.
refer to  https://github.com/infra-geo-ouverte/igo2-lib/issues/1631
Refactor the add catalog dialog to split predefined catalog and custom catalogs. 

feat(geo): split the add catalog dialog in tabs, predefined catalog and custom services

---

packages/geo/src/lib/datasource/shared/datasources/wfs-datasource.ts
packages/geo/src/lib/datasource/shared/datasources/wms-wfs.utils.ts
packages/geo/src/lib/layer/shared/layers/vector-layer.ts
packages/geo/src/lib/workspace/shared/edition-workspace.service.ts

Refactor and fix cancellation of current request. We had a race condition when we zoom out quickly with a WFS that contains a lot of data. The calls were carried away and created an infinite loop

fix(geo): layer - adjust the cancellation of ongoing request

---

packages/geo/src/lib/datasource/shared/datasources/datasource.interface.ts
packages/geo/src/lib/datasource/shared/datasources/datasource.ts
packages/geo/src/lib/datasource/shared/datasources/wfs-datasource.ts
packages/geo/src/lib/datasource/shared/datasources/wms-datasource.ts
packages/geo/src/lib/datasource/shared/datasources/wms-wfs.utils.ts
packages/geo/src/lib/layer/shared/layers/layer-base.ts
packages/geo/src/lib/layer/shared/layers/layer.ts
packages/geo/src/lib/layer/shared/layers/linked/linked-layer.interface.ts
packages/geo/src/lib/layer/shared/layers/linked/linked-layer.ts
packages/geo/src/lib/layer/shared/layers/vector-layer.ts
packages/geo/src/lib/map/utils/layer-watcher.ts
packages/geo/src/lib/workspace/shared/index.ts
packages/geo/src/lib/workspace/shared/wms-workspace.service.ts
packages/geo/src/lib/workspace/shared/workspace.interface.ts
packages/geo/src/lib/workspace/workspace-selector/workspace-selector.directive.ts

This fix the refresh interval that was not working. We implement it to work with WMS and WFS datasource. This usefull when we have a WMS that need to be refresh a certain interval and we could have a LinkedLayer for the workspace and this layer will also sync at the refresh if we add the configuration.
For testing add `"refreshIntervalSec": 2` to your WmsDatasourceOptions. You could also add a LinkedLayer with the `LinkedProperties.REFRESH` and it should refresh at the same time of it's parent

fix(geo): datasource refresh implement event manager and add compatibility with workspace linked layer

---

packages/geo/src/lib/query/shared/query-search-source.ts
packages/geo/src/lib/search/search-bar/search-bar.component.html
packages/geo/src/lib/search/search-bar/search-bar.component.ts
packages/geo/src/lib/search/search-settings/search-settings.component.html
packages/geo/src/lib/search/search-settings/search-settings.component.ts
packages/geo/src/lib/search/shared/sources/cadastre.ts
packages/geo/src/lib/search/shared/sources/coordinates.ts
packages/geo/src/lib/search/shared/sources/icherche.ts
packages/geo/src/lib/search/shared/sources/ilayer.ts
packages/geo/src/lib/search/shared/sources/nominatim.ts
packages/geo/src/lib/search/shared/sources/source.ts
packages/geo/src/lib/search/shared/sources/storedqueries.ts
packages/geo/src/lib/search/shared/sources/workspace.ts
packages/geo/src/locale/en.geo.json
packages/geo/src/locale/fr.geo.json

There is no way to reset the seach sources options. 
Add a button/method to reset/store the default options from each search sources.
Configurable with a parameter. 
See the PR in the IGO2 project to test along. 
https://github.com/user-attachments/assets/d8c0c35b-8d84-477a-9c86-f569b9a0af4a

feat(search): add reset options functionality to search source options
