infra-geo-ouverte/igo2-lib

- demo-app/app/app.component.html
- demo-app/app/app.component.ts
- lib/src/filter/index.ts
- lib/src/filter/module.ts
- lib/src/filter/shared/index.ts
- lib/src/filter/shared/time-filter.interface.ts
- lib/src/filter/time-filter-form/index.ts
- lib/src/filter/time-filter-form/time-filter-form.component.html
- lib/src/filter/time-filter-form/time-filter-form.component.spec.ts
- lib/src/filter/time-filter-form/time-filter-form.component.styl
- lib/src/filter/time-filter-form/time-filter-form.component.ts
- lib/src/filter/time-filter-item/index.ts
- lib/src/filter/time-filter-item/time-filter-item.component.html
- lib/src/filter/time-filter-item/time-filter-item.component.spec.ts
- lib/src/filter/time-filter-item/time-filter-item.component.styl
- lib/src/filter/time-filter-item/time-filter-item.component.ts
- lib/src/filter/time-filter-list/index.ts
- lib/src/filter/time-filter-list/time-filter-list.component.html
- lib/src/filter/time-filter-list/time-filter-list.component.spec.ts
- lib/src/filter/time-filter-list/time-filter-list.component.styl
- lib/src/filter/time-filter-list/time-filter-list.component.ts
- lib/src/index.ts
- lib/src/layer/layer-item/layer-item.component.html
- lib/src/layer/layer-legend/layer-legend.component.html
- lib/src/layer/module.ts
- lib/src/layer/shared/layers/layer-wms.ts
- lib/src/layer/shared/layers/layer.interface.ts
- lib/src/map/shared/map.ts
- lib/src/module.ts
- package.json
> feat(time filter): time filter module

- src/lib/context/shared/context.interface.ts
- src/lib/context/shared/map-context.directive.ts
- Add an option to keep the current map view when switching context
> feat(context): add keepCurrentView options

- src/lib/print/print-form/print-form.component.html
- src/lib/print/print-form/print-form.component.ts
- src/lib/print/shared/print.interface.ts
- src/lib/print/shared/print.service.ts
- src/lib/utils/tilequeue.ts
- src/locale/en.json
- src/locale/fr.json
- Better print template with title
- Fix title loading issue
- Fix blank space issue
> Print template

- src/lib/context/shared/map-context.directive.ts
- src/lib/datasource/shared/datasources/datasource.ts
- src/lib/datasource/shared/datasources/feature-datasource.ts
- src/lib/datasource/shared/datasources/osm-datasource.ts
- src/lib/datasource/shared/datasources/wms-datasource.ts
- src/lib/datasource/shared/datasources/wmts-datasource.ts
- src/lib/datasource/shared/datasources/xyz-datasource.ts
- src/lib/form/fields/map-field/map-field.component.ts
- src/lib/layer/shared/layers/image-layer.ts
- src/lib/layer/shared/layers/layer.interface.ts
- src/lib/layer/shared/layers/layer.ts
- src/lib/layer/shared/layers/tile-layer.ts
- src/lib/layer/shared/layers/vector-layer.ts
- src/lib/map/map-browser/map-browser.component.ts
- src/lib/map/shared/map.ts
- src/lib/print/shared/print.service.ts
- src/lib/query/shared/query.directive.ts
- Change olMap in map.ts to ol
- Change olLayer in layer.ts to ol
- Change olSource in datasource.ts to ol
> refactor(ol): change olMap, olLayer and olSource to ol

- src/demo-app/app/app.component.ts
- src/lib/context/shared/context.interface.ts
- src/lib/context/shared/layer-context.directive.ts
- src/lib/context/shared/map-context.directive.ts
- src/lib/datasource/shared/datasource.service.ts
- src/lib/datasource/shared/datasources/datasource.interface.ts
- src/lib/datasource/shared/datasources/feature-datasource.interface.ts
- src/lib/datasource/shared/datasources/osm-datasource.interface.ts
- src/lib/datasource/shared/datasources/wfs-datasource.interface.ts
- src/lib/datasource/shared/datasources/wms-datasource.interface.ts
- src/lib/datasource/shared/datasources/wms-datasource.ts
- src/lib/datasource/shared/datasources/wmts-datasource.interface.ts
- src/lib/datasource/shared/datasources/wmts-datasource.ts
- src/lib/datasource/shared/datasources/xyz-datasource.interface.ts
- src/lib/datasource/shared/datasources/xyz-datasource.ts
- src/lib/layer/module.ts
- src/lib/layer/shared/index.ts
- src/lib/layer/shared/layer.service.ts
- src/lib/layer/shared/layers/image-layer.interface.ts
- src/lib/layer/shared/layers/image-layer.ts
- src/lib/layer/shared/layers/layer.interface.ts
- src/lib/layer/shared/layers/layer.ts
- src/lib/layer/shared/layers/tile-layer.interface.ts
- src/lib/layer/shared/layers/tile-layer.ts
- src/lib/layer/shared/layers/vector-layer.interface.ts
- src/lib/layer/shared/layers/vector-layer.ts
- src/lib/layer/shared/style.service.spec.ts
- src/lib/layer/shared/style.service.ts
- src/lib/map/shared/map.ts
- src/lib/tool/tools/search-results-tool/search-results-tool.component.ts
- Differentiate layer options from layer context because context stuff needs to be serializble where as options may be anything.
> refactor(context): refactor context layer

- package.json
- src/demo-app/app/app.component.html
- src/lib/context/shared/context.service.spec.ts
- src/lib/core/message/index.ts
- src/lib/core/message/message-center/index.ts
- src/lib/core/message/message-center/message-center.component.html
- src/lib/core/message/message-center/message-center.component.spec.ts
- src/lib/core/message/message-center/message-center.component.styl
- src/lib/core/message/message-center/message-center.component.ts
- src/lib/core/message/shared/message.enum.ts
- src/lib/core/message/shared/message.interface.ts
- src/lib/core/message/shared/message.service.spec.ts
- src/lib/core/message/shared/message.service.ts
- src/lib/core/module.ts
- src/lib/core/request/request.service.spec.ts
- src/lib/datasource/shared/capabilities.service.spec.ts
- src/lib/datasource/shared/datasource.service.spec.ts
- src/lib/print/shared/print.service.spec.ts
- src/lib/print/shared/print.service.ts
- src/lib/query/shared/query.service.spec.ts
- src/lib/search/search-bar/search-bar.component.spec.ts
- src/lib/search/shared/search.service.spec.ts
- src/lib/tool/tools/context-manager-tool/context-manager-tool.component.spec.ts
> feat(message): message center

- src/lib/core/language/shared/language.service.ts
languageService.translate.get('key') -> return observable
languageService.translate.instant('key') -> return value
> feat(translate): add a way to get translations

- src/lib/layer/layer-item/layer-item.component.html
https://github.com/infra-geo-ouverte/igo2/issues/201
> update material visibility icon

- src/lib/filter/time-filter-form/time-filter-form.component.ts
fix issue #91 
fail with mode "--prod"
> fix(timefilter): issue #91

- package.json
- src/lib/filter/time-filter-form/time-filter-form.component.ts
- src/lib/map/poi-button/poi-button.component.ts
fix wmstime enddate and startdate, layer with no dimension in capabilities no wmstime enable, add htmlgetinfo and wmstime layer in default context.
> fix(wmst): fix wmst startdate, capabilites-wmst no dimension

- src/lib/filter/time-filter-form/time-filter-form.component.spec.ts
- src/lib/filter/time-filter-form/time-filter-form.component.ts
fix wmstime filter and always use min value as first date, to be done: 2 value in rang for slider (not present in md_slider for the moment).
> fix(slider) wmstime slider min value

- src/lib/datasource/shared/datasources/wms-datasource.ts
- src/lib/filter/time-filter-form/time-filter-form.component.html
- src/lib/filter/time-filter-form/time-filter-form.component.styl
- src/lib/filter/time-filter-form/time-filter-form.component.ts
related : https://github.com/infra-geo-ouverte/igo2-lib/issues/77#issuecomment-346048397
> fix(wmstime): css, wmstime datetime format, x button

- src/demo-app/contexts/wfs_test.json
According to PR #132, this file must be updated for new options.
> updating this file for ogcFilters's options.

- src/lib/filter/ogc-filterable-item/ogc-filterable-item.component.html
- src/lib/filter/ogc-filterable-item/ogc-filterable-item.component.ts
- src/lib/layer/layer-item/layer-item.component.ts
This PR is suitable for issue #122 and attempt to wait response for source fields (wfs & wms source) to populate menus.
> Colors & wait for sourcefields

- src/demo-app/contexts/wfs_test.json
wrong property for PropertyIsEqualTo
> replace  wfs_test pattern with expression for EqualTo

- src/demo-app/contexts/wfs_test.json
- src/lib/filter/ogc-filterable-item/ogc-filterable-item.component.ts
When adding a filter & the list of filter is empty. Setting the filter status to active (active=true).
For non-empty filter's list, the status is set to false.
> Add new filter

- package.json
- src/lib/filter/time-filter-form/time-filter-form.component.html
- src/lib/filter/time-filter-form/time-filter-form.component.styl
- src/lib/filter/time-filter-form/time-filter-form.component.ts
https://github.com/infra-geo-ouverte/igo2-lib/issues/125
https://github.com/infra-geo-ouverte/igo2-lib/issues/124
> fix(filter): wmstime init startdate value + css placeholder

- src/lib/filter/ogc-filter-form/ogc-filter-form.component.html
- src/lib/filter/ogc-filter-form/ogc-filter-form.component.styl
- src/lib/filter/ogc-filterable-item/ogc-filterable-item.component.html
- src/lib/filter/ogc-filterable-item/ogc-filterable-item.component.styl
- src/lib/layer/layer-item/layer-item.component.html
- src/locale/en.json
- src/locale/fr.json
Refining CSS alignements for inline-table elements. 
Adding refresh button if ogc-filter.component is used from his tool.
> Alignements and adding refresh controls

- src/lib/datasource/shared/datasources/datasource.interface.ts
- src/lib/datasource/shared/datasources/datasource.ts
- src/lib/datasource/shared/datasources/wms-datasource.ts
- src/lib/filter/time-filter-form/time-filter-form.component.html
- src/lib/filter/time-filter-form/time-filter-form.component.ts
- src/lib/filter/time-filter-item/time-filter-item.component.html
- src/lib/filter/time-filter-item/time-filter-item.component.ts
- src/locale/fr.json
https://github.com/infra-geo-ouverte/igo2-lib/issues/126
> add (filter) year support + edit fr.json

- src/demo-app/contexts/wfs_test.json
- src/lib/query/shared/query.directive.ts
- src/locale/fr.json
When clicking on selected features, a undefined feature was returned. Filtering features !== undefined.
Some translations corrected & mistyped wfs_test uri and title.
> Fixing undefined clicked or dragged features

- src/demo-app/contexts/wfs_test.json
- src/lib/layer/layer-item/layer-item.component.html
- src/lib/query/shared/query.directive.ts
- src/locale/fr.json
Controlling values for undefined downloadURL.
> Undefined download url

- demo/src/app/geo/directions/directions.component.ts
- projects/geo/src/lib/routing/routing-form/routing-form.component.html
- projects/geo/src/lib/routing/routing-form/routing-form.component.ts
Fixing bug when choosing an driving option.
```
[ ] Yes
[x] No
```
Be careful to https://stackoverflow.com/questions/50222738/angular-6-material-mat-select-change-method-removed
> Directions minor fixes

- projects/geo/src/lib/routing/shared/routing.interface.ts
too slow with annotation param.
> fix(routing) : remove annotation, not needed

- package.json
fix build.geo on windows (maximum call stack size exceeded)
```
[ ] Yes
[X] No
```
> fix(*) fix build.geo on windows (maximum call stack size exceeded)

- projects/context/src/locale/en.context.json
- projects/context/src/locale/fr.context.json
Some locale were missing into the context library.
They now share common keys.
I've also checked for other projects if locale keys were similar. They are.
```
[ ] Yes
[X] No
```
> fix(context) Locale do not contains common keys

- projects/geo/src/lib/search/search-sources/search-source.interface.ts
- [X ] The commit message follows our guidelines:https://github.com/infra-geo-ouverte/igo2/blob/master/.github/CONTRIBUTING.md#git-commit-guidelines
Fix search source interface for reseautq (important for IGO2 integration)
```
[ ] Yes
[x ] No
```
> fix(search-source) Provide interface for reseautq

- demo/src/app/geo/layer/layer.component.html
- projects/core/src/lib/message/shared/message.service.ts
- projects/geo/src/lib/filter/ogc-filter-button/ogc-filter-button.component.html
- projects/geo/src/lib/filter/ogc-filterable-item/ogc-filterable-item.component.html
- projects/geo/src/lib/filter/ogc-filterable-list/ogc-filterable-list.component.html
- projects/geo/src/lib/toast/toast.component.html
- projects/geo/src/lib/toast/toast.component.ts
- projects/tools/src/lib/map-details-tool/map-details-tool.component.html
- projects/tools/src/lib/search-results-tool/search-results-tool.component.ts
Fix issues with button placement & map providing.
```
[ ] Yes
[x ] No
```
> Fix button ogc filter

- projects/geo/src/lib/datasource/shared/capabilities.service.ts
A method has been moved in OL and is not found anymore.
It is now imported from the right place.
```
[ ] Yes
[x] No
```
> fix WMTS GetCapbilities import error

- projects/common/src/lib/custom-html/custom-html.component.html
- projects/common/src/lib/custom-html/custom-html.component.ts
- projects/common/src/lib/custom-html/custom-html.module.ts
- projects/common/src/lib/custom-html/index.ts
- projects/common/src/public_api.ts
- projects/tools/src/lib/about-tool/about-tool.component.html
- projects/tools/src/lib/about-tool/about-tool.component.ts
- projects/tools/src/lib/about-tool/about-tool.interface.ts
- projects/tools/src/lib/about-tool/about-tool.module.ts
- projects/tools/src/lib/about-tool/index.ts
- projects/tools/src/lib/tools.module.ts
- projects/tools/src/locale/en.tools.json
- projects/tools/src/locale/fr.tools.json
- projects/tools/src/public_api.ts
1- @igo2/common: Adding a custom component to build html template by a string variable.
1- @igo2/tools: New tool named 'About' with default message or customizable with an option. Into a context, should be written like this
`    {
"name": "about",
"options": {
"html": "<h1>Customizing the about tool</h1>"
}
}`
```
[ ] Yes
[X] No
```
> Tool about 

- projects/geo/src/lib/filter/ogc-filterable-item/ogc-filterable-item.component.ts
WMS with WFS were not using correct property.
WMS with WFS now using correct property for ogc-filter geometry fieldname
```
[ ] Yes
[ ] No
```
> fix(ogc-filter) WMS with linked wfs

- projects/geo/src/lib/filter/ogc-filterable-item/ogc-filterable-item.component.ts
fix(ogc-filter) geometry fieldname
```
[ ] Yes
[X] No
```
> fix(ogc-filter) fix  geometry fieldname

- projects/geo/src/lib/routing/routing-form/routing-form.component.html
- projects/geo/src/lib/routing/routing-form/routing-form.component.ts
- projects/geo/src/locale/en.geo.json
- projects/geo/src/locale/fr.geo.json
1- Fix duplicate routes& stops when coming back to routing component.
1- Remove duplicated route and stop (delete on component destroy)
2- Fix issue #207 
3- Add a share url button in form.
```
[ ] Yes
[X] No
```
> Fix directions

- projects/geo/src/lib/routing/routing-form/routing-form.component.ts
1- Unsubscribe route queries on destroy of component. If the route queries are not unsubscribed, route (on map) will be shown outside routing-component. ( Issue #224 )
2- Removing result without geometries (when searching by term) in routing component. 
1- Unbsubscribe route queries and form change.
2- Remove results without geometry ex: layer search sources
```
[ ] Yes
[x] No
```
> Fix routing subscription

- projects/geo/src/lib/routing/routing-form/routing-form.component.ts
When focus on a stop into the routing component AND you don't fire a click on map AND you leave the routing tool AND you fire a click THEN a stop is added the map.
Prevent the previously described behavior ... hum (clear enough?) :) 
```
[ ] Yes
[x] No
```
> fix(routing) unlisten to singleclick event when leaving component.

- projects/geo/src/lib/routing/routing-form/routing-form.component.ts
Higher tolerance on route selection on map
```
[ ] Yes
[x] No
```
> fix(routing) tolerance on routes selection

- README.md
> docs(readme) Developement server

- projects/common/src/lib/list/list-item.directive.ts
- projects/common/src/lib/list/list.component.scss
- projects/common/src/lib/list/list.component.ts
- projects/common/src/lib/list/list.theming.scss
See #232 
igo-list-items can now be disabled
```
[ ] Yes
[x] No
```
> feat(list): igo-list-items can now be disabled

- gulpfile.js
Error on npm run build.common && npm run build.auth
```
[ ] Yes
[x] No
```
> Gulp with empty directory

- projects/geo/src/lib/layer/layer-list/layer-list.component.ts
Wrong keyword was used.
Now using the keyword stored into layer-list service. 
```
[ ] Yes
[ ] No
```
> fix(layer-list) wrong keyword was used.

- projects/geo/src/lib/import-export/shared/drop-geo-file.directive.ts
- projects/geo/src/lib/import-export/shared/import-export.service.ts
- projects/geo/src/lib/import-export/shared/import-export.type.ts
https://github.com/infra-geo-ouverte/igo2-lib/issues/247
> add(import-export): gpx support format

- demo/src/environments/environment.ts
> fix(demo) propertiesAlias

- package-lock.json
- projects/geo/src/lib/datasource/shared/datasource.service.ts
- projects/geo/src/lib/datasource/shared/datasources/any-datasource.ts
- projects/geo/src/lib/datasource/shared/datasources/datasource.interface.ts
- projects/geo/src/lib/datasource/shared/datasources/feature-datasource.ts
- projects/geo/src/lib/datasource/shared/datasources/index.ts
- projects/geo/src/lib/datasource/shared/datasources/websocket-datasource.interface.ts
- projects/geo/src/lib/datasource/shared/datasources/websocket-datasource.ts
- projects/geo/src/lib/layer/shared/layer.service.ts
- projects/geo/src/lib/layer/shared/layers/vector-layer.interface.ts
- projects/geo/src/lib/layer/shared/layers/vector-layer.ts
- proxy.conf.json
Add websocket support 
```
[ ] Yes
[x] No
```
> Websocket support

- packages/common/src/lib/entity/shared/transaction.ts
Transactions cannot be rolledback
Transactions can be rollbacked. Rolling back a transaction reverts it's changes on a store.
```
[ ] Yes
[ ] No
```
> feat(transaction): uncommited transactions can be rollbacked

- packages/geo/src/lib/search/search-bar/search-bar.component.ts
In the search bar, there is no launch event during a search option change.
The event is started when a search option is changed.
```
[ ] Yes
[x ] No
```
> Search type

- demo/src/environments/environment.prod.ts
- demo/src/environments/environment.ts
- packages/geo/src/lib/catalog/shared/catalog.interface.ts
- packages/geo/src/lib/catalog/shared/catalog.service.ts
- packages/geo/src/lib/datasource/shared/datasources/carto-datasource.ts
- packages/geo/src/lib/datasource/shared/datasources/tilearcgisrest-datasource.ts
- packages/geo/src/lib/datasource/shared/datasources/wms-datasource.ts
- packages/geo/src/lib/feature/feature-details/feature-details.component.html
- packages/geo/src/lib/feature/feature-details/feature-details.component.ts
- packages/geo/src/lib/filter/ogc-filterable-item/ogc-filterable-item.component.html
- packages/geo/src/lib/filter/ogc-filterable-item/ogc-filterable-item.component.ts
- packages/geo/src/lib/filter/shared/ogc-filter.interface.ts
- packages/geo/src/lib/filter/shared/ogc-filter.service.ts
- packages/geo/src/lib/layer/layer-item/layer-item.component.html
- packages/geo/src/lib/query/shared/query.enums.ts
- packages/geo/src/lib/query/shared/query.interfaces.ts
- packages/geo/src/lib/query/shared/query.service.ts
Get back some PR & commits made on master during the dev of alpha 1.0.0-alpha.1
This PR DO NOT include all the commit and PR. Only some were picked.
```
[Y ] Yes
[] No
```
Minor Breaking change :
QueryHtmlTarget  = 'innerhtml' do not exist anymore. Use iframe instead.
> Merged into master during alpha dev

- packages/geo/src/lib/print/print-form/print-form.component.html
- packages/geo/src/lib/print/print-form/print-form.component.scss
- packages/geo/src/lib/print/print-form/print-form.component.ts
- packages/geo/src/lib/print/shared/print.type.ts
- packages/geo/src/locale/en.geo.json
- packages/geo/src/locale/fr.geo.json
Some stugg in the print UI needed improvements
Change the slide-toggle position
Fix some labels that weren't translated
```
[ ] Yes
[x] No
```
> ui(print): minor changes to the print UI and changes in some labels

- packages/geo/src/lib/feature/shared/store.ts
- packages/geo/src/lib/feature/shared/strategies/loading.ts
- packages/geo/src/lib/feature/shared/strategies/selection.ts
The feature store movement to it's features used the default behavior and is not configurable
The feature store movement to it's features is now configurable and uses the latest imporvements to the "moveToOlFeatures" function.
```
[ ] Yes
[x] No
```
> feat(store): make it possible to configure the feature store movement

- packages/geo/src/lib/layer/shared/layers/layer.interface.ts
- packages/geo/src/lib/layer/shared/layers/layer.ts
- packages/geo/src/lib/map/shared/map.ts
There's no search layer by an alias.
There's now a layer search by an alias.
```
[ ] Yes
[x ] No
```
> Adding the search layer by a layer alias

- packages/auth/src/lib/auth-form/auth-intern.component.html
You can now press "Enter" key yo log in
```
[ ] Yes
[X ] No
```
@ameliebernier bring chocolate so let's merge it in priority!
> Press key "Enter" to authenticate

- projects/geo/src/lib/datasource/shared/datasources/arcgisrest-datasource.ts
- projects/geo/src/lib/datasource/shared/datasources/carto-datasource.ts
- projects/geo/src/lib/datasource/shared/datasources/datasource.ts
- projects/geo/src/lib/datasource/shared/datasources/feature-datasource.ts
- projects/geo/src/lib/datasource/shared/datasources/osm-datasource.ts
- projects/geo/src/lib/datasource/shared/datasources/tilearcgisrest-datasource.ts
- projects/geo/src/lib/datasource/shared/datasources/websocket-datasource.ts
- projects/geo/src/lib/datasource/shared/datasources/wfs-datasource.ts
- projects/geo/src/lib/datasource/shared/datasources/wms-datasource.ts
- projects/geo/src/lib/datasource/shared/datasources/wmts-datasource.ts
- projects/geo/src/lib/datasource/shared/datasources/xyz-datasource.ts
- projects/geo/src/lib/layer/shared/layers/layer.ts
- projects/utils/src/lib/watcher.ts
Lors de l'utilisation du Websocket (datasource). Un websocket est recréé à chaque fois que la couche est recréé sans que le dernier websocket soit fermé. 
Fermer le websocket lorsque la couche associée est supprimée.
```
[ ] Yes
[x] No
```
> feat(datasource) datasource do something when layer's status change

- projects/geo/src/lib/datasource/shared/datasources/websocket-datasource.ts
l'option 'update' de la configuration 'onmessage' d'un websocket ne fonctionne pas.
l'option 'update' de la configuration 'onmessage' d'un websocket fonctionne.
```
[ ] Yes
[x] No
```
> Fix update websocket

- demo/src/contexts/_contexts.json
- demo/src/contexts/context3.json
- projects/geo/src/lib/datasource/shared/datasource.service.ts
- projects/geo/src/lib/datasource/shared/datasources/any-datasource.interface.ts
- projects/geo/src/lib/datasource/shared/datasources/any-datasource.ts
- projects/geo/src/lib/datasource/shared/datasources/datasource.interface.ts
- projects/geo/src/lib/datasource/shared/datasources/index.ts
- projects/geo/src/lib/datasource/shared/datasources/mvt-datasource.interface.ts
- projects/geo/src/lib/datasource/shared/datasources/mvt-datasource.ts
- projects/geo/src/lib/layer/shared/layer.service.ts
- projects/geo/src/lib/layer/shared/layers/any-layer.interface.ts
- projects/geo/src/lib/layer/shared/layers/any-layer.ts
- projects/geo/src/lib/layer/shared/layers/index.ts
- projects/geo/src/lib/layer/shared/layers/vectortile-layer.interface.ts
- projects/geo/src/lib/layer/shared/layers/vectortile-layer.ts
add MVT(MapBox Vector Tile) and Vector Tile layer suppported as datasource, based on this example: https://openlayers.org/en/latest/examples/vector-tile-selection.html
> feat(datasource,layer): add MVT(MapBox Vector Tile) and Vector Tile

- 3-Deployer_lib_vers_IGO2.bat
- demo/src/app/common/entity-table/entity-table.component.ts
- demo/src/contexts/context3.json
- demo/src/polyfills.ts
- packages/geo/src/lib/catalog/shared/catalog.interface.ts
- packages/geo/src/lib/catalog/shared/catalog.service.ts
- packages/geo/src/lib/datasource/shared/datasources/carto-datasource.ts
- packages/geo/src/lib/layer/utils/legend.ts
refactor(crossOrigin) Harmonizing crossOrigin syntax and properties
feat(polyfills) Allow IE 11 to manage some object properly
ui(entity-table) fix icon
```
[ ] Yes
[x] No
```
> Various fixes alpha

- demo/src/contexts/context3.json
- packages/geo/src/lib/datasource/shared/datasource.service.ts
- packages/geo/src/lib/datasource/shared/datasources/any-datasource.interface.ts
- packages/geo/src/lib/datasource/shared/datasources/any-datasource.ts
- packages/geo/src/lib/datasource/shared/datasources/datasource.interface.ts
- packages/geo/src/lib/datasource/shared/datasources/index.ts
- packages/geo/src/lib/datasource/shared/datasources/mvt-datasource.interface.ts
- packages/geo/src/lib/datasource/shared/datasources/mvt-datasource.ts
- packages/geo/src/lib/layer/shared/layer.service.ts
- packages/geo/src/lib/layer/shared/layers/any-layer.interface.ts
- packages/geo/src/lib/layer/shared/layers/any-layer.ts
- packages/geo/src/lib/layer/shared/layers/index.ts
- packages/geo/src/lib/layer/shared/layers/vector-layer.interface.ts
- packages/geo/src/lib/layer/shared/layers/vectortile-layer.interface.ts
- packages/geo/src/lib/layer/shared/layers/vectortile-layer.ts
- packages/geo/src/lib/layer/shared/style.service.ts
- packages/geo/src/lib/layer/shared/stylebyattribute.ts
* add MVT(MapBox Vector Tile)  supported as new datasource.
* add Vector Tile layer supported as new layer
* add styling by an attribute values
* change context
* fix lint in layers
> feat(datasource,layer): add MVT datasource, vectortile layer and style by attribute

- demo/src/app/geo/search/search.component.ts
- packages/geo/src/lib/search/search-bar/search-bar.component.html
- packages/geo/src/lib/search/search-bar/search-bar.component.scss
- packages/geo/src/lib/search/search-bar/search-bar.module.ts
- packages/geo/src/lib/search/search-selector/search-selector.component.html
- packages/geo/src/lib/search/search-selector/search-selector.component.ts
- packages/geo/src/lib/search/search-selector/search-selector.module.ts
- packages/geo/src/lib/search/search-settings/search-settings.component.html
- packages/geo/src/lib/search/search-settings/search-settings.component.scss
- packages/geo/src/lib/search/search-settings/search-settings.component.spec.ts
- packages/geo/src/lib/search/search-settings/search-settings.component.ts
- packages/geo/src/lib/search/search-settings/search-settings.module.ts
- packages/geo/src/lib/search/search.module.ts
- packages/geo/src/lib/search/shared/search-source.service.ts
- packages/geo/src/lib/search/shared/sources/icherche.ts
- packages/geo/src/lib/search/shared/sources/nominatim.ts
- packages/geo/src/lib/search/shared/sources/source.interfaces.ts
- packages/geo/src/lib/search/shared/sources/source.ts
- packages/geo/src/locale/en.geo.json
- packages/geo/src/locale/fr.geo.json
#349 
control which source-type can be queried
```
[ ] Yes
[x] No
```
> Searchsource setting

- packages/geo/src/lib/catalog/catalog-browser/catalog-browser-layer.component.html
- packages/geo/src/lib/catalog/catalog-browser/catalog-browser.module.ts
- packages/geo/src/lib/catalog/shared/catalog.interface.ts
- Add metadata button
```
[ ] Yes
[ ] No
```
> feat(catalog): add metadata button

- demo/src/app/geo/layer/layer.component.ts
- packages/geo/src/lib/datasource/shared/datasources/arcgisrest-datasource.ts
- packages/geo/src/lib/datasource/shared/datasources/carto-datasource.ts
- packages/geo/src/lib/datasource/shared/datasources/cluster-datasource.ts
- packages/geo/src/lib/datasource/shared/datasources/datasource.ts
- packages/geo/src/lib/datasource/shared/datasources/feature-datasource.ts
- packages/geo/src/lib/datasource/shared/datasources/mvt-datasource.ts
- packages/geo/src/lib/datasource/shared/datasources/osm-datasource.ts
- packages/geo/src/lib/datasource/shared/datasources/tilearcgisrest-datasource.ts
- packages/geo/src/lib/datasource/shared/datasources/websocket-datasource.ts
- packages/geo/src/lib/datasource/shared/datasources/wfs-datasource.ts
- packages/geo/src/lib/datasource/shared/datasources/wms-datasource.ts
- packages/geo/src/lib/datasource/shared/datasources/wmts-datasource.ts
- packages/geo/src/lib/datasource/shared/datasources/xyz-datasource.ts
- packages/geo/src/lib/layer/shared/layers/vector-layer.interface.ts
- packages/geo/src/lib/layer/shared/layers/vector-layer.ts
- packages/geo/src/lib/layer/utils/index.ts
- packages/geo/src/lib/layer/utils/vector-watcher.ts
- packages/geo/src/lib/map/utils/layer-watcher.ts
add watcher to vector layer. Possibility to stop animation and websocket
```
[ ] Yes
[x] No
```
> feat(vector-layer-watcher) add watcher to vector layer

- demo/src/app/geo/directions/directions.component.ts
- packages/geo/src/lib/overlay/shared/overlay.utils.ts
- packages/geo/src/lib/routing/routing-form/routing-form.component.html
- packages/geo/src/lib/routing/routing-form/routing-form.component.scss
- packages/geo/src/lib/routing/routing-form/routing-form.component.ts
fix(routing): fix icone, padding, recherche textuelle, label
> fix(routing): fix icone, padding, recherche textuelle, label

- packages/geo/src/lib/layer/layer-item/layer-item.component.html
- packages/geo/src/lib/layer/layer-item/layer-item.component.scss
- packages/geo/src/lib/layer/layer-item/layer-item.component.ts
Refer to #351 
Line spacing between each layers has been reduced.
```
[ ] Yes
[x] No
```
> Show/hide legend on click (title)

- packages/geo/src/lib/search/search-settings/search-settings.component.spec.ts
test not work
test work
```
[ ] Yes
[x] No
```
> test(geo.search.search-settings) fix test

- package-lock.json
- packages/context/src/lib/context-manager/shared/context.interface.ts
- packages/context/src/lib/context-manager/shared/layer-context.directive.ts
Choose option (not yet on the user interface) to remove or not the layers that have been added to the map on context change.
> feat(context): choose to remove or not all layers on context change

- packages/geo/src/lib/map/baselayers-switcher/baselayers-switcher.component.html
- packages/geo/src/lib/map/baselayers-switcher/mini-basemap.component.html
- packages/geo/src/lib/map/baselayers-switcher/mini-basemap.component.ts
- packages/geo/src/locale/en.geo.json
- packages/geo/src/locale/fr.geo.json
Minimap title is now "Baselayers" when there is 3 or more baselayers available.
When there is two, it still only the title of the other baselayer.
> ui(miniMap): update miniMap title when more than 2 baselayers

- demo/src/app/geo/time-filter/time-filter.component.ts
- packages/geo/src/lib/datasource/shared/capabilities.service.ts
- packages/geo/src/lib/filter/shared/index.ts
- packages/geo/src/lib/filter/shared/time-filter.enum.ts
- packages/geo/src/lib/filter/shared/time-filter.interface.ts
- packages/geo/src/lib/filter/shared/time-filter.service.ts
- packages/geo/src/lib/filter/time-filter-form/time-filter-form.component.html
- packages/geo/src/lib/filter/time-filter-form/time-filter-form.component.ts
- packages/geo/src/lib/filter/time-filter-item/time-filter-item.component.html
- packages/geo/src/lib/filter/time-filter-item/time-filter-item.component.ts
refer to #265 
refer to #265 
```
[ ] Yes
[x] No
```
> Time filter enhancement alpha

- packages/geo/src/lib/search/shared/sources/source.ts
The hashtag is case sensitive
The hashtag is not case sensitive anymore.
```
[ ] Yes
[ ] No
```
> fix(source) Set the hashtag not case sensitive.

- packages/geo/src/lib/download/shared/download.service.ts
Some URL builded by the download.service were not working on IE due to encoding issues ( é è à )...
```
[ ] Yes
[x] No
```
> URL encoding issue on IE.

- packages/geo/src/lib/catalog/catalog-browser/catalog-browser.component.ts
Baselayers catalog add and remove function are now synchronized with baselayers switcher and current map items.
> fix(catalog-browser): fixed add/remove function for baselayers catalog

- packages/geo/src/lib/map/map-browser/map-browser.component.scss
- packages/geo/src/lib/measure/measurer/measurer.component.scss
- Geolocate button css adjustment for IE
- Measurer css adjustment for Firefox
> ui(map-browser/measurer): Apply CSS modification for the interface

- packages/geo/src/lib/datasource/shared/datasources/wms-wfs.utils.ts
test with embacle.json into the igo2 (https://github.com/infra-geo-ouverte/igo2/blob/5333d11e8301e1f32712d407ad6fae68ea038e9c/src/contexts/embacle.json#L88)
```
[ ] Yes
[ ] No
```
> fix(wms-wfs.utils) Json as outputformat.

- packages/geo/src/lib/import-export/import-export/import-export.component.ts
- packages/geo/src/lib/import-export/shared/export.service.ts
- packages/geo/src/lib/import-export/shared/export.utils.ts
- packages/geo/src/lib/import-export/shared/import.service.ts
- packages/utils/src/lib/file.ts
- packages/utils/src/lib/index.ts
- "EPSG" is mandatory in the EPSG code
- Encoding issue may happen when exporting files with ogre
- GPX files are exported with ogre and it's not so good at it
- "EPSG" is not mandatory in the EPSG code
- No more encoding issue when exporting files with ogre
- GPX files are exported using OL. Some files that ogre wouldn't process now work perfectly fine
```
[ ] Yes
[x] No
```
> feat(import-export): EPSG not mandatory and fix encoding issue

- packages/common/src/lib/entity/entity-selector/entity-selector.component.html
- packages/common/src/lib/entity/entity-selector/entity-selector.component.ts
Entity selector cannot be disabled
Entity selector can be disabled
```
[ ] Yes
[x] No
```
> feat(entity selector): entity selector may now be disabled

- packages/integration/src/lib/context/context.state.ts
Tool withotu parent may cause an error in the context state
No more error
```
[ ] Yes
[x] No
```
> fix(tool): fix error caused by tools not having a parent

- packages/integration/src/lib/map/map.state.ts
> feat(map) set attribution collapsed at openning.

- packages/geo/src/lib/geometry/geometry-form-field/geometry-form-field.component.html
- packages/geo/src/lib/geometry/geometry-form-field/geometry-form-field.component.ts
DrawGuide not working since a recent commit
Fixed that
```
[ ] Yes
[x] No
```
> fix(geometry): fix geometry form field drawGuide and geometryType model

- packages/integration/src/lib/search/search-results-tool/search-results-tool.component.ts
The sidenav panel was not fully available on the next search results:
```
[ ] Yes
[x] No
```
> fix(search-result)Use the complete available space

- demo/src/app/geo/query/query.component.html
in the demo, the features are not queryable.
the features are queryable
```
[ ] Yes
[x] No
```
> fix(demo.geo.query) features are queryable

- packages/geo/src/lib/import-export/shared/export.service.ts
- packages/geo/src/lib/import-export/shared/export.type.ts
no CSV format in the export list
CSV format in the export list
```
[ ] Yes
[x] No
```
> feat(geo.import/export) add CSV to Export format

- packages/context/src/lib/share-map/shared/share-map.service.ts
infra-geo-ouverte/igo2#322
```
[ ] Yes
[x] No
```
> Context was not provided to every link. Impact on layers visibility

- packages/geo/src/lib/search/shared/sources/ilayer.ts
> fix(ilayer) remplacement for non alphanum strings on query

- packages/geo/src/lib/filter/time-filter-form/time-filter-form.component.ts
> Stop time filter animation on disable

- packages/geo/src/lib/filter/ogc-filter-form/ogc-filter-form.component.html
- packages/geo/src/lib/layer/layer-item/layer-item.component.html
- packages/geo/src/locale/en.geo.json
- packages/geo/src/locale/fr.geo.json
Adding a tooltip on layer options   ==> ![image](https://user-images.githubusercontent.com/7397743/67095615-58d76900-f184-11e9-9333-a6b71cca6a1a.png)
```
[ ] Yes
[x] No
```
> Various tooltip and translation

- demo/src/app/geo/query/query.component.html
- demo/src/app/geo/query/query.component.ts
- packages/geo/src/lib/datasource/shared/datasources/feature-datasource.ts
- packages/geo/src/lib/feature/shared/feature.interfaces.ts
- packages/geo/src/lib/feature/shared/feature.utils.ts
- packages/geo/src/lib/query/shared/query.directive.ts
- packages/geo/src/lib/query/shared/query.service.ts
'querytitle' is not use with feature datasource
'querytitle' is use with feature datasource + multiples attributes can be specify
```
[ ] Yes
[x] No
```
> feat(geo.datasource.feature) enable 'queryTitle' on feature datasource

- README.md
- demo/src/polyfills.ts
Query crash on IE due to matchAll not found
"L’objet ne gère pas la propriété ou la méthode « matchAll »"
```
[ ] Yes
[ ] No
```
> polyfills(queryService) Matchall polyfill

- demo/src/app/geo/query/query.component.ts
Fix query demo : Create layer sourceOptions attribute.
Issue #499
> fix(query): query demo fix (issue #499)

- demo/src/app/geo/feature/feature.component.ts
- demo/src/assets/mapboxStyleExample-feature.json
- demo/src/assets/mapboxStyleExample-vectortile.json
- package.json
- packages/geo/ng-package.json
- packages/geo/ng-package.prod.json
- packages/geo/package.json
- packages/geo/src/lib/layer/shared/layer.service.ts
- packages/geo/src/lib/layer/shared/layers/vector-layer.interface.ts
- packages/geo/src/lib/layer/shared/layers/vector-layer.ts
- packages/geo/src/lib/layer/shared/layers/vectortile-layer.interface.ts
- packages/geo/src/lib/layer/shared/style.service.ts
- packages/geo/src/lib/layer/shared/vector-style.interface.ts
use mapbox style specification on vector layer.
```
[ ] Yes
[x] No
```
maputnik seems to be a great tool for creating the JSON containing styles
> feat(geo.layer.vector) use mapbox style specification on vector layer

- packages/geo/src/lib/layer/layer-list/layer-list.component.html
Change layer list "remove filter" icon to something less visible
> Layer list filter

- demo/src/app/geo/ogc-filter/ogc-filter.component.ts
- packages/geo/src/lib/datasource/shared/datasources/wfs-datasource.ts
- packages/geo/src/lib/filter/ogc-filter-toggle-button/ogc-filter-toggle-button.component.html
- packages/geo/src/lib/filter/ogc-filter-toggle-button/ogc-filter-toggle-button.component.ts
- packages/geo/src/lib/filter/ogc-filterable-item/ogc-filterable-item.component.ts
- packages/geo/src/lib/filter/shared/ogc-filter.interface.ts
- packages/geo/src/lib/filter/shared/ogc-filter.ts
- packages/utils/src/lib/object-utils.ts
Layer only have 1 push button set.
Push buttons could now have multiple pushbuttons to filter the layer content.
```
[X] Yes
[ ] No
```
**MINOR BREAKING CHANGE**
1. The pushButtons structure is modified.
2. `ogcPushButtons` has been renamed  to `buttons`
Before:
``` 
pushButtons: [
{
logical: 'Or',
ogcPushButtons: [
{title: 'button 1', enabled: true, filters: {...}},
{title: 'button 2', enabled: false, filters: {...}},
{title: 'button 3', enabled: false, filters: {...}},
{title: 'button 4', enabled: false, filters: {...}}
]
},
{
logical: 'Or',
ogcPushButtons: [ …
```
> Multiple pushButtons

- packages/geo/src/lib/filter/time-filter-form/time-filter-form.component.ts
#510 
If the play button is pushed again, the slider reset to the first step value and the animation start again.
```
[ ] Yes
[x] No
```
> Slider Year issue #510

- packages/geo/src/lib/layer/layer-list/layer-list-binding.directive.ts
- packages/geo/src/lib/layer/layer-list/layer-list.component.html
- packages/geo/src/lib/layer/layer-list/layer-list.component.ts
- packages/geo/src/lib/layer/shared/layers/layer.ts
Layer-list toolbar button were not linked to the layers status (visibility or resolution).
Fix the non-synchronized status.
+
Observable on 
- layer.visible as layer.visible$
- layer.isInResolutionsRange as layer.isInResolutionsRange$
```
[ ] Yes
[x] No
```
> Layerlist toolbar

- packages/geo/src/lib/search/shared/sources/coordinates.ts
Replace toFixed by a rounding function to fix error on string data and preventing trailling zeros
```
[ ] Yes
[x] No
```
> Replace toFixed by a rounding function to fix error on string data and preventing trailling zeros

- packages/geo/src/lib/filter/time-filter-form/time-filter-form.component.ts
> refactor(wms) Params interface now all uppercase

- packages/geo/src/lib/filter/spatial-filter/spatial-filter-item/spatial-filter-item.component.scss
Basics CSS corrections for the interface (bug in IE)
> ui(spatialFilterItem): CSS corrections for IE

- packages/geo/src/lib/filter/spatial-filter/spatial-filter-item/spatial-filter-item.component.scss
CSS correction for results table
> ui(results): CSS Fix results table interface

- packages/geo/src/lib/search/shared/sources/storedqueries.ts
> fix(storedqueries) default values for missing configuration

- demo/src/app/core/media/media.component.html
- demo/src/app/core/media/media.component.ts
- packages/core/src/lib/media/media.service.ts
No way to detect if the device is a touchscreen.
https://github.com/infra-geo-ouverte/igo2-lib/issues/526
```
[ ] Yes
[x] No
```
> Detect touch device

- packages/context/src/lib/context-manager/context-permissions/context-permissions-binding.directive.ts
- packages/context/src/lib/context-manager/context-permissions/context-permissions.component.ts
- packages/context/src/lib/context-manager/shared/context.service.ts
- packages/context/src/lib/context-map-button/bookmark-button/bookmark-button.component.ts
- packages/geo/src/lib/overlay/shared/overlay.utils.ts
- keep current context on authentification
- go on new context when one is created
- context permissions refresh on edit permissions
- last change is only a lint error fix
> fix(context): fix some problems with context updates

- packages/common/src/lib/list/list.component.scss
- packages/geo/src/lib/catalog/catalog-browser/catalog-browser-group.component.html
- packages/geo/src/lib/catalog/catalog-browser/catalog-browser-group.component.scss
- packages/geo/src/lib/search/search-results/search-results.component.html
Accentuate catalog group title and search results title (for query and results from search bar)
issue igo2-lib#346
> accentuate / emphasize on catalog group title and search results title

- packages/geo/src/public_api.ts
Error in igo2 build process.
```
[ ] Yes
[x] No
```
> refactor(cadastre) export the cadastre provider into the geo public_api

- packages/geo/src/lib/filter/shared/spatial-filter.service.ts
- packages/geo/src/lib/filter/spatial-filter/spatial-filter-item/spatial-filter-item.component.html
- packages/geo/src/lib/filter/spatial-filter/spatial-filter-item/spatial-filter-item.component.scss
- Missing traduction error catch for terrapi thematics
- CSS search title update
> fix(spatialFilter): missing traduction fix / CSS title update

- package-lock.json
- packages/auth/src/lib/auth-form/auth-form.component.ts
- packages/auth/src/lib/shared/auth.service.ts
- packages/auth/src/lib/shared/profils.guard.ts
- packages/auth/src/lib/shared/token.service.ts
- packages/context/src/lib/context-manager/shared/context.service.ts
- packages/core/src/lib/analytics/shared/analytics.service.ts
- packages/geo/src/lib/catalog/shared/catalog.interface.ts
- packages/geo/src/lib/filter/shared/spatial-filter.service.ts
- packages/integration/src/lib/analytics/analytics-listener.service.ts
- packages/integration/src/lib/analytics/analytics.module.ts
- packages/integration/src/lib/analytics/index.ts
- packages/integration/src/lib/integration.module.ts
- packages/integration/src/public_api.ts
> feat(analytics): track events

- packages/geo/src/lib/overlay/shared/overlay.utils.ts
Overlay - add width property to stroke
Overlay - fix offset between pin and real position
```
[ ] Yes
[x] No
```
> Overlay Stroke width

- demo/src/app/geo/search/search.component.html
- demo/src/app/geo/search/search.component.ts
- packages/common/src/lib/collapsible/collapsible.component.html
- packages/common/src/lib/collapsible/collapsible.component.ts
- packages/geo/src/lib/search/search-bar/search-bar.component.ts
- packages/geo/src/lib/search/search-results/search-results.component.html
- packages/geo/src/lib/search/search-results/search-results.component.ts
- packages/geo/src/lib/search/shared/sources/icherche.ts
- packages/geo/src/lib/search/shared/sources/ilayer.ts
- packages/integration/src/lib/search/search-results-tool/search-results-tool.component.html
- packages/integration/src/lib/search/search-results-tool/search-results-tool.component.ts
- packages/integration/src/lib/search/search.state.ts
- Fix page 10 error
- manage search settings change
- manage igo-collapsible on search
> fix(search-results): display more results fix

- packages/geo/src/lib/search/search-results/search-results.component.html
Manage collapsible state with group title
> fix(toast-panel): get feature info collapsible fix

- packages/geo/src/lib/datasource/shared/datasources/wfs-datasource.ts
- packages/geo/src/lib/download/shared/download.service.ts
- packages/geo/src/lib/feature/shared/feature.utils.ts
- packages/geo/src/lib/filter/ogc-filter-form/ogc-filter-form.component.ts
- packages/geo/src/lib/filter/ogc-filterable-item/ogc-filterable-item.component.ts
- packages/geo/src/lib/filter/shared/ogc-filter.service.ts
- packages/geo/src/lib/filter/shared/ogc-filter.ts
- packages/geo/src/lib/filter/spatial-filter/spatial-filter-item/spatial-filter-item.component.ts
- packages/geo/src/lib/map/shared/map.ts
- packages/geo/src/lib/print/shared/print.service.ts
- packages/geo/src/lib/wkt/shared/wkt.service.ts
> Remove hardcoded EPSG

- packages/geo/src/lib/directions/directions-form/directions-form.component.ts
1- term change was not subscribed
2- Added layer (route and stop) not always visible on map
1- Term change subscription
2- Fix adding layer to map synchronization
```
[ ] Yes
[x ] No
```
> Directions term change

- packages/auth/ng-package.json
- packages/auth/ng-package.prod.json
- packages/auth/package.json
- packages/geo/ng-package.json
- packages/geo/ng-package.prod.json
- packages/geo/package.json
- packages/geo/src/lib/datasource/shared/capabilities.service.ts
- packages/geo/src/lib/datasource/shared/datasource.service.ts
- packages/geo/src/locale/en.geo.json
- packages/geo/src/locale/fr.geo.json
If only one layer is in error in the context, the entire context is not accessible.
Returns a message indicating which layer is in error.
The other layers will still be added.
```
[ ] Yes
[x ] No
```
> fix(datasource): improve error handling

- demo/src/app/geo/search/search.component.html
- x ] The commit message follows our guidelines:https://github.com/infra-geo-ouverte/igo2/blob/master/.github/CONTRIBUTING.md#git-commit-guidelines
Refer to https://github.com/infra-geo-ouverte/igo2/issues/422
Fix https://github.com/infra-geo-ouverte/igo2/issues/422
```
[ ] Yes
[x] No
```
> On uncheck, last checked source stay in search-results

- packages/auth/src/locale/en.auth.json
- packages/geo/src/lib/import-export/import-export/import-export.component.html
- packages/geo/src/lib/import-export/import-export/import-export.component.ts
- packages/geo/src/lib/import-export/shared/drop-geo-file.directive.ts
- packages/geo/src/lib/import-export/shared/import.interface.ts
- packages/geo/src/lib/import-export/shared/import.service.ts
- packages/geo/src/lib/import-export/shared/import.utils.ts
- packages/geo/src/locale/en.geo.json
- packages/geo/src/locale/fr.geo.json
The file size is limited to 30 mb (approx).
Set this limit configurable.
```
[ ] Yes
[x] No
```
> Configurable file size on import

- packages/geo/src/lib/search/shared/search-pointer-summary.directive.ts
Fix #606 
```
[ ] Yes
[x] No
```
> Fix pointer summary

- packages/geo/src/lib/catalog/shared/catalog.service.ts
- packages/geo/src/lib/feature/feature-details/feature-details.component.html
- packages/geo/src/lib/feature/feature-details/feature-details.component.ts
- packages/geo/src/lib/search/shared/sources/ilayer.ts
- fix htmlgml2 target (iframe)
> fix(queryFormat): fix layer's queryFormat htmlgml2

- packages/geo/src/lib/filter/filter.module.ts
- packages/geo/src/lib/filter/time-filter-form/time-filter-form.component.scss
- packages/geo/src/lib/filter/time-filter-form/time-filter-form.component.ts
- packages/geo/src/lib/filter/time-filter-form/time-filter-form.theming.scss
- Fix UTC time vs local time bug
- Switch language to french
- Apply focus style on selected date
> fix(time-filter): fix UTC time, language and style on selected date

- packages/geo/src/lib/import-export/shared/export.service.ts
- packages/geo/src/lib/layer/layer-list/layer-list.component.ts
- packages/geo/src/lib/map/shared/map.ts
- Fix firefox export (lost format extension)
- Fix selection mode with baselayers
- Overflow move with raise/lower layer if not into view
> fix(layer-list / export): Fix 1.3 release

- packages/geo/src/lib/layer/layer-list/layer-list.component.html
- packages/geo/src/lib/layer/layer-list/layer-list.component.scss
- packages/geo/src/lib/layer/layer-list/layer-list.component.ts
- packages/geo/src/lib/layer/layer.theming.scss
- fix problem the slider close on clic on slider
- add more shadow-box on mat-menu to make slider more visible on ui
- fix problem with value 55.0000001 add round on it
IGO2 # 457
https://github.com/infra-geo-ouverte/igo2/issues/457
- [x ] No
> fix(layer-list) opacity slider: don't close on clic, scss+, fix probleme dec. value 55.0001

- packages/geo/src/lib/filter/spatial-filter/spatial-filter-item/spatial-filter-item.component.html
- packages/geo/src/lib/filter/spatial-filter/spatial-filter-item/spatial-filter-item.component.scss
- packages/geo/src/lib/filter/spatial-filter/spatial-filter-item/spatial-filter-item.component.ts
- packages/geo/src/lib/import-export/import-export/import-export.component.ts
- packages/geo/src/locale/en.geo.json
- packages/geo/src/locale/fr.geo.json
- packages/integration/src/lib/filter/spatial-filter-tool/spatial-filter-tool.component.html
- packages/integration/src/lib/filter/spatial-filter-tool/spatial-filter-tool.component.ts
- Link spatial-filter to export tool tab using the import-export-state
> feat(spatial-filter): link spatial filter to export tool

- packages/geo/src/lib/import-export/import-export/import-export.component.html
- packages/geo/src/lib/import-export/import-export/import-export.component.ts
- packages/geo/src/lib/import-export/shared/export.service.ts
- packages/geo/src/lib/import-export/shared/export.type.ts
- packages/geo/src/locale/en.geo.json
- packages/geo/src/locale/fr.geo.json
- Allow the user to export file in CSV semicolon delimiter format (can be opened correctly in excel default parameter)
> feat(export): Allow the CSV semicolon delimiter export format

- packages/auth/src/lib/shared/auth.service.ts
- packages/common/src/lib/action/actionbar/actionbar.component.html
- packages/common/src/lib/action/actionbar/actionbar.component.ts
- packages/context/src/lib/context-manager/context-item/context-item.component.html
- packages/context/src/lib/context-manager/context-item/context-item.component.ts
- packages/context/src/lib/context-manager/context-list/context-list-binding.directive.ts
- packages/context/src/lib/context-manager/context-list/context-list.component.html
- packages/context/src/lib/context-manager/context-list/context-list.component.scss
- packages/context/src/lib/context-manager/context-list/context-list.component.ts
- packages/context/src/lib/context-manager/context-manager.module.ts
- packages/context/src/lib/context-manager/context-permissions/context-permissions.component.html
- packages/context/src/lib/context-manager/context-permissions/context-permissions.component.scss
- packages/context/src/lib/context-manager/context-permissions/context-permissions.component.ts
- packages/context/src/lib/context-manager/shared/context.interface.ts
- packages/context/src/lib/context-manager/shared/context.service.ts
- packages/context/src/lib/context.module.ts
- packages/context/src/locale/en.context.json
- packages/context/src/locale/fr.context.json
- Allow the user to filter context list by profil/user/GRAPP
- Add autocomplete on the add permissions action
> feat(context): filter context by user + autocomplete on permissions adding

- packages/context/src/lib/share-map/shared/share-map.service.ts
- packages/core/src/lib/route/route.interface.ts
- packages/core/src/lib/route/route.service.ts
- packages/geo/src/lib/datasource/shared/capabilities.service.ts
- packages/geo/src/lib/datasource/shared/datasources/wmts-datasource.interface.ts
- there are no title display on map for the wmts
- the wmts isn't shared on copy link
- The wmts title display on map
- The wmts is added to url on share copy link
refer to issues #669, #670
> * (feat): Add title on map and copy link for WMTS

- packages/integration/src/lib/search/search-results-tool/search-results-tool.component.ts
- Remove previous search-result selection when a new search-result is selected
> fix(search-results): remove previous selection with new selection

- packages/geo/src/lib/import-export/import-export/import-export.component.html
- packages/geo/src/locale/en.geo.json
- packages/geo/src/locale/fr.geo.json
- Add translation for URL format
- Fix disabled export button when layer is removed from the map tool
> fix(export): URL translation and layer remove from map

- packages/geo/src/lib/filter/spatial-filter/spatial-filter-item/spatial-filter-item.component.ts
- packages/geo/src/lib/geometry/geometry-form-field/geometry-form-field-input.component.ts
- Fix spatial filter freehand circle drawing style (was disappearing with new ol version)
> fix(spatial-filter): fix spatial filter freehand circle style

- packages/geo/src/lib/import-export/import-export/import-export.component.html
- packages/geo/src/lib/import-export/import-export/import-export.component.ts
- packages/geo/src/locale/en.geo.json
- packages/geo/src/locale/fr.geo.json
- packages/integration/src/lib/filter/spatial-filter-tool/spatial-filter-tool.component.ts
- packages/integration/src/lib/import-export/import-export-tool/import-export-tool.component.html
- packages/integration/src/lib/import-export/import-export-tool/import-export-tool.component.ts
- packages/integration/src/lib/import-export/import-export.state.ts
- packages/integration/src/lib/map/map-details-tool/map-details-tool.component.ts
- packages/integration/src/lib/map/map-tool/map-tool.component.ts
- packages/integration/src/lib/map/map-tools/map-tools.component.ts
- Fix translate item from terrapi
- Pre select layers when export results is active
- Pre select export mode
> fix(spatial-filter): fix spatial filter 1.4

- packages/common/src/lib/entity/entity-table/entity-table.component.html
- packages/common/src/lib/entity/entity-table/entity-table.component.ts
- packages/common/src/lib/entity/shared/transaction.ts
- packages/common/src/lib/form/shared/form.utils.ts
- packages/geo/src/lib/feature/shared/strategies/loading.ts
- packages/geo/src/lib/feature/shared/strategies/selection.ts
- packages/geo/src/lib/geometry/geometry-form-field/geometry-form-field-input.component.ts
- packages/geo/src/lib/geometry/geometry-form-field/geometry-form-field.component.html
- packages/geo/src/lib/geometry/geometry-form-field/geometry-form-field.component.ts
- packages/geo/src/lib/geometry/shared/controls/draw.ts
- packages/geo/src/lib/geometry/shared/controls/modify.ts
- packages/geo/src/lib/geometry/shared/controls/slice.ts
- packages/geo/src/lib/layer/layer-list/layer-list-binding.directive.ts
- packages/geo/src/lib/layer/shared/layers/layer.interface.ts
- packages/geo/src/lib/layer/shared/layers/layer.ts
- packages/geo/src/lib/map/shared/map.ts
This PR contains a bunch of small self-contained commits that are mostly fixes. Wven features are quite simple too.
> Fadq 1.4.2

- packages/common/src/lib/interactive-tour/interactive-tour.component.scss
- packages/common/src/lib/interactive-tour/interactive-tour.service.ts
- CSS fix for interactive tour steps
> fix(interactive-tour): css fix for interactive tour

- packages/geo/src/lib/filter/ogc-filter-toggle-button/ogc-filter-toggle-button.component.ts
- packages/geo/src/lib/filter/ogc-filterable-item/ogc-filterable-item.component.ts
- packages/geo/src/lib/layer/shared/layer.service.ts
- packages/geo/src/lib/layer/shared/layers/image-layer.ts
- packages/geo/src/lib/layer/shared/layers/vector-layer.ts
- packages/geo/src/lib/layer/shared/layers/vectortile-layer.ts
Vector/vectortile are not intercepted by the auth interceptor
add authInterceptor for vector and vectortile layers.
> Add authInterceptor for vector and vectortile layers

- packages/geo/src/lib/catalog/catalog-browser/catalog-browser-layer.component.ts
- packages/geo/src/lib/search/search-results/search-results-add-button.component.ts
https://github.com/infra-geo-ouverte/igo2/issues/508
The add button not always trigger the layer addition.
Fix it. 
> preview conflict with layer add (1st attempt to fix)

- packages/common/src/lib/interactive-tour/interactive-tour.service.ts
- Skip step and remove that step when element attach to is not found
- Add mat-typography class to all shepherd step
> Fix interactive tour

- packages/geo/src/lib/import-export/import-export/import-export.component.ts
- packages/geo/src/lib/query/shared/query.service.ts
The next branch crash when exporting a single layer from a context with a single vector layer....
Fix.
> Export fix crash with context containing 1 vector layer

- packages/common/src/lib/interactive-tour/interactive-tour.service.ts
- Element attach to must be define in the step to enter the missing element condition
- If enter the missing condition, do not skip to next element if the next element is the last of the tour
> fix(interactive-tour): fix missing element condition

- packages/geo/src/lib/layer/layer-legend-item/layer-legend-item.component.ts
- packages/geo/src/lib/layer/layer-legend/layer-legend.component.ts
- Many legend doesn't appear
- [#517](https://github.com/infra-geo-ouverte/igo2/issues/517)
- [x ] No
> Fix(legend)- legend close on return in map(#517) +show many legend

- packages/geo/src/lib/import-export/import-export/import-export.component.html
- packages/geo/src/lib/import-export/import-export/import-export.component.ts
- packages/geo/src/locale/en.geo.json
- packages/geo/src/locale/fr.geo.json
when opening multiple url, you browser block the popup.
Add a message for multiple url blocked by browser.
> Add a message for multiple url blocked by browser.

- packages/geo/src/lib/feature/feature-details/feature-details.directive.ts
- packages/geo/src/lib/search/shared/sources/cadastre.providers.ts
- packages/geo/src/lib/search/shared/sources/cadastre.ts
- packages/geo/src/lib/search/shared/sources/coordinates.ts
- packages/geo/src/lib/search/shared/sources/storedqueries.providers.ts
- packages/geo/src/lib/search/shared/sources/storedqueries.ts
Search source not containing the routing span crash. 
Add the routing properties to every search sources (except for nominatim) and add a clause to ensure there is no fail on feature results.
> Routing feature

- packages/common/src/lib/interactive-tour/interactive-tour.component.html
- packages/common/src/lib/interactive-tour/interactive-tour.component.ts
- packages/common/src/lib/interactive-tour/interactive-tour.service.ts
- packages/integration/src/lib/about/about-tool/about-tool.component.html
- packages/integration/src/lib/about/about-tool/about-tool.component.ts
The app title for Discover IGO is not customizable.
Now it is. 
> Discover IGO - Customizable title

- packages/integration/src/lib/search/search-results-tool/search-results-tool.component.ts
- packages/integration/src/lib/search/search.state.ts
- Add the selected result as a property of the search state
- Allow to be accessible from the search state
> feat(search-state): add selected result property

- packages/geo/src/lib/feature/feature-details/feature-details.component.html
- packages/geo/src/lib/feature/feature-details/feature-details.component.ts
- delete route property from feature details if directions tool not defined in the toolbox
> Feature routing fix

- packages/geo/src/lib/import-export/shared/export.type.ts
- packages/geo/src/lib/search/shared/sources/icherche.ts
- packages/geo/src/locale/en.geo.json
- packages/geo/src/locale/fr.geo.json
Into the import/export, renaming the URL by external link
> import/export, renaming the URL by external link

- packages/integration/src/lib/about/about-tool/about-tool.component.ts
When trying to customize the title of the tour button, in the about tool, an error was raised and the title was not correct.
Fix it.
> fix(about-tool) configurable title for the general tour

- packages/common/src/lib/interactive-tour/interactive-tour.component.scss
- Change font-size for shepherd-text, font-weight for shepherd-title
- Add border and box-shadow for poppers
> ui(interactive-tour): change style for poppers

- packages/geo/src/lib/feature/shared/strategies/in-map-extent.ts
- packages/integration/src/lib/search/search-results-tool/search-results-tool.component.ts
Fix a undefined map coming from the spatial-filter tool.
> In map extent - store.layer.map was undefined.

- packages/geo/src/lib/import-export/export-button/export-button.component.ts
> Non exportable layer do not show the export button. 

- packages/common/src/lib/image/secure-image.pipe.ts
- packages/geo/src/lib/print/print/print.component.ts
- packages/geo/src/lib/print/shared/print.service.ts
- Fix print-tool legend icon that doesn't appear with secure layer
> Print legend icon

- packages/integration/src/lib/filter/spatial-filter-tool/spatial-filter-tool.component.ts
- packages/integration/src/lib/import-export/import-export-tool/import-export-tool.component.html
- packages/integration/src/lib/import-export/import-export-tool/import-export-tool.component.ts
- packages/integration/src/lib/import-export/import-export.state.ts
- packages/integration/src/lib/map/map-details-tool/map-details-tool.component.ts
- packages/integration/src/lib/map/map-tool/map-tool.component.ts
- packages/integration/src/lib/map/map-tools/map-tools.component.ts
- packages/integration/src/lib/tool/tool.state.ts
> feat(import-export) allow to control if both importExport types (layer and context) are shown

- packages/geo/src/lib/import-export/import-export/import-export.component.html
- packages/geo/src/lib/import-export/import-export/import-export.component.ts
- packages/geo/src/lib/import-export/import-export/import-export.interface.ts
- packages/geo/src/lib/import-export/import-export/index.ts
- packages/geo/src/lib/import-export/index.ts
- packages/geo/src/locale/en.geo.json
- packages/geo/src/locale/fr.geo.json
- packages/integration/src/lib/import-export/import-export-tool/import-export-tool.component.html
- packages/integration/src/lib/import-export/import-export-tool/import-export-tool.component.ts
User must know the EPSG code for the imported source. 
Provide an user friendly list for input projections based on handled projection of the app. 
@mbarbeau test with the ogre import service. 
> feat(import-export) provide an user friendly list for input projections

- packages/geo/src/lib/datasource/shared/datasource.service.ts
- packages/geo/src/lib/datasource/shared/datasources/any-datasource.interface.ts
- packages/geo/src/lib/datasource/shared/datasources/any-datasource.ts
- packages/geo/src/lib/datasource/shared/datasources/datasource.interface.ts
- packages/geo/src/lib/datasource/shared/datasources/index.ts
- packages/geo/src/lib/datasource/shared/datasources/tiledebug-datasource.interface.ts
- packages/geo/src/lib/datasource/shared/datasources/tiledebug-datasource.ts
- packages/geo/src/lib/layer/shared/layer.service.ts
- packages/geo/src/lib/layer/shared/layers/tile-layer.interface.ts
- packages/geo/src/lib/layer/shared/layers/tile-layer.ts
- packages/geo/src/lib/utils/id-generator.ts
Add a layer type form https://openlayers.org/en/latest/apidoc/module-ol_source_TileDebug-TileDebug.html
> feat(datasource) add a layer type tiledebug for tile debugging

- packages/geo/src/lib/datasource/shared/datasources/wfs-datasource.ts
- packages/geo/src/lib/datasource/shared/datasources/wms-datasource.ts
- packages/geo/src/lib/layer/utils/layerSync-watcher.ts
- packages/geo/src/lib/workspace/shared/wms-workspace.service.ts
WMS workspace with a different url for wms-wfs is not correctly assigned.
Fix it + retrieve source field simple optimization.
> Minor fix workspace

- packages/geo/src/lib/print/shared/print.service.ts
- There was a bug with printing to PDF with tablet, mobile and some laptop screen.
- Canvases were split and not added correctly to the file
> fix(print-tool): fix small screen layers print

- packages/geo/src/lib/datasource/shared/capabilities.service.ts
- packages/geo/src/lib/layer/shared/layers/vector-layer.ts
- packages/geo/src/lib/layer/shared/layers/vectortile-layer.ts
- Fix xhr request interception when custom loader is call (it was missing url parameter)
> fix(intercept): add url to xhr request interception

- packages/geo/src/lib/filter/shared/spatial-filter.service.ts
- packages/geo/src/lib/filter/spatial-filter/spatial-filter-item/spatial-filter-item.component.scss
- packages/integration/src/lib/filter/spatial-filter-tool/spatial-filter-tool.component.ts
- Fix Point zone adding
- Fix buffer Input parameter sending
> fix(spatial-filter): fix radius and buffer sending

- packages/geo/src/locale/en.geo.json
- packages/geo/src/locale/fr.geo.json
Enhance import clarifications.
> i18n(import-export) enhance the imports clarifications

- .github/workflows/codeql-analysis.yml
> chore(code-analysis): Create codeql-analysis.yml

- packages/geo/src/lib/layer/layer-list/layer-list.component.html
- packages/geo/src/lib/layer/layer-list/layer-list.component.ts
Layer opacity change when releasing the slider.
Apply the opacity change when sliding the slider
https://github.com/infra-geo-ouverte/igo2/issues/465
> feat(layer-list) bind slider change to opacity

- packages/geo/src/lib/catalog/shared/catalog.interface.ts
- Add forced properties attribute to ICatalog (was only part of Catalog, so it creates problem when defining catalogs)
> add ICatalog forced properties attribute

- packages/context/src/lib/share-map/shared/share-map.service.ts
URL containing ? cause an lost of the following content in the url .. some layer are not shared.
Encode url. 
> Share map url encoding (wmsUrl and wmtsUrl)

- packages/geo/src/lib/catalog/shared/catalog.service.ts
- packages/geo/src/lib/datasource/shared/datasources/arcgisrest-datasource.ts
- packages/geo/src/lib/datasource/shared/datasources/tilearcgisrest-datasource.ts
1- group were shown as layer
2- undefined layer on getlegend
3- title duplicate in legend
fix it.
> Esri rest fix

- packages/geo/src/lib/print/shared/print.service.ts
> fix(print): subtitle newline image format fix

- packages/geo/ng-package.json
- packages/geo/ng-package.prod.json
- packages/geo/src/lib/catalog/shared/catalog.abstract.ts
- packages/geo/src/lib/catalog/shared/catalog.enum.ts
- packages/geo/src/lib/catalog/shared/catalog.service.ts
- packages/geo/src/lib/datasource/shared/capabilities.service.ts
- packages/geo/src/lib/datasource/shared/datasource.service.ts
- packages/geo/src/lib/datasource/shared/datasources/any-datasource.interface.ts
- packages/geo/src/lib/datasource/shared/datasources/any-datasource.ts
- packages/geo/src/lib/datasource/shared/datasources/datasource.interface.ts
- packages/geo/src/lib/datasource/shared/datasources/imagearcgisrest-datasource.interface.ts
- packages/geo/src/lib/datasource/shared/datasources/imagearcgisrest-datasource.ts
- packages/geo/src/lib/datasource/shared/datasources/index.ts
- packages/geo/src/lib/layer/shared/layer.service.ts
- packages/geo/src/lib/layer/shared/layers/image-layer.interface.ts
- packages/geo/src/lib/layer/shared/layers/image-layer.ts
- packages/geo/src/lib/query/shared/query.service.ts
- packages/geo/src/lib/utils/id-generator.ts
- packages/geo/src/lib/workspace/shared/wms-workspace.service.ts
1-Add an datasource for esri image source.  (imagearcgisrest)
2-Catalog were adding arcgisrest despite the type of catalog. tilearcgisrest catalog was adding arcgisrest.
3- No scale provided for layer but available in layer capacities
4- No soucefields provided but available in layer capacities
5-  No querytitle provided but available in layer capacities
Add these features
> Esri image

- packages/context/src/lib/share-map/shared/share-map.service.ts
- packages/core/src/lib/route/route.interface.ts
- packages/core/src/lib/route/route.service.ts
Only WMS and WMTS are shareable by url
Add ArcGis Rest, Image ArcGis Rest and TIle ArcGis Rest can now be shared by url. 
> Share arcgis

- packages/geo/src/lib/filter/time-filter-form/time-filter-form.component.ts
Time animation, a slider for a year type was exceeding the max value
> fix(time-filter) year slider animation

- packages/geo/src/lib/catalog/shared/catalog.service.ts
- packages/geo/src/lib/datasource/shared/datasources/imagearcgisrest-datasource.interface.ts
- packages/geo/src/lib/datasource/shared/datasources/imagearcgisrest-datasource.ts
- Fix legend info options for imagearcgisrest layer
- Fix forced title for arcgisrest layer
*Probably a temporary fix, to be continued...*
> fix(arcgisREST): fix forced title and legend for arcgis layer

- package.json
- packages/geo/src/lib/import-export/shared/drop-geo-file.directive.ts
Crash on geojson without crs property
> fix(drag-drop) missing crs property

- packages/context/src/lib/share-map/share-map/share-map.component.ts
If the baselayer is changed, the url was not updated.
update url if the baselayer is changed
> fix(shareMap): update url if the baselayer is changed

- packages/core/src/lib/message/shared/message.interface.ts
- packages/core/src/lib/message/shared/message.service.ts
The message has no date range.
feat(message): add an optional date range to message application
> add an optional date range to message application

- packages/common/src/lib/image/secure-image.pipe.ts
- packages/geo/src/lib/catalog/catalog-library/add-catalog-dialog.component.ts
- packages/geo/src/lib/print/shared/print.service.ts
> Various fix

- packages/geo/src/lib/directions/directions-form/directions-form.component.ts
> fix(directions): marker was not correctly selected.

- packages/geo/src/lib/filter/ogc-filter-selection/ogc-filter-selection.component.scss
- Add auto height for push buttons (allow multiple lines title)
> fix(ogcFilter): css fix for pushButtons title

- packages/geo/src/lib/directions/directions-form/directions-form.component.ts
- packages/geo/src/lib/draw/shared/draw-icon.service.ts
- packages/geo/src/locale/en.geo.json
- packages/geo/src/locale/fr.geo.json
- packages/integration/src/lib/directions/directions-tool/directions-tool.component.html
- packages/integration/src/lib/directions/directions-tool/directions-tool.component.ts
- packages/integration/src/lib/directions/directions.state.ts
The directions geometries are not printable.
The directions geometries are now printable.
TODO, print the directions as text. The directionState store the activeRoute text.
> Print directions

- packages/geo/src/lib/search/shared/search.utils.ts
> computeTermSimilarity is now not case sensitive

- packages/geo/src/lib/filter/ogc-filterable-item/ogc-filterable-item.component.html
- packages/geo/src/lib/search/shared/search.utils.ts
- packages/geo/src/lib/workspace/shared/wms-workspace.service.ts
Advanced ogcfilters could not be used.
Issue when adding the same layer twice (workspace)
Fix.
> fix(ogcfilters)

- packages/geo/src/lib/catalog/catalog-library/catalog-library.component.ts
Predefined catalog options were not used correctly
Use them
> fix(catalog): predefined catalog options were not used correctly

- packages/geo/src/lib/directions/directions-form/directions-form-binding.directive.ts
- packages/geo/src/lib/directions/directions-form/directions-form.component.ts
Difficult to move stops because the zoom auto on new route calculation
Disable auto-zoom
> fix(directions): auto zoom on new stop/route

- packages/geo/src/lib/datasource/shared/datasources/wms-datasource.ts
Related to https://github.com/openlayers/openlayers/issues/7790
> Wms optimize

- packages/geo/src/lib/datasource/shared/datasource.service.ts
- packages/geo/src/lib/import-export/import-export/import-export.component.ts
- packages/geo/src/lib/map/shared/map.utils.ts
1- inverted EPSG code for 4326-4269 in import export menu :( (shame)
2- Esri service properties were note retrieved
Fix it
> Various fix (ESRI layer + inverted epsg codes for import)

- packages/core/src/style/themes/teal.theme.scss
> fix (teal-theme)

- demo/src/styles.scss
- packages/core/src/style/themes/bluedq.theme.scss
feat(style/theme): add new theme call bluedq
> feat(style/theme): add new theme call bluedq

- package.json
- packages/geo/src/lib/layer/layer-legend-list/layer-legend-list.component.html
- packages/geo/src/lib/layer/layer-legend-list/layer-legend-list.component.scss
- packages/integration/src/lib/map/map-tools/map-tools.component.scss
list of legends is not scrollable
list of legends is scrollable
- [x ] No
> fix(map): Legend scroll bug fix

- packages/integration/src/lib/about/about-tool/about-tool.component.html
- packages/integration/src/lib/about/about-tool/about-tool.component.ts
html header was placed between various feature in the ui
Place it a the right place. 
> About header html - fix placement

- gulpfile.js
- packages/core/src/style/partial/core.variables.scss
- packages/geo/src/lib/map/index.ts
- packages/geo/src/lib/map/map.module.ts
- packages/geo/src/lib/map/map.theming.scss
- packages/geo/src/lib/map/menu-button/index.ts
- packages/geo/src/lib/map/menu-button/menu-button.component.html
- packages/geo/src/lib/map/menu-button/menu-button.component.scss
- packages/geo/src/lib/map/menu-button/menu-button.component.ts
- packages/geo/src/lib/map/menu-button/menu-button.theming.scss
- Menu button was implemented in the assembly (igo2). 
- With new sass package 1.9.0 release, themings are handled differently
- Menu button component is now implemented in lib to adjust correctly with the new theming structure
> refactor(menu-button): add igo menu button to lib (adjust style)

- demo/src/app/geo/directions/directions.component.ts
- packages/geo/src/lib/directions/directions-buttons/directions-buttons.component.ts
- packages/geo/src/lib/directions/directions-inputs/directions-inputs.component.html
- packages/geo/src/lib/directions/directions-inputs/directions-inputs.component.ts
- packages/geo/src/lib/directions/directions-sources/osrm-directions-source.ts
- packages/geo/src/lib/directions/directions.component.ts
- packages/geo/src/lib/directions/shared/directions.enum.ts
- packages/geo/src/lib/directions/shared/directions.interface.ts
- packages/geo/src/lib/directions/shared/directions.utils.ts
- packages/geo/src/locale/fr.geo.json
- packages/integration/src/locale/en.integration.json
- packages/integration/src/locale/fr.integration.json
> fix(directions): observable management on search

- packages/context/src/lib/share-map/shared/share-map.service.ts
- packages/geo/src/lib/catalog/catalog-library/add-catalog-dialog.component.html
- packages/geo/src/lib/catalog/catalog-library/add-catalog-dialog.component.ts
- packages/geo/src/lib/catalog/catalog-library/catalog-library.component.ts
The way to add catalog do not allow the user to select within a list of titles.
Provide a way to select a catalog to add by title. 
> Add catalog

- demo/src/app/geo/query/query.component.ts
- packages/geo/src/lib/query/shared/query.interfaces.ts
- packages/geo/src/lib/query/shared/query.utils.ts
Query on an imported layer don't work.
Query work.
- [] No
variable change name:  queryFeature -> queryLayerFeatures
> fix(query) query on an imported layer

- packages/geo/src/lib/datasource/shared/capabilities.service.ts
> fix(arcgis layer): attribution cause crash on add layer.

- packages/integration/src/lib/map/advanced-map-tool/advanced-coordinates/advanced-coordinates.component.html
- packages/integration/src/lib/map/advanced-map-tool/advanced-coordinates/advanced-coordinates.component.ts
- packages/integration/src/locale/en.integration.json
- packages/integration/src/locale/fr.integration.json
It is hard to access the map's scale and resolution
Provide a way to see the scale and resolution. 
> feat(advanced-coordinates): add the map's scale and resolution to the tool

- packages/core/src/lib/message/shared/message.service.ts
- packages/core/src/locale/en.core.json
- packages/core/src/locale/fr.core.json
Message without title crash. 
Message based on translation need a key as title
> Message based on translation need a key as title

- .github/workflows/complete.js.yml
- .github/workflows/onPush-ci.js.yml
> chore(githubaction): less action triggered for next branch.

- demo/src/app/geo/draw/draw.component.ts
- [ X] The commit message follows our guidelines:https://github.com/infra-geo-ouverte/igo2/blob/master/.github/CONTRIBUTING.md#git-commit-guidelines
"error: ERROR TypeError: Cannot read property 'projection' of undefined" when adding geometry to drawing layer
- [X ] No
> fix (Demo):assign map in demo draw component

- demo/src/app/geo/simple-map/simple-map.component.html
- packages/geo/src/lib/map/index.ts
- packages/geo/src/lib/map/info-section/index.ts
- packages/geo/src/lib/map/info-section/info-section.component.html
- packages/geo/src/lib/map/info-section/info-section.component.scss
- packages/geo/src/lib/map/info-section/info-section.component.ts
- packages/geo/src/lib/map/map.module.ts
New feature
Provide a component for show generic content on the map... coord could be used.. or anything...
You could check the simple map demo into the lib.  This infoSection is in gray.
> feat(geo): info content on map

- README.md
> chore(readme): readme with gitter badge

- packages/auth/src/lib/auth-form/auth-intern.component.html
- [] Tests for the changes have been added (for bug fixes / features)
- [] Docs have been added / updated (for bug fixes / features)
Second pull request (to branch next)
Allow to fix disable login button when auto generate field from auth component
> fix(auth): Fix disabled login button with autocomplete form

- packages/geo/src/lib/geometry/shared/controls/draw.ts
- packages/geo/src/lib/geometry/shared/controls/modify.ts
- packages/geo/src/lib/geometry/shared/controls/slice.ts
Some controls have their style properties wrongly typed.
They are properly typed by using the StyleLike type provided by OL.
> fix(typing): Fix typing issues in geometry controls

- packages/core/src/lib/message/shared/message.service.ts
See https://github.com/infra-geo-ouverte/igo2-lib/issues/1004
Fix the issue with toastr not being able to attach itself to the app when it is loaded during app initialization.
> fix: Circular dependency with toastr

- packages/geo/src/lib/directions/directions-buttons/directions-buttons.component.ts
- packages/geo/src/lib/directions/directions.component.html
- packages/geo/src/lib/directions/directions.component.ts
- packages/integration/src/lib/directions/directions-tool/directions-tool.component.html
- packages/integration/src/lib/directions/directions-tool/directions-tool.component.ts
When sharing direction by url. The current context is not transfered. 
Pass context to shared url. 
> Keep current context open on direction url share url. 

- packages/geo/src/lib/search/search-bar/search-bar.component.ts
When the search bar's store is null, attempting to clear it fails.
The store is cleared only if the store exists.
> fix(search bar): fix an issue with the search bar when the store is null

- package-lock.json
- package.json
Reverts infra-geo-ouverte/igo2-lib#1002
> Revert "chore(deps-dev): bump karma from 6.3.4 to 6.3.16"

- packages/integration/src/lib/about/about-tool/about-tool.component.ts
> fix(about): fix depot url

- packages/geo/src/lib/search/shared/sources/source.ts
Caps lock hashtags are not being included in icherche source
Caps lock hashtags are now being convert to lower case and included in icherche source
> fix(icherche): fix icherche hashtags caps lock comparison

- packages/geo/src/lib/layer/layer-legend/layer-legend.component.ts
Certaines légendes ne s'affichent plus (notamment avec optionsFromApi)
Les légendes provenant de optionsFromApi s'affichent
> fix(layer-legend): fix layer-legend display

- packages/geo/src/lib/layer/utils/layerSync-watcher.ts
fix https://github.com/infra-geo-ouverte/igo2-lib/issues/1024
> fix(layerSync): error on time property transfer

- packages/geo/src/lib/layer/utils/layerSync-watcher.ts
Reverts infra-geo-ouverte/igo2-lib#1027
> Revert "feat(layerSync): prevent refresh of linked layer if applied OGC filters are the same"

- packages/common/src/lib/entity/entity-table/entity-table.component.scss
feat(entity-table): add css class to hide content
> feat(entity-table): add css class to hide content

- packages/context/src/lib/context-import-export/shared/context-import.utils.ts
- packages/geo/src/lib/import-export/shared/import.utils.ts
fix(import): imported layers are disabled when offline
> fix(import): imported layers are disabled when offline

- packages/geo/src/lib/search/shared/sources/source.ts
+ character aren't read for icherche hashtags research
+ character is read for icherche hashtags research
> feat(icherche): allow + hashtags to be read

- packages/geo/src/lib/layer/layer-item/layer-item.component.html
- packages/geo/src/lib/layer/layer-item/layer-item.component.ts
- packages/geo/src/locale/en.geo.json
- packages/geo/src/locale/fr.geo.json
No translate for disabled eye
Add translate for disabled eye
> i18n(layer-item): add translate for disabled eye

- packages/geo/src/lib/layer/shared/layers/layer.interface.ts
- packages/geo/src/lib/layer/utils/outputLegend.ts
- packages/geo/src/lib/print/shared/print.service.ts
The legend of some hidden layer are printed.
With the display property, filter which layer's legend is printed. 
> fix(print): handle display of legend

- packages/geo/src/lib/print/shared/print.service.ts
- packages/geo/src/lib/workspace/shared/edition-workspace.service.ts
- packages/geo/src/lib/workspace/shared/wms-workspace.service.ts
1- wms/wfs layer with workspace show blue features on printing output
2- when printing, the legend shown in the print output differ than the one shown in the legend tool .
Fix it. 
> Print fixes

- packages/common/src/lib/entity/shared/state.ts
- packages/common/src/lib/entity/shared/store.md
- packages/geo/src/lib/map/shared/controllers/view.ts
- packages/integration/src/lib/workspace/workspace.state.ts
add new method getSelectedFeature
** need to be test with https://github.com/infra-geo-ouverte/igo2/pull/796
> feat(workspaceState) add method workspaceSelection 

- packages/geo/src/lib/metadata/metadata-button/metadata-button.component.ts
- packages/integration/src/lib/filter/spatial-filter-tool/spatial-filter-tool.component.ts
Spatial filter zone isn't render correctly (ol render feature error)
With external layer, always showed url even when it wasn't defined
Spatial filter zone is render correctly
With external layer, abstract is showed when url isn't defined
> fix(catalog/spatial-filter): 1.12.0 fix

- packages/core/src/style/themes/bluedq.theme.scss
new color in themedq change:  primary, onHover and select
@marclonfo
> fix(bluedq.theme.scss) change colors in theme DQ

- .github/workflows/codeql-analysis.yml
> chore(codeql): Move to codeql v2 (issue 1071)

- packages/common/src/lib/entity/entity-table/entity-table.component.html
- packages/common/src/lib/entity/entity-table/entity-table.component.ts
Bug with edition autocomplete selection
Fix edition autocomplete selection
> fix(entity-table): fix edition autocomplete

- demo/src/app/app.component.scss
- demo/src/app/app.module.ts
- gulpfile.js
- packages/core/src/style/theming.scss
- packages/core/src/style/typography.scss
material core theming is imported from igo custom theming
material core theming is now imported globally within typography scss
> fix(theming): fix global core import

- packages/geo/src/lib/filter/time-filter-form/time-filter-form.component.html
- packages/geo/src/lib/filter/time-filter-form/time-filter-form.component.scss
> Fix(time-filter css) 

- packages/context/src/lib/context-map-button/poi-button/poi-button.component.scss
- packages/integration/src/lib/measure/measure.state.ts
Error is sometimes trigger on context change with measures already displaying on the map
Minor CSS fix on pois mat-select label
Fixed
> fix(measure-poi): fix measure state layer init / CSS poi fix

- package.json
- packages/auth/package.json
- packages/common/package.json
- packages/context/package.json
- packages/core/package.json
- packages/geo/package.json
- packages/integration/package.json
- packages/utils/package.json
> chore(package): author update

- demo/src/app/geo/search/search.component.html
- demo/src/app/geo/search/search.component.ts
- packages/common/src/lib/context-menu/context-menu.directive.ts
- packages/common/src/lib/context-menu/context-menu.module.ts
- packages/common/src/lib/context-menu/index.ts
- packages/common/src/lib/context-menu/long-press.directive.ts
Context menu do not work on ios
Fix it and modify search demo. 
fix https://github.com/infra-geo-ouverte/igo2-lib/issues/1100
> fix(contextmenu): handle ios mobile device

- packages/context/src/lib/share-map/share-map.module.ts
- packages/context/src/lib/share-map/share-map/share-map-url.component.html
- packages/context/src/lib/share-map/share-map/share-map-url.component.scss
- packages/context/src/lib/share-map/share-map/share-map-url.component.ts
- packages/context/src/locale/en.context.json
- packages/context/src/locale/fr.context.json
THe share clarifications are not editable. 
Add a custom html component where values are provided by translations
> feat(share): add custom html for clarification

- demo/src/app/geo/hover/hover.component.ts
- packages/geo/src/lib/map/shared/hover-feature.directive.ts
Hover feature label is flashing when hover on the same feature
Feature properties is lost when transfering in renderFeature
Hover feature label doesn't flash anymore
Feature properties isn't lost anymore
> fix(hover): fix flashing feature and property transfer

- packages/geo/src/lib/feature/feature-details/feature-details.component.ts
refer to https://github.com/infra-geo-ouverte/igo2/issues/861
> fix(googleLinks): links were broken

- package.json
GHpage did not work correctly since 1.13 release.
Fix it. 
> chore(ghpages): fix release of gh pages

- packages/common/src/lib/image/image-error.directive.ts
When using paths subsequent to domain, the fallback image is not found
Fix it.
> fix(imgerror): relative path is used

- demo/src/app/app.component.scss
- packages/context/src/lib/context-manager/context-list/context-list.component.scss
Mat-icon suffix isn't rightly sized
Fix
> fix(app): fix mat-icon suffix css

- packages/geo/src/lib/query/shared/query.service.ts
A service was causing an infinite loop on query.
Generate a geometry based on query click
> fix(query): undefined geometry handling

- packages/geo/src/lib/import-export/shared/export.service.ts
Layer name with ’ cause export crash (ogre).
Replace ’ by '
;)
> fix(export): layer name with ’ cause export crash (ogre).

- packages/auth/src/lib/shared/auth.service.ts
- packages/context/src/lib/share-map/shared/share-map.service.ts
We're not allowed to force language other than by auth service or browser params
https://github.com/infra-geo-ouverte/igo2/pull/881 
Allowed forced language by url param to override auth service locale
> feat(auth): allow language force to bypass user locale

- packages/geo/src/lib/search/search-bar/search-bar.component.html
The search button is displayed before the reset button, when applicable
The reset button is now displayed before the search button, when applicable
> ui(search-bar): Invert reset button and search button

- packages/geo/src/lib/search/shared/sources/icherche.ts
- packages/geo/src/locale/en.geo.json
- packages/geo/src/locale/fr.geo.json
Rest area and cycle stops are now searchable
icherche source are now alpha sorting
> feat(icherche): ajout des haltes cyclables et routières

- demo/src/app/geo/query/query.component.html
- demo/src/app/geo/query/query.component.ts
- packages/geo/src/lib/query/shared/query.service.ts
When using queryUrl, the computed bbox isn't right (only take the map view extent)
QueryUrl now use ol extent method
> fix(query): fix query url bbox param

- gulpfile.js
- packages/core/src/style/themes/bluedark.scss
- packages/core/src/style/themes/bluedark.theme.scss
> feat (theme) - Add new bluedark theme

- packages/geo/src/lib/search/search-results/search-results.component.ts
When searching for a exactmatch, there is no method to get more results if there is some available.
fix it.
> fix(search-result): allow more results on a filtered state

- packages/common/src/lib/entity/entity-table/entity-table.component.ts
Si on ne met pas visible dans la définition de l'attribut date, il n'est pas ajouté au formGroup
l'attribut visible n'est plus obligatoire pour l'édition de date
> Fix du paramètre visible obligatoire pour faire l'édition d'une date

- packages/geo/src/lib/map/baselayers-switcher/mini-basemap.component.ts
minimap view doesn't refresh correctly
Fix
> fix(minmap): fix minimap view change

- demo/src/app/geo/catalog/catalog.component.html
- demo/src/app/geo/catalog/catalog.component.ts
> fix(demo): unable to add layers from the catalog

- packages/core/src/lib/language/shared/language.service.ts
- packages/geo/src/lib/search/shared/sources/coordinates.ts
- packages/geo/src/lib/search/shared/sources/icherche.ts
- packages/geo/src/lib/search/shared/sources/ilayer.ts
When reloading the language (e.g. url control "lang"), search source titles were not reloaded with the new language
search source titles are reloaded with the new language
> fix(search-source): fix language reload on search source

- packages/geo/src/lib/draw/draw/draw.component.ts
> fix(draw): error with layers with numeric id

- packages/common/src/lib/confirm-dialog/confirm-dialog.service.ts
> feat(confirm-dialog): now support translations

- packages/common/src/lib/context-menu/long-press.directive.ts
long press event was emitted also on multitouch event
Only emit longpress event on single touch event.
> fix(longpress): prevent multitouch event emissioon

- packages/geo/src/lib/import-export/shared/import.utils.ts
- packages/geo/src/lib/layer/shared/layers/layer.interface.ts
- packages/geo/src/lib/workspace/shared/feature-workspace.service.ts
- packages/integration/src/lib/search/search.state.ts
All feature workspace were indexed and searchable in search bar.
Add option to control of a workspace should be indexed or not. 
> feat(workspace):add option to index or not content

- packages/geo/src/lib/offline/geoDB/configFileToGeoDB.service.ts
Loaded geojson were wrongly encoded. 
Fix it.
> fix(zippedGeojson): fix utf8 encoding error

- packages/geo/src/lib/print/shared/print.service.ts
This update relate to the issue [488](https://github.com/infra-geo-ouverte/igo2-lib/issues/488) in igo2.
Add attribution and copyright if we export the ma to image or pdf
> fix(geo): add attribution and copyright if export pdf or image

- packages/geo/src/lib/import-export/import-export/import-export.component.ts
…d in config
export formats were wrong if allowed formats were imposed in config
Let layer have their own export formats.. and filter those formats based on export's format defined in config.
> fix(export): export formats were wrong if allowed formats were imposed in config

- packages/geo/src/lib/feature/shared/feature.utils.ts
- packages/geo/src/lib/map/shared/controllers/geolocation.ts
> refactor(geolocation): adjusting threshold for speed detection

- packages/core/src/lib/request/error.interceptor.ts
- packages/geo/src/lib/catalog/catalog-browser/catalog-browser-group.component.ts
- packages/geo/src/lib/catalog/catalog-browser/catalog-browser-layer.component.ts
- packages/geo/src/lib/catalog/catalog-browser/catalog-browser.component.ts
- packages/geo/src/lib/catalog/shared/catalog.interface.ts
- packages/geo/src/lib/search/search-results/search-results-add-button.component.ts
1-Service returning empty response when unautorized (or other status) crash error handler. 
2-Adding layer from search results is sometime impossible. https://github.com/infra-geo-ouverte/igo2/issues/946
1-Prevent empty error. (fix(core): empty intercepted error)
2- Fix it => [fix(add layer): undefined event](https://github.com/infra-geo-ouverte/igo2-lib/pull/1248/commits/df41eba77ab552848d2faf38daf38b4578c8bdc8)
> Minor fixes

- packages/context/src/lib/context-manager/shared/layer-context.directive.ts
- packages/utils/src/lib/object-utils.ts
Rework single subscription to remove error
https://github.com/infra-geo-ouverte/igo2-lib/issues/1271
> fix(LayerContext): subscribe once with first operator

- .vscode/launch.json
- .vscode/tasks.json
Add launch configuration to enable debugging in vscode with breakpoints.
For testing launch de run and debug config:
> Feat vscode debugging

- packages/geo/src/lib/search/shared/sources/icherche.ts
- packages/geo/src/locale/en.geo.json
- packages/geo/src/locale/fr.geo.json
N/A
Insert hashtag# to acces culture layers
N/A
> ajout_culture_ashtag

- packages/geo/src/lib/style/shared/feature/feature-style.ts
> Exported context, draw layer with radius

- package-lock.json
- packages/geo/package.json
- packages/geo/src/lib/draw/draw/draw.module.ts
- packages/geo/src/lib/layer/layer.module.ts
- packages/geo/src/lib/style/style.module.ts
> fix(ColorPicker): remove unused deps

- packages/core/src/lib/config/config.service.ts
There is no method to retrieve global configs
add method to retrieve global configs (merge of environnement.ts and config.json)
> feat(core): add method to retrieve global configs

- packages/common/src/lib/entity/entity-table/entity-table.component.html
- packages/common/src/lib/entity/entity-table/entity-table.component.ts
- packages/geo/src/lib/feature/shared/strategies/geo-properties.ts
- packages/geo/src/lib/feature/shared/strategies/in-map-extent.ts
- packages/geo/src/lib/feature/shared/strategies/in-map-resolution.ts
There is a laggy behavior when handling large datasets inside workspace tables.
Optimize calculation and debounce time some state calculation 
> Performance - entity table related to workspaces

- demo/src/app/geo/layer/layer.component.ts
- packages/geo/src/lib/datasource/shared/datasources/wfs-datasource.ts
- packages/geo/src/lib/datasource/shared/datasources/wms-wfs.utils.ts
- packages/geo/src/lib/filter/shared/ogc-filter.ts
- packages/geo/src/lib/layer/shared/layers/vector-layer.ts
on 16.0.0 release branch, the wfs is not loading properly.
Remove urlfunction from wfs and let the custom wfs loader do his job.
> Wfs fix loading issues

- packages/geo/src/lib/filter/ogc-filterable-item/ogc-filterable-item.component.scss
https://github.com/infra-geo-ouverte/igo2-lib/issues/1441
Fix it.
> fix(ogcFilter): v16 regression, let the button being clickable when header=false

- packages/core/src/theming/typography.scss
https://github.com/infra-geo-ouverte/igo2/issues/1024
> 1024 typography adjustment

- packages/geo/src/lib/layer/layer-list-tool/layer-list-tool.theming.scss
- packages/geo/src/lib/search/search-bar/search-bar.theming.scss
- packages/geo/src/lib/search/search-results/search-results-item.theme.scss
- packages/geo/src/lib/search/search.theming.scss
https://github.com/infra-geo-ouverte/igo2-lib/issues/1361
> fix(geo): style regression with the material theme

- packages/geo/src/lib/layer/layer-item/layer-item.component.scss
- packages/geo/src/lib/layer/layer-item/layer-item.theme.scss
- packages/geo/src/lib/layer/layer.theming.scss
https://github.com/infra-geo-ouverte/igo2/issues/1052
> fix(geo): layer - visibility button style regression

- packages/geo/src/lib/map/baselayers-switcher/baselayers-switcher.component.html
- packages/geo/src/lib/map/baselayers-switcher/baselayers-switcher.component.scss
- packages/geo/src/lib/map/baselayers-switcher/mini-basemap.component.ts
- packages/geo/src/lib/map/map-browser/map-browser.component.ts
https://github.com/infra-geo-ouverte/igo2/issues/1063
> 1063 laffichage des fonds de carte est décallé

- packages/context/src/lib/context-manager/context-list/context-list.component.html
- packages/context/src/lib/context-manager/context-list/context-list.component.scss
Correction du problème d'affichage. Le premier point est non réplicable de mon côté.
L'issue originale provenant de JIRA:
J'ai un problème au niveau des contextes (voir l'image ci-dessous). Comme vous pouvez le voir, j'ai désélectionner l'ensemble des contextes que je possède et malgré tout, j'ai encore plusieurs contextes dans mon catalogue et ils ne disparaissent pas 
Également, ça doit être un problème d'affichage, mais ce serait bien que le carré de sélection soit vis-à-vis le texte qui leur est affilié, parce qu'actuellement, ils sont l'un par dessus l'autre de mon côté!
> fix(context): list style regression

- packages/context/src/lib/context-map-button/context-map-button.module.ts
- packages/context/src/lib/context-map-button/poi-button/poi-button.component.html
- packages/context/src/lib/context-map-button/poi-button/poi-button.component.scss
> fix(context): poi-button style regression

- .github/workflows/gh-release.yml
- .npmrc
github version is push without v preffix. 
let the v preffix 
> chore(npmrc): remove tag-version-prefix

- packages/geo/src/lib/print/print-form/print-form.component.html
- packages/geo/src/lib/print/shared/print.type.ts
- packages/geo/src/locale/en.geo.json
- packages/geo/src/locale/fr.geo.json
> fix(geo): print - remove 300 PPI resolution

- packages/common/src/lib/context-menu/context-menu.directive.ts
this behavior related to #1332  
> fix(common): Context menu doesn't work on Firefox

- packages/geo/src/lib/import-export/shared/export.service.ts
This behavior related to  [#1081](https://github.com/infra-geo-ouverte/igo2/issues/1081) .
solve download issue if the used device is android.
> fix(geo): solve export file on mobile android using uri

- packages/geo/src/lib/print/print/print.component.ts
- packages/geo/src/lib/print/shared/print.service.ts
this behavior related to #1502 
> fix(geo): detect map print extent after change map resolution

- packages/common/src/lib/entity/entity-table/entity-table.component.ts
this behavior related to #1512 
> fix(common): solve Select or unselect all rows at once

- packages/geo/src/lib/style/style-modal/layer/style-modal-layer.component.ts
this behavir related to #1508 
> fix(geo): color picker with style modal layer

- projects/demo/src/app/geo/hover/hover.component.ts
- projects/demo/src/app/geo/layer/layer.component.ts
- projects/demo/src/app/geo/legend/legend.component.ts
- projects/demo/src/app/geo/ogc-filter/ogc-filter.component.ts
- projects/demo/src/app/geo/print/print.component.ts
- projects/demo/src/contexts/_default.json
- projects/demo/src/environments/environment.prod.ts
- projects/demo/src/environments/environment.ts
this behavior related to #1555 
> fix(demo): Repoint web services in assembly demo

- projects/demo/src/app/geo/layer/layer.component.ts
N/A
Added layer with multiples styles available. See https://github.com/infra-geo-ouverte/igo2-lib/pull/1549#discussion_r1437093818
> demo(layer): added layer showcasing multiple styles

- packages/geo/src/lib/datasource/shared/datasources/carto-datasource.ts
this behavior related to #1528 (check the comment in the issue)
> fix(geo): check legend before loop

- packages/auth/package.json
- packages/common/package.json
- packages/context/package.json
- packages/core/package.json
- packages/geo/package.json
- packages/integration/package.json
- packages/utils/package.json
- scripts/src/build-library.ts
- scripts/src/core/clean-exports.ts
> fix(build): clean up exports in the distributed package.json #1616

- packages/geo/src/lib/print/shared/print.service.ts
this behavior related to #1593 
> feat(geo): change printed text to Sans Serif font

- packages/auth/src/locale/en.auth.json
- packages/auth/src/locale/fr.auth.json
- [X ] The commit message follows our guidelines:https://github.com/infra-geo-ouverte/igo2/blob/master/.github/CONTRIBUTING.md#git-commit-guidelines
N/A
N/A
N/A
i18n: Translation
> i18n(accessAnonymous):change of label to public access

- packages/common/src/lib/entity/shared/transaction.ts
The interface `EntityOperation` is nor longe exported.
The interface `EntityOperation` is exported once again.
> fix(transaction): Export EntityOperation like it used to

- packages/integration/src/lib/search/search.state.ts
> fix(integration): check if workspace search source is defined

- packages/geo/src/lib/import-export/shared/drop-geo-file.directive.ts
- packages/geo/src/lib/map/shared/projection.utils.ts
fix https://github.com/infra-geo-ouverte/igo2/issues/1146
> Fix importing vector

- .vscode/extensions.json
- package-lock.json
- package.json
- packages/context/package.json
- packages/geo/package.json
- packages/geo/src/lib/datasource/shared/datasources/arcgisrest-datasource.ts
- packages/geo/src/lib/datasource/shared/datasources/cluster-datasource.interface.ts
- packages/geo/src/lib/datasource/shared/datasources/datasource.ts
- packages/geo/src/lib/datasource/shared/datasources/feature-datasource.interface.ts
- packages/geo/src/lib/datasource/shared/datasources/feature-datasource.ts
- packages/geo/src/lib/datasource/shared/datasources/websocket-datasource.ts
- packages/geo/src/lib/datasource/shared/datasources/wfs-datasource.interface.ts
- packages/geo/src/lib/datasource/shared/datasources/wfs-datasource.ts
- packages/geo/src/lib/datasource/shared/datasources/wms-datasource.interface.ts
- packages/geo/src/lib/draw/draw/draw.component.ts
- packages/geo/src/lib/filter/shared/ogc-filter.interface.ts
- packages/geo/src/lib/geometry/geometry-form-field/geometry-form-field-input.component.ts
- packages/geo/src/lib/geometry/shared/controls/draw.ts
- packages/geo/src/lib/geometry/shared/controls/slice.ts
- packages/geo/src/lib/import-export/import-export/import-export.component.ts
- packages/geo/src/lib/layer/shared/layers/vector-layer.interface.ts
- packages/geo/src/lib/layer/shared/layers/vector-layer.ts
- packages/geo/src/lib/measure/measurer/measurer.component.ts
- packages/geo/src/lib/query/shared/query.directive.ts
- packages/geo/src/lib/query/shared/query.interfaces.ts
- packages/geo/src/lib/search/search-results/search-results-add-button.component.ts
- packages/geo/src/lib/style/shared/vector/conversion.utils.ts
- packages/integration/src/lib/filter/spatial-filter-tool/spatial-filter-tool.component.ts
- packages/integration/src/lib/map/map-proximity.state.ts
- projects/demo/src/app/geo/spatial-filter/spatial-filter.component.ts
> feat(geo): update Openlayers to v9

- packages/common/icon/src/shared/icons.ts
- packages/geo/src/lib/catalog/catalog-library/catalog-library.component.html
- packages/geo/src/lib/catalog/catalog-library/catalog-library.component.ts
- packages/geo/src/lib/layer/layer-list/layer-list.component.html
- packages/geo/src/lib/layer/layer-list/layer-list.component.ts
- packages/integration/src/lib/catalog/catalog-library-tool/catalog-library-tool.component.ts
- packages/integration/src/lib/map/advanced-map-tool/advanced-swipe/advanced-swipe.component.html
- packages/integration/src/lib/map/advanced-map-tool/advanced-swipe/advanced-swipe.component.ts
- packages/integration/src/lib/map/map-details-tool/map-details-tool.component.html
- packages/integration/src/lib/map/map-legend/map-legend-tool.component.html
- packages/integration/src/lib/map/map-tools/map-tools.component.html
Some svg icons were available into the google font icons library
> refactor(*): move from svg to library icons

- commitlint.config.ts
- git-hooks/commit-msg
- package-lock.json
- package.json
Validate and lint the commit message with the conventionnal rules
> fix: lint commit message

- packages/geo/src/lib/draw/draw/draw.component.ts
- packages/geo/src/lib/style/style-modal/layer/style-modal-layer.component.html
- packages/geo/src/lib/style/style-modal/layer/style-modal-layer.component.scss
Elements were not aligned and some css were unused
Align this + css cleanup
> refactor(geo): adjustments for style modal layer color picker

- packages/geo/src/lib/feature/feature-details/feature-details.component.ts
When the user was clicking on a link in the feature-details and that link was embedded (i.e <a></a>) and directed to the Depot API, the regex expression was incorrect.
The regex expression has been fixed.
> fix(feature-details): fix depot url regex

- package-lock.json
- packages/geo/package.json
- packages/geo/src/lib/directions/shared/directions.service.ts
- packages/geo/src/lib/workspace/shared/feature-workspace.service.ts
- packages/geo/src/lib/workspace/shared/wfs-workspace.service.ts
- packages/integration/package.json
- packages/integration/src/lib/workspace/shared/workspace.utils.ts
Si vous pouvez tester les différentes partie.
Pour les workspaces ce n'est pas vraiment testable, a moins de cherry picker le commit de la PR  https://github.com/infra-geo-ouverte/igo2-lib/pull/1731
> fix(deps): upgrade jspdf-autotable to version 5.0.2 and update import statements

- packages/geo/src/lib/layer/layer-item/layer-item.component.ts
> fix(geo): manage tooltip for layer button

- packages/geo/src/lib/datasource/shared/capabilities.service.ts
- packages/geo/src/lib/datasource/shared/datasources/wfs-datasource.ts
- packages/geo/src/lib/datasource/shared/datasources/wms-datasource.interface.ts
- packages/geo/src/lib/datasource/shared/datasources/wms-datasource.ts
- packages/geo/src/lib/datasource/shared/datasources/wms-wfs.utils.ts
- packages/geo/src/lib/filter/ogc-filter-time/ogc-filter-time.component.ts
- packages/geo/src/lib/filter/shared/date.utils.ts
- packages/geo/src/lib/filter/shared/filter.utils.ts
- packages/geo/src/lib/filter/shared/ogc-filter.interface.ts
- packages/geo/src/lib/filter/shared/ogc-filter.service.ts
- packages/geo/src/lib/filter/shared/ogc-filter.ts
- packages/geo/src/lib/filter/shared/time-filter.interface.ts
- packages/geo/src/lib/filter/shared/time-filter.service.ts
- packages/geo/src/lib/filter/time-filter-form/time-filter-form.component.ts
- packages/geo/src/lib/filter/time-filter-item/time-filter-item.component.html
- packages/geo/src/lib/filter/time-filter-item/time-filter-item.component.ts
- packages/geo/src/lib/layer/layer-legend/layer-legend.component.ts
Many fixes for the OGC and Time filter.
> Fix OGC and time filters

- packages/geo/src/lib/datasource/shared/datasource.service.ts
- packages/geo/src/lib/datasource/shared/datasources/wfs-datasource.interface.ts
- packages/geo/src/lib/datasource/shared/datasources/wfs-datasource.ts
- packages/geo/src/lib/datasource/shared/datasources/wms-datasource.ts
- packages/geo/src/lib/datasource/shared/datasources/wms-wfs.utils.ts
- packages/geo/src/lib/filter/ogc-filterable-item/ogc-filterable-item.component.ts
- packages/geo/src/lib/filter/shared/ogc-filter.interface.ts
- packages/geo/src/lib/filter/shared/ogc-filter.service.ts
Cette PR est basé sur la branche feature/ogc-params, faire la revue de cette PR en premier https://github.com/infra-geo-ouverte/igo2-lib/pull/1723
fix(geo): ogc-filter apply on initial datasource load
> Fix OGC filter apply on initial datasource load

- package-lock.json
- packages/geo/ng-package.json
- packages/geo/package.json
- packages/geo/src/lib/geometry/shared/geometry.utils.ts
- packages/geo/src/lib/workspace/widgets/interactive-selection/interactive-selection.component.html
- packages/geo/src/lib/workspace/widgets/interactive-selection/interactive-selection.component.scss
- packages/geo/src/lib/workspace/widgets/interactive-selection/interactive-selection.component.ts
- packages/geo/src/lib/workspace/widgets/ogc-filter/ogc-filter.component.scss
- packages/geo/src/lib/workspace/widgets/widgets.ts
- packages/geo/src/lib/workspace/workspace.module.ts
- packages/geo/src/locale/en.geo.json
- packages/geo/src/locale/fr.geo.json
- packages/integration/src/lib/workspace/shared/feature-actions.service.ts
- packages/integration/src/lib/workspace/shared/wfs-actions.service.ts
- packages/integration/src/lib/workspace/shared/workspace.utils.ts
- packages/integration/src/locale/en.integration.json
- packages/integration/src/locale/fr.integration.json
https://github.com/infra-geo-ouverte/igo2-lib/issues/1629
https://github.com/infra-geo-ouverte/igo2-lib/issues/1629
add a widget to workspace to select features by geometry
Must be merge and tested after merging this PR https://github.com/infra-geo-ouverte/igo2/pull/1142 
> feat(*): add a widget to workspace to select features by geometry

- LICENSE
- packages/geo/src/lib/layer/layer-unavailable/layer-unavailable-list/layer-unavailable-list.component.ts
https://github.com/infra-geo-ouverte/igo2-lib/issues/1770
Fixing the error in Angular that an import is missing for *ngFor
No breakings changes
> fix(layer-unavailable-list): fix missing import

- package-lock.json
- packages/core/language/src/shared/language-mock.provider.ts
- packages/core/language/src/shared/language.provider.ts
- packages/core/package.json
Mise à jour de la librairie de translation
> chore(deps): update ngx-translate to v17

- .github/workflows/pull-request.yml
> chore(*): ensure the demo build successfully

- packages/geo/src/lib/workspace/shared/workspace.utils.ts
> fix(workspace): propagate field visibility to workspace template

- packages/core/environment/src/environment.interface.ts
> fix(core): environement options is back after v17 refactor
